### ISSUE TITLE
Python 3.8 on Amazon Linux 2 platform

### ISSUE THREAD

**Issue by chicheng** [aws/elastic-beanstalk-roadmap#100]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

[Python 3.8 was released in Oct 2019](https://www.python.org/downloads/release/python-380/), it will receive bugfix updates until early 2021, then security updates until Oct 2024.

Potential integration: #28 Full Django framework support (GIS libraries on Python platform)

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-02-26-al2.html
