### ISSUE TITLE
Document prescribed method to serve static files from / rather than /public in Ruby platforms

### ISSUE THREAD

**Issue by craustin** [aws/elastic-beanstalk-roadmap#102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
ElasticBeanstalk Ruby platforms (both AL1 + 2) include a default `nginx` config to serve static files from `/public` @ `/public` and `/public/assets` @ `/assets`. Though, idiomatic Rails serves files from `/public` at `/` - so I'd like a prescribed way to change this. I propose an addition to the docs to describe a prescribed method for this as this must be a _very common_ change for EBS + Rails users.

Alternatively, I'd support changing the EBS Ruby platform default static path config, but I figure that's a challenging change to make at this point - even though it's likely a better default.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
The EBS-standard `nginx` config is present in all Ruby AWS platforms.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm trying to serve static files using `nginx` (not Puma) from `/` and not the default `/public`. This is difficult because it requires customizing the default `nginx` config - and that can be error prone. There are many StackOverflow answers with convoluted `nginx` configs that attempt to resolve this, but it would be nice to have an AWS-sanctioned one. Also, an incorrect config here may inadvertently serve the application code, which could be very bad.

**Are you currently working around this issue?**
I'm using a custom `nginx` config.

**Additional context**
Here's a thread from many years ago discussing this issue - and a reply from 2018 from Amazon's "chrisw" acknowledging the issue, but he didn't follow up with a canonical method for resolving this:
https://forums.aws.amazon.com/thread.jspa?start=25&threadID=150904&tstart=0

Here's where this common requirement should probably be mentioned in the docs:
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_Ruby.container.html#create_deploy_Ruby.container.console.staticfiles

**Comment by mrenneke-amazon** [comment]
Unfortunately, it turns out that this isn’t a documentation issue.   The Elastic Beanstalk Developer Guide provides [static file configuration procedures](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_Ruby.container.html#ruby-namespaces).  However, the configuration you are asking about  (` / : public `)  is not supported with the default configuration that Elastic Beanstalk delivers for Nginx.   Perhaps an alternate approach may be considered, but there is not one at this point in time.

**Comment by craustin** [comment]
Thanks for your response! It would be helpful to note in those docs that hosting static files at `/` is not supported with the default Elastic Beanstalk `nginx` config. My original suggestion though was to provide an alternate approach (requiring custom `nginx` config), as you mention - since this is a common scenario.

**Comment by mrenneke-amazon** [comment]
I will add that note to the Ruby Platform chapter of the guide, and will also update it accordingly should anything change in that area.  Thanks for that feedback!

**Comment by mrenneke-amazon** [comment]
Hello again!  

We have released an AL2 Ruby platform version with an nginx configuration that serves static assets (in the `public/` directory)  from both `/public `and domain root ` /  `.   This update was included in the October release of **Ruby AL2 platform version 3.3.7.**
The **Static Files** section of the [Ruby Platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_Ruby.container.html#create-deploy_Ruby.container.CON) topic in the _Elastic Beanstalk Developer Guide_ describes this new configuration.
Please see roadmap issue [#187](https://github.com/aws/elastic-beanstalk-roadmap/issues/187) for more information.

Thank you for your feedback and patience!
