### ISSUE TITLE
Support "networkMode:host" for multi container Docker environments

### ISSUE THREAD

**Issue by Bob-Iwamoto** [aws/elastic-beanstalk-roadmap#104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Please add the feature to configure the Docker network mode (host, bridge or none) inside the dockerrun.aws.json file used by Elastic Beanstalk with Docker-related environments.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?
No.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The feature enables us to run container applications that need to refer the IP address of host. (because some applications do not work with NAPT.)

**Are you currently working around this issue?**
No.

**Additional context**
It is ok to support Amazon Linux 2 first, if it is more feasible to do so.

**Comment by Sekhar-Kutikuppala** [comment]
Hi @Bob-Iwamoto Thanks for the feedback. We are adding this support in Docker on AL2 platforms where you define multiple containers and the network mode in docker-compose.yml file

**Comment by Sekhar-Kutikuppala** [comment]
#8

**Comment by Bob-Iwamoto** [comment]
Understood, Sekhar! Really appreciated.

Bob

**Comment by Sekhar-Kutikuppala** [comment]
Launched this feature along with support for running multi-container applications using AL2 based Docker platform
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker-multicontainer-migration.html

**Comment by miguelcss** [comment]
Hello @Sekhar-Kutikuppala , how can we enable this using the recomended AL2 single docker container (aka ```"AWSEBDockerrunVersion": "1"``` ? 

thanks in advance
