### ISSUE TITLE
Bug in Elastic Beanstalk Shared ALB Feature when default VPC is deleted

### ISSUE THREAD

**Issue by awskrishnakancharla** [aws/elastic-beanstalk-roadmap#109]
When the default VPC of the region is deleted, Elastic Beanstalk environment creation fails when I try to launch an environment with the shared ALB configuration. 

Steps to replicate issue :
- Deleted Default VPC of the region
- I created an Application Load balancer via EC2 console and specified a listener
- On the Elastic Beanstalk console, I launched a sample environment, I selected the VPC and subnets for Load balancer and instances in Networking section.
- In the Load balancer section, I selected the application load balancer and opted for shared load balancer.
- Provided the arn for the load balancer and specified the port.
- Save and deploy. This created the first environment associated with the load balancer correctly.

After this, I followed the exact same steps for the second environment but it failed with the error message "No default VPC for this user”.

As a workaround, I created a default vpc in the region and tried to launch the environment again with the same configuration settings. I was able to create the environments with the shared load balancer.

Kindly look into this,

Krishnaditya K.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Comment by Sekhar-Kutikuppala** [comment]
Hi @dkknch Thank you for the feedback. We are looking into this issue

**Comment by rahulrajaram** [comment]
@dkknch  This should now be resolved. Can you please check?

Closing for now, please reopen if issue persists.
