### ISSUE TITLE
Node.js on Amazon Linux 2 platform

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#11]
We're working on building out this and other platforms on top of Amazon Linux 2 (AL2). With our AL2 platforms, we are refreshing and rethinking each platform based on feedback we’ve gotten from customers. If you have any questions or suggestions for this platform, please add a comment in the issue.

**Comment by derN3rd** [comment]
Are there any roadmaps for specific versions of node? The only LTS supported version that is online right now on beanstalk is node 10.
Is there an estimate when node 12 will be available?

Thanks in advance

**Comment by labisso** [comment]
hey @derN3rd - Node.js 12 support on Amazon Linux 2 will be available very soon :)

**Comment by juho** [comment]
@labisso could you give a more exact estimate?

**Comment by Sekhar-Kutikuppala** [comment]
Node.js on AL2 platform is now generally available
[Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-04-30-al2.html)
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/04/aws-elastic-beanstalk-announces-general-availability-of-amazon-linux-2-based-node-js-php-go-and-ruby-platforms/)
