### ISSUE TITLE
Unintuitive navigation inside "Configuration" panel

### ISSUE THREAD

**Issue by benmolin** [aws/elastic-beanstalk-roadmap#113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Go to an App -> Configuration (left menu) -> Software (Edit). Then click on "Configuration" again, and nothing happens.

I'd like for that click to take you back to the "Configuration overview" instead, like how the cancel button at the bottom of the page works. I always click "Logs" then go back to "Configuration."

**Comment by Sekhar-Kutikuppala** [comment]
Thank you for the feedback. We will evaluate this
