### ISSUE TITLE
Will Beanstalk support Correto 15 in the near future?

### ISSUE THREAD

**Issue by marceloverdijk** [aws/elastic-beanstalk-roadmap#115]

**Comment by 1tonyca** [comment]
Thanks for your interests, would it be okay to track Corretto 17 (LTS) support via [https://github.com/aws/elastic-beanstalk-roadmap/issues/195](https://github.com/aws/elastic-beanstalk-roadmap/issues/195)

**Comment by 1tonyca** [comment]
Closing this in favor of tracking [#195](https://github.com/aws/elastic-beanstalk-roadmap/issues/195)
