### ISSUE TITLE
Tomcat 10 with Corretto

### ISSUE THREAD

**Issue by banbrick-dexxa** [aws/elastic-beanstalk-roadmap#116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

When will Tomcat 9 with Corretto or Java be available? Can this be added to the roadmap?

**Comment by kenyons** [comment]
Prebuilt Tomcat 9 platform would be great because it adds Servlet spec 4.0 which supports HTTP/2

**Comment by michael-mccutcheon** [comment]
Is there a reason this shouldn't be Tomcat 10?  It is the latest version of Tomcat, not 9.

**Comment by banbrick-dexxa** [comment]
Only 9 was available when I originally posted this. Tomcat 10 would be better.

**Comment by michael-mccutcheon** [comment]
@1tonyca Can this request be modified so that it states Tomcat 10 (not 9)?

**Comment by 1tonyca** [comment]
Yes, since @banbrick-dexxa (the original requester) also mentioned Tomcat 10 would be better, I would update the title to reflect so.

**Comment by namero999** [comment]
This will be needed for Spring 6, and we are not too far away from it..

**Comment by edwardsre** [comment]
Which versions of Corretto are you wanting them to target? @namero999 wants it for Spring 6 which would require Corretto 17.

**Comment by namero999** [comment]
I think Tomcat 10 and, most importantly, Java 17 are considered standard baseline nowadays. Java 17 support for Tomcat should really be there, now that is has shipped for regular Java Beanstalk.

The fact that 17 is required for Spring 6 is just an extra important motivation to ship it out sooner rather than later.

**Comment by PeterCai7** [comment]
Are there any thoughts about if we need Tomcat 10 with Java 8 & 11 or not, in addition to Java 17?

>If you migrate from Tomcat 9 to 10, you’ll have to change any calls from, java.* to jakarta.*. As an example, javax.servlet-api becomes jakarta.servlet-api. If you are migrating a large project, check out the [Apache Tomcat migration tool for Jakarta EE](https://github.com/apache/tomcat-jakartaee-migration).

https://www.infoworld.com/article/3510460/what-is-apache-tomcat-the-original-java-servlet-container.html

**Comment by namero999** [comment]
Tomcat 10 works on 8.
Tomcat 10.1, not far from being released and based on the freshly released Jakarta 10, requires 11.

Imho 11 is the new 8 and we'll need to support it for a while, but the world is ready to be nudged out of 8 :)

**Comment by jul69** [comment]
**Spring 6.0 / SpringBoot 3.0** will **require Tomcat 10 and Java17**... release scheduled for nov-22
It would be nice to see status _We're Working On It_ rather than _Researching_

**Comment by namero999** [comment]
Spring 6 released in General Availability. The most popular web framework is now unable to be run on AWS.

**Comment by PeterCai7** [comment]
When using SpringBoot 3.0 and selecting `Spring Web` dependency, the spring boot starter would help embedding a Tomcat 10.1.x into our bundle. Ref: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-tomcat/3.0.1
Therefore, folks who are using Spring Boot 3.0 should be able to run their applications on EB Corretto 17 platform.

**Comment by lisenet** [comment]
We need Corretto with Tomcat (version does not matter much, as we can accommodate Tomcat 8.5 or 9 or 10) and Java 17. This is currently blocking our migration path from an older version of Java to Java 17.

**Comment by PeterCai7** [comment]
Thanks for commenting. We are working on this.

**Comment by lisenet** [comment]
@PeterCai7 thanks. When you say "we're working on this", what does it actually mean? What stage are you currently at? Do you have any ETA?

**Comment by csetube** [comment]
We are also waiting for this. Can we have an ETA, So that we can plan our migration?
Java 8 support for Spring boot is ended by 2023 November as per the roadmap.
So a quick turnaround on this is appreciated.

**Comment by rzanon** [comment]
Hi Team, same there we are waiting for an ETA just to know if we can wait for you or if we have to move to another solution.
Any feedback will be appreciated.
Thank you

**Comment by PeterCai7** [comment]
Hi all,

We do not have an ETA yet. But we are investigating the ways we install Tomcat10.1 and evaluating the efforts needed to update our test apps due to mirgrations of Jarkata EE. It took more time to fully understand to changes from Tomcat 9 to Tomcat 10.1. Please stay tune and thank you for your patience.

**Comment by mariusropoticamambu** [comment]
Hi, since the end of life for Tomcat 8.5 is planned for May 2024 (https://tomcat.apache.org/tomcat-85-eol.html), can we expect Tomcat 10 with Corretto to be available until that date? Thanks.

**Comment by PeterCai7** [comment]
Tomcat 10 with Corretto 17 is out: https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-07-13-al2023.html

If you are still interested in Tomcat 9, please leave thumbs on the other issue: https://github.com/aws/elastic-beanstalk-roadmap/issues/285.

This issue should be marked as closed soon.

**Comment by AndreVelde** [comment]
Can we expect Corretto 11 also get Tomcat 10 or 9 support since Tomcat 8.5 will be end of life next year

**Comment by PeterCai7** [comment]
> Can we expect Corretto 11 also get Tomcat 10 or 9 support since Tomcat 8.5 will be end of life next year

We are considering them.

**Comment by gtiwari333** [comment]
What about JDK17 with Tomcat 9? Is there any plan for it? @PeterCai7

**Comment by dfsa3ws** [comment]
> > Can we expect Corretto 11 also get Tomcat 10 or 9 support since Tomcat 8.5 will be end of life next year
> 
> We are considering them.

@PeterCai7 Could you also consider adding Corretto 8 to Tomcat 10 or 9? The last Corretto 8 Tomcat platform has an end date of 2024-09-30. Thanks.

**Comment by lisenet** [comment]
@dfsa3ws just FYI, Tomcat 10.1 does not support Java 8.

**Comment by darin-holloway** [comment]
@dfsa3ws I've requested an AL2023 Tomcat 9 / Corretto 8 platform to bridge us through 2026 end of support on corretto 8 https://github.com/aws/elastic-beanstalk-roadmap/issues/317 

One thought I've had is using a AL2023 tomcat 9 corretto 11 platform and `dnf install corretto8` && `update-alternatives` as part of an ebextension if AWS won't/can't deliver, but that's obviously a bit hacky.

**Comment by PeterCai7** [comment]
We released Corretto8 Tomcat 9 on AL2 instead of AL2023 due to compatibility concerns. https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2024-01-29-al2.html
I think we may use it as a temporary bridge until AL2 end of life in 2025.

**Comment by darin-holloway** [comment]
@PeterCai7 That's fantastic, I missed that in the latest update, I'd still love a AL2023/tomcat 9/jdk 8 to buy another 6ish months until JDK8 falls off support, but this is a huge win for us.

**Comment by AshishDash** [comment]
@PeterCai7 Are you also releasing Corretto11 / Corretto17 with Tomcat 9 on AL2 ?

**Comment by PeterCai7** [comment]
@AshishDash 
Corretto 11 Tomcat 9 and Corretto 17 Tomcat 9 would probably be only on AL2023.

**Comment by praegt** [comment]
Closing this, please open a new issue for new Corretto / Tomcat platform requests
