### ISSUE TITLE
 Support the new Capacity Rebalancing feature for EC2 Auto Scaling

### ISSUE THREAD

**Issue by candrews** [aws/elastic-beanstalk-roadmap#123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?

[AWS introduced Capacity Rebalancing for EC2 Auto Scaling](https://aws.amazon.com/blogs/compute/proactively-manage-spot-instance-lifecycle-using-the-new-capacity-rebalancing-feature-for-ec2-auto-scaling/); this feature would be very helpful for Beanstalk.

Beanstalk should have a new ASG configuration option to enable Capacity Rebalancing as part of the existing spot configuration.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

This request is for Beanstalk at a whole - not for a specific Beanstalk platform.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Capacity rebalancing provides a more reliable, lower cost approach to spot instance management. Clearly this approach would be beneficial to Elastic Beanstalk.

**Are you currently working around this issue?**
How are you currently solving this problem?

Capacity rebalancing is not usable with Beanstalk right now so its advantages can't be realized. The current state is more expensive and less reliable than what will be possible once Beanstalk implements this feature.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by rennokki** [comment]
@candrews I guess the only workaround until an official release is to edit the ASG by yourself with a `.ebextensions/asg.conf` file, for example:

```config
Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html
  AWSEBAutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      CapacityRebalance: True
```

**Comment by ungarida** [comment]
The problem with any workaround is to cause a drift into the CloudFormation stack causing an inconsistent state. I would not recommend to change things manually.

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-08-09-release-notes.html

**Comment by akshayram-wolverine** [comment]
Whats new here: https://aws.amazon.com/about-aws/whats-new/2021/08/aws-elastic-beanstalk-capacity-rebalancing-amazon-ec2-spot-instances/
