### ISSUE TITLE
Support Corretto 15

### ISSUE THREAD

**Issue by uldall** [aws/elastic-beanstalk-roadmap#124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Add support for Corretto 15 as it has now been out for a bit over a month: https://aws.amazon.com/about-aws/whats-new/2020/09/announcing-general-availability-amazon-corretto-15/

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
The Java Corretto platform.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want to be able to use Java 15 in Elastic Beanstalk.

**Are you currently working around this issue?**
We are currently stuck on Java 11.

**Additional context**
No

**Attachments**
No attachments.

**Comment by darin-holloway** [comment]
OpenJDK 17 is the next scheduled LTS release, the corretto version based on that seems more likely for inclusion as an Elastic Beanstalk platform.

**Comment by marceloverdijk** [comment]
Indeed @darin-holloway Java 17 would make more sense because it is the next LTS.
It would be nice if AWS would provide some roadmap information what there plans are regarding support Beanstalk Java versions.

**Comment by namero999** [comment]
17 is now out. Any idea of when a new Beanstalk platform version will be available? And possibly, what tomcat version? 8.5? 9? Thanks.

**Comment by 1tonyca** [comment]
Thanks for your interests, would it be okay to track Corretto 17 support using [https://github.com/aws/elastic-beanstalk-roadmap/issues/195](https://github.com/aws/elastic-beanstalk-roadmap/issues/195)

**Comment by uldall** [comment]
> Thanks for your interests, would it be okay to track Corretto 17 support using #195

Yes that would be fine :)
