### ISSUE TITLE
Docker with Amazon Linux 2 on beanstalk doesn't start on boot & /tmp/ebbootstrap.sh failures

### ISSUE THREAD

**Issue by Sarah-E-Greene** [aws/elastic-beanstalk-roadmap#128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

This impacts the latest docker Amazon Linux 2 image:

AMI ID: ami-09a5174a98da90b1a
AMI Description: aws-elasticbeanstalk-amzn-2.0.20201028.64bit-eb_docker_amazon_linux_2-hvm-2020-11-06T06-09

When switching our existing beanstalk on amazon linux 1 and multi-container docker to the above ami, the startup scripts don't seem to work properly in a few ways (and thus, the docker containers for our application don't start):

- Docker is not configured to start on boot:

```
[ec2-user@ip-172-17-41-99 ~]$ sudo docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[ec2-user@ip-172-17-41-99 ~]$ sudo systemctl list-unit-files docker.service
UNIT FILE      STATE
docker.service disabled
1 unit files listed.
```

- /tmp/ebbootstrap.sh fails to run correctly, as initctl is not found

```
Nov 19 17:41:06 ip-172-17-53-2 eb-log: /tmp/ebbootstrap.sh: line 290: initctl: command not found
```

- ntpdate is being called, but ntpd is not running

```
Nov 19 17:40:30 ip-172-17-53-2 eb-log: Redirecting to /bin/systemctl stop ntpd.service
Nov 19 17:40:30 ip-172-17-53-2 eb-log: Failed to stop ntpd.service: Unit ntpd.service not loaded.
Nov 19 17:40:30 ip-172-17-53-2 eb-log: sh: ntpdate: command not found
```

Without these solved, we can't switch to these amazon linux 2 images, and we will be staying on amazon linux 1 (until it goes EOL)

**Comment by joshm91** [comment]
We just ran into the same thing today. Did you ever work out a fix @SarahRiley?

**Comment by Sarah-E-Greene** [comment]
@joshm91 We didn’t find a fix, we stuck with amazon linux 1 for now until AWS fixes this on their side.

**Comment by dsapab** [comment]
Hello @SarahRiley / @joshm91,

Thank you for reaching out. Based on the error you shared:

`Nov 19 17:41:06 ip-172-17-53-2 eb-log: /tmp/ebbootstrap.sh: line 290: initctl: command not found
`

It seems that the **/tmp/ebbootstrap.sh** script being downloaded and executed corresponds to an **Amazon Linux 1 platform**. Please note:

- In Amazon Linux 1, the daemons are managed via Upstart. Upstart configuration files are located at _/etc/init/_. 
- In Amazon Linux 2, the daemons are managed via SystemD. The configuration files are located at _/etc/systemd/system/_.
- **initctl** will only work in Amazon Linux 1 AMIs / platforms.
- Based on the error it seems that the [aws:autoscaling:launchconfiguration / ImageId setting](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalinglaunchconfiguration) is being populated with an Amazon Linux 2 AMI, but within an Amazon Linux 1 platform. 

**Can this be the case?** 

For utilising [Amazon Linux 2 Docker platform ](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.docker), a **new environment for the new platform must be launched using Docker AL2 version X.Y.Z**. For upgrading to Amazon Linux 2, It will not suffice (nor work) replacing the AMI with the latest one in the current environment. Each platform and version will download a specific revision for the _ebbootstrap.sh_ script. Amazon Linux 2 is a whole new platform and these AMIs will just work with the new platform. An Amazon Linux 2 AMI will not work in the older generation platforms (Single Container Docker version X.Y.Z /  Multicontainer Docker version X.Y.Z ).

Please let me know if this helps to narrow down the issue. Based on the input, seems to be related with this path. In any other case, please share details about the exact platform version and AWS Region being used.

Thank you for your time!

**Comment by joshm91** [comment]
@pablods90 You're absolutely correct. We figured this out a couple of weeks ago and I meant to mention it here but forgot. Thanks for reaching out!

**Comment by dsapab** [comment]
Excellent @joshm91! Thanks for confirming.

**Comment by Sarah-E-Greene** [comment]
A couple of weeks ago, I wondered if  it was the platform version, but didn't end up having time to check. 

I'll find some time to check next week and update this.

**Comment by dsapab** [comment]
Hello @SarahRiley ! Thanks for reaching out. 

Were you able to check this? Let me know if you need any other assistance for progressing.

Thanks!

**Comment by Sarah-E-Greene** [comment]
Hi @pablods90,

I tried this out last night, and it's failing due to a weird error:

```
aws_elastic_beanstalk_environment.foo[0]: Modifying... [id=e-cpayjgv37x]
Error: ConfigurationValidationException: Configuration validation exception: Unknown or duplicate parameter: ECSTaskDefinitionName
	status code: 400, request id: 1e17b710-a31c-4ec4-8551-6cba6fbe2056
```

We use terraform to spin up our beanstalk, so this is our amazon linux 1 beanstalk config, with the following changes:

```
solution_stack_name    = "64bit Amazon Linux 2 v3.2.3 running Docker"

setting {
     namespace = "aws:autoscaling:launchconfiguration"
     name      = "ImageId"
     value     =  <new amazon linux 2 ami>
}
```

There's no other references to this error on google (which is rather surprising!) so i'm rather lost at this point.  There's no relevant references to 'ecs' or 'task' in our terraform.  The old amazon linux 1 platform gets past this validation (and fails later), so i suspect it's something to do with the solution stack, but i'm not sure what's wrong.  There's no other version of the solutions stack of that type available that I can check with.  This is in us-east-1.

Thoughts?

**Comment by dsapab** [comment]
Hello @SarahRiley,

Thanks for reaching out.

**ECSTaskDefinitionName** does not apply to Amazon Linux 2 platforms, as this new generation platforms do not rely on ECS anymore for running the Docker containers.

Based one snippet, seems that an **existing** environment is being modified. Is this the case?

A few thoughts:
- For creating this new setup, a whole new environment must be created (as you are changing the solution stack). I am unsure how Terraform will exactly behave here, but my advice would be creating a new environment rather than updating an existing one. Can you try this approach?
- I can think about other parameter/setting or snippet included in the Terraform code that is setting a property not compatible with the new platform. Can you double check this?
- Setting the **ImageId** [parameter](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalinglaunchconfiguration) is not really necessary. Unless you are using your custom AMI, the advice is to let Beanstalk select the latest and proper AMI for the solution Stack. Unless you require to specify your own AMI, do not set this option and let Beanstalk pick the right one. Not related to the error, but it is worth mentioning.

I hope it helps!

**Comment by Sarah-E-Greene** [comment]
Yes, that’s correct, it was an existing environment.  At this point, we’re not going to be able to switch to Amazon Linux 2 with needing to completely switch out beanstalk environments, so will focus our attention elsewhere.

I think we’re fine to close this issue.
