### ISSUE TITLE
PHP on Amazon Linux 2 platform

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#13]
We're working on building out this and other platforms on top of Amazon Linux 2 (AL2). With our AL2 platforms, we are refreshing and rethinking each platform based on feedback we’ve gotten from customers. If you have any questions or suggestions for this platform, please add a comment in the issue.

**Comment by gmsantos** [comment]
Which proxy webserver will be used in PHP AL2 platform? Nginx or Apache?

**Comment by labisso** [comment]
@gmsantos We're planning to support only Nginx (with PHP-FPM) at launch. Will that be a problem for you?

**Comment by gmsantos** [comment]
No problem at all :)

**Comment by mxnr** [comment]
Hi @gmsantos!
Is there a timeline for this changes? Planning to update all app's from PHP 7.2 to PHP 7.3, but in case if you are planning to add 7.4 in the next few months - we will wait:) 
Thanks!

**Comment by gmsantos** [comment]
@mxnr I think you mean @labisso :)

**Comment by jim0thy** [comment]
What version of PHP will this launch with? PHP 7.4 would be ideal, but I'm guessing we need to wait for #5 first?

**Comment by labisso** [comment]
@jim0thy PHP 7.4 is now available in Amazon Linux 2, so we are expecting to include 7.4 support when we launch this beta (as well as 7.3). We're hard at work on this now!

**Comment by heathdutton** [comment]
That's awesome to hear @labisso! Is there a rough eta? Are we talking months or weeks? Can't wait to kick the tires.

**Comment by BobDankert** [comment]
I see the moved to public beta - where can we get more information on the new environment?

**Comment by rbran100** [comment]
@labisso Will you be adding support for Apache proxy server in AL2? Our applications rely currently on some dynamically generated rewrite rules that and some other functionality that will be more difficult to implement in nginx.

**Comment by Sekhar-Kutikuppala** [comment]
@rbran100 We are not currently planning on supporting Apache on AL2 based PHP platforms or the other AL2 platforms. I'm curious to know the difficulty in implementing your functionality requirements in Nginx. Can you tell us more about why it is difficult for you to use Nginx?

**Comment by mxnr** [comment]
PHP 7.4 available! Awesome, thank you guys <img width="828" alt="Снимок экрана 2020-04-14 в 20 17 04" src="https://user-images.githubusercontent.com/1383089/79254184-0655db80-7e8d-11ea-98dc-c91b0f241db2.png">

**Comment by rbran100** [comment]
@Sekhar-Kutikuppala It is really just that our application makes heavy use of rewrite rules in apache we have several 100 domains that need to each map to their own files subfolders for example:

```
  RewriteCond %{REQUEST_FILENAME} !-f                                                           
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} ^(.*?)\/files\/
  RewriteCond %{HTTP_HOST} ^static\.mit\.xxx\.com [OR]
  RewriteCond %{HTTP_HOST} ^staticmit\.xxx\.com
  RewriteRule ^(.*)$ /file/MIT/files/$1 [L]
```
Not exactly like that but a simple illustration, and that is added to/from regularly.  I think that that could be adapted to a nginx config and paired with a reload of the config.  But it will take a significant change to several components and we would need to audit/test to make sure nothing is missed.

So it really isn't that it is difficult (that we know of yet without audit) just that a significant effort would be required since we rely on directory level rewrites and htaccess files so much.  The rest (upload file sizes,  expires headers, cache-control headers, etc...) I am sure we can get running without much fuss.

**Comment by CTNCardoso** [comment]
I need help, how can I configure the configuration?

location / {
     try_files $ uri $ uri / /index.php?$query_string;
}

To use Laravel.

**Comment by CTNCardoso** [comment]
I need help, 

How do I set the configuration?

location / {
     try_files $ uri $ uri / /index.php?$query_string;
}

To use Laravel.

**Comment by Sekhar-Kutikuppala** [comment]
PHP on AL2 platform is now generally available
[Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-04-30-al2.html)
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/04/aws-elastic-beanstalk-announces-general-availability-of-amazon-linux-2-based-node-js-php-go-and-ruby-platforms/)

**Comment by McQgit** [comment]
@Sekhar-Kutikuppala  Since you don't have plans to support Apache on AL2, how long do you plan to support existing AL PHP platforms with it?  I just want to understand the timeline I have for migration / alternatives.  Thanks

**Comment by stuartbroad8** [comment]
**Apache** is still the leading web server. We have 100's of projects that depend on apache. Could anyone give any updates on its future status . thanks !

**Comment by swiffer** [comment]
Migrated already. In the end was easier than first thought but as most PHP users are used to Apache and configuring Rewrite Rules via .htaccess files a little more guidenance on where and how to set these in the new platform would be helpful.

I ended dumping the /etc/nginx/nginx.conf from a running instance, adding my neccessary rewrite in server section

```        
location / {
    try_files $uri $uri/ /index.php?$args;
}
```

and placed it in `.platform/nginx/nginx.conf`

**Comment by neerajklite** [comment]
Would be great if we can have apache support as well on AL2 :)

**Comment by Mosnar** [comment]
It doesn't look like Composer is included anymore (at least on the 7.4 project) and dependencies aren't automatically installed. Was that intentional?

**Comment by cristianocca** [comment]
I know this is for PHP, but python is most likely similar. Can someone give me a hint on how to migrate from apache to nginx? Placing files under .platform/nginx/conf.d or nginx.conf doesn't seem to work since we need to configure both location and server sections.

Here is what we are trying to achieve:

- static files path (django)
- add cache headers to static files
- http to https redirect if forwarded-for proto
- pass forwarded-for-proto header to the proxy
- Add security headers (X-Frame-Options, HSTS, etc..) to both static and proxied requests
- setup GZIP to both static and proxied requests
- tweak keep alive time
- disable server banners

Here's our "full overwrite" put on .platform/nginx/nginx.conf, but it doesn't work, and is probably not the best way to do it (we don't need a full overwrite, just an extension).

This doesn't work, but is close.
```
#Elastic Beanstalk Nginx Configuration File
# Taken from: conf.d

user                    nginx;
error_log               /var/log/nginx/error.log warn;
pid                     /var/run/nginx.pid;
worker_processes        auto;
worker_rlimit_nofile    200000;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    include       conf.d/*.conf;

    map $http_upgrade $connection_upgrade {
        default     "upgrade";
    }

    server {
        listen        80 default_server;
        access_log    /var/log/nginx/access.log main;

        client_header_timeout 60;
        client_body_timeout   60;
        
        server_tokens off;
        keepalive_timeout 120;
        
        # GZIP Config - add any missing here
        gzip on;
        gzip_types text/plain text/html text/css text/javascript text/json application/javascript application/xml application/json application/pdf application/x-font-ttf application/x-font-opentype;
        gzip_proxied any;
        
        
        # Security headers
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1;mode=block";
        
        
        # TODO: Redirect to HTTPS?
        if ($http_x_forwarded_proto = "http") {
            return 301 https://$host$request_uri;
        }
        
        
        # Static files - absolute or relative? root or alias?
        location /static/ {
            root static/;
            expires 7d;
        }
        
        # Python server
        # Taken from: conf.d/elasticbeanstalk/00_... something
        location / {
            proxy_pass          http://127.0.0.1:8000;
            proxy_http_version  1.1;
            
            #proxy_send_timeout 120s; 
            #proxy_read_timeout 120s; 

            proxy_set_header    Connection          $connection_upgrade;
            proxy_set_header    Upgrade             $http_upgrade;
            proxy_set_header    Host                $host;
            proxy_set_header    X-Real-IP           $remote_addr;
            proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto $scheme;
        }
      
        # Include the Elastic Beanstalk generated locations
        # include conf.d/elasticbeanstalk/*.conf;
    }
}
```

**Comment by Caoimhin89** [comment]
> I ended dumping the /etc/nginx/nginx.conf from a running instance, adding my neccessary rewrites in server section (fairly simple rule here)
> 
> ```
> location / {
>     try_files $uri $uri/ /index.php?$args;
> }
> ```
> 
> and placed it in `.platform/nginx/nginx.conf`

Hey, @swiffer! I didn't quite follow this. `.platform` is in your application repo or on the server? Did you insert `location / { try_files $uri $uri/ /index.php?$args; }` inside the server section of nginx.conf or as its own section?

Is this accurate:

`server {
        listen        80 default_server;
        access_log    /var/log/nginx/access.log main;
        location / {
             try_files $uri $uri/ /index.php?$args;
        }
        client_header_timeout 60;
        client_body_timeout   60;
        keepalive_timeout     60;
        gzip                  off;
        gzip_comp_level       4;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        # Include the Elastic Beanstalk generated locations
        include conf.d/elasticbeanstalk/*.conf;
    }`

**Comment by swiffer** [comment]
Hi @Caoimhin89 - .platform in my application repo. docs on how to extend the nginx config are available at https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html

I've tried to extend at first but failed to add my rewrite rules to the existing server block. thats why i opted to overwrite the complete file.

**Comment by Caoimhin89** [comment]
Hi @swiffer, thanks for the response. So how should the final nginx.conf file look? Did you remove any code or just add this?:

`location / {
    try_files $uri $uri/ /index.php?$args;
}`

**Comment by swiffer** [comment]
I've just added this into the server section. (used /etc/nginx/nginx.conf from a running instance as template).

**Comment by infernobass7** [comment]
@labisso How does AL2 handle environment variables? I set variables in the console exactly the same as I did with the original AL but it does not seem to be using these variables. The main issue that I am running into is trying to pull a private package with composer. On AL I was able to set COMPOSER_AUTH as an escaped string in the console and it would install correctly.

**Comment by ARH-Digital** [comment]
Will apache be available at all, or will we have to configure it to work alongside nginx?
I know this can be done, just a lot more work and I am sure there are a lot of people that will still be using apache.

**Comment by Sekhar-Kutikuppala** [comment]
Hi @ARH-Digital  We are working on adding Apache to the PHP on AL2 platform

**Comment by neerajklite** [comment]
Thank you @Sekhar-Kutikuppala and to the beanstalk team , this is wonderful :)

**Comment by nicolasmoreira** [comment]
Very nice job team!

**Comment by Jun711** [comment]
@Sekhar-Kutikuppala 
Hi, I updated my platform using my existing configuration and code that runs on `PHP 5.5 running on 64bit Amazon Linux` and also switched from Classic Load Balancer to Application Load Balancer to use HTTP2. 
Everything seems to work fine as I could load my webpages. However, gzip compression seemed to stop working

Amazon Linux 2 container options. 
![Screen Shot 2020-08-11 at 2 02 41 PM](https://user-images.githubusercontent.com/6880939/89948646-547cb080-dbdb-11ea-97d7-a8f8531fd145.png)

Could someone point me to the right direction? thanks

**Comment by Jun711** [comment]
Hi @cristianocca I wonder if you could share your nginx configuration extension that you used in the end and did you have any issue with gzip compression?

**Comment by cristianocca** [comment]
@Jun711 we are using Python, not PHP, so the nginx file is probably different. Either way, here it is

```
#Elastic Beanstalk Nginx Configuration File

user                    nginx;
error_log               /var/log/nginx/error.log warn;
pid                     /var/run/nginx.pid;
worker_processes        auto;
worker_rlimit_nofile    66485;

events {
    worker_connections  4096;
}

http {
    include	  /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request_method $uri" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    include	  conf.d/*.conf;

    map $http_upgrade $connection_upgrade {
        default     "upgrade";
    }

    # Some optimizations
    charset  utf-8;
    sendfile on;
    tcp_nopush  on;
    tcp_nodelay on;
    server_tokens off;
    log_not_found off;
    types_hash_max_size 2048;
    client_max_body_size 2048M;
    keepalive_timeout     120;
    client_header_timeout 10;
    client_body_timeout   10;
    send_timeout 10;

    upstream app_server {
        # fail_timeout=0 means we always retry an upstream even if it failed
        # to return a good HTTP response

        # for UNIX domain socket setups
        server unix:/var/app/current/gunicorn.sock fail_timeout=0;

        # for a TCP configuration
        # server 127.0.0.1:8000 fail_timeout=0;
    }


    server {
	    listen        80 default_server;
        access_log    /var/log/nginx/access.log main;


        # GZIP Config - add any missing here
        gzip on;
        gzip_comp_level 4;
        gzip_types text/plain text/xml text/css text/javascript text/json application/javascript application/xml application/json application/pdf application/x-font-ttf application/x-font-opentype font/woff2;
        gzip_proxied any;


        # Security headers
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload" always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1;mode=block" always;


        # Redirect to HTTPS
        if ($http_x_forwarded_proto = "http") {
            return 301 https://$host$request_uri;
        }

        location /static/ {
            autoindex on;
            alias /var/app/current/static/;
            expires 7d;
        }

        location / {
           
            proxy_http_version  1.1;
            proxy_cache_bypass   $http_upgrade;

            proxy_set_header    Connection          $connection_upgrade;
            proxy_set_header    Upgrade             $http_upgrade;
            proxy_set_header    Host                $host;
            proxy_set_header    X-Real-IP           $remote_addr;
            proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto   $http_x_forwarded_proto;

            proxy_redirect off;
            proxy_pass http://app_server;
        }
       	# Include the Elastic Beanstalk generated locations
        include conf.d/elasticbeanstalk/healthd.conf;
    }
}
```

**Comment by Jun711** [comment]
@cristianocca Thanks. I guess you are overriding the whole nginx configuration instead of extending it. Do you happen to know how to extend it as well?

We tried overriding it using the default nginx configuration and it seemed to work, at least my static files were gzipped. 

I tried with something like this and put it at `.platform/nginx/conf.d/gzip.conf` but gzip wasn't turned on. 
```
server {
  gzip on;
  gzip_comp_level 4;
  gzip_types text/html text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
}
```

**Comment by niphoenixo** [comment]
Hi there,

I am not able to remove index.php from url with Elastickbeanstak(Nginx) + Codeigniter  setup
Please help on this

My default controller works well, but for the rest of controller I need to add index.php manually into the url

Otherwise it is showing below error

**404 Not Found
nginx/1.18.0**


Below mention are the full details of my application

**Version**

PHP 7.4
Codeignter 3.10

**Deployment Setup**
AWS
ElasticBeanstalk
NGINX

**MY Application Setup**

.platform
  -nginx
     -conf.d
        -custom.conf
-Application
-Controller
-Views
-Model
...
...
..

**Custom Config** custom.conf

files:
  /etc/nginx/conf.d/proxy.conf:
    mode: "000644"
    owner: root
    group: root
    content: |
      server {
        server_name http://domain.tld/;

        root /var/www;
        index index.html index.php;

        # set expiration of assets to MAX for caching
        location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
                expires max;
                log_not_found off;
        }

        location / {
                # Check if a file or directory index file exists, else route it to index.php.
                try_files $uri $uri/ /index.php;
        }

        location ~* \.php$ {
                fastcgi_pass 127.0.0.1:9000;
                include fastcgi.conf;
        }
    }

**My config.php**

$config['base_url'] = "http://domain.tld/";
$config['index_page']       = "";
$config['uri_protocol']     = "REQUEST_URI";

**Comment by manu-sparheld** [comment]
@niphoenixo 
Instead of using files you can use `.platform` dir. and this problem comes from nginx config. you can find it here:
https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/

**Comment by tridoan** [comment]
> Hi @ARH-Digital We are working on adding Apache to the PHP on AL2 platform

Is there any update on this feature?

**Comment by githubRover** [comment]
@tridoan Apache has been available for some time.  I switched to nginx but in the beanstalk console, go to Configuration - Software.  There is an option for 'proxy server' to set either nginx or Apache.  I am running PHP 7.4 on AL2

**Comment by khushtypeapps** [comment]
> I need help,
> 
> How do I set the configuration?
> 
> location / {      try_files $uri $uri/ /index.php?$query_string; }
> 
> To use Laravel.

create a file in top root of project
.platform\nginx\conf.d\elasticbeanstalk\000_rewrite_path.conf
and paste the code " location / {      try_files $uri $uri/ /index.php?$query_string; }" in rewrite path
That it

**Comment by kowstech** [comment]
> This one save my days and ass
