### ISSUE TITLE
IMDSv2 Support for Multicontainer Docker Elastic Beanstalk platform

### ISSUE THREAD

**Issue by cabney927** [aws/elastic-beanstalk-roadmap#130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?

Can you please update the latest Multi-container Docker Elastic Beanstalk platform to support IMDSv2, so the less secure IMDSv1 can be disabled?

I first checked with aws-security@amazon.com, since this is related to a Security Hub finding.  They mentioned "AWS Security is unable to assist with architectural, account limit, or customer service issues.", so I'm posting this here.

When going through my AWS Security Hub findings, I found a “HIGH” severity issue titled “EC2.8 EC2 instances should use Instance Metadata Service Version 2 (IMDSv2)”. The EC2 instance it was referring to was created upon creation of my Elastic Beanstalk environment.
 
Upon additional research I found the following AWS documentation for how to disable the usage of IMDSv1 on Elastic Beanstalk, https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-ec2-imds.html . 
 
When attempting to disable IMDSv1 in the Elastic Beanstalk Configuration settings, I noticed the “Instance metadata service (IMDS)” section was not available.  Based on the following AWS documentation I found the following quote, “The IMDS section on this configuration page appears only for platform versions that support IMDSv2”, https://docs.amazonaws.cn/en_us/elasticbeanstalk/latest/dg/using-features.managing.ec2.html .

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?
The platform version I am using is “Multi-container Docker running on 64bit Amazon Linux/2.23.0”.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

I'm trying to satisfy the Security Hub requirements and use the latest secure versions of libraries within my Elastic Beanstalk clusters.  If this problem is not solved, I will either have to work with the less secure version or look at other platform options.
Ultimately I would like to add a small section such as the following to my cloudformation template to disable IMDSv1 and force IMDSv2 to be used.

```
- Namespace: aws:autoscaling:launchconfiguration
  OptionName: DisableIMDSv1
  Value: 'true'
```

**Are you currently working around this issue?**
How are you currently solving this problem?
Currently I'm using the less secure IMDSv1 version.

**Additional context**
Anything else we should know?

I'm using Cloudformation templates to build my Elastic Beanstalk clusters, but I've included an easy way to reproduce the issue below.

This can reproduced by doing the following:
1. Create a test Elastic Beanstalk application
2. Set the Platform to Docker, Platform branch to Multi-container Docker running on 64bit Amazon Linux, and Platform version to 2.23.0
3. Create Application using sample code
4. Once the application and environment have been created, select the "Configuration" option.
5. Click the "Edit" button in the "Instances" category.
6. Notice that there is no option to disable IMDSv1.

I did notice that the Docker platform has an option for Amazon Linux 2 while the Multi-container Docker platform only had an option for Amazon Linux.  I read somewhere that all Amazon Linux 2 platform versions support both IMDSv1 and IMDSv2.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by cabney927** [comment]
I'm planning to look into migrating to the Docker Amazon Linux 2 Platform to see if that meets my needs.
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker-multicontainer-migration.html

**Comment by cabney927** [comment]
Migrating to the Docker Amazon Linux 2 Platform and disabling IMDSv1 through our CloudFormation template resolved this issue.

**Comment by alexsanderp** [comment]
Any way to set the hop limit?
