### ISSUE TITLE
Replace SSD storage type gp2 with gp3 

### ISSUE THREAD

**Issue by eballetbaz** [aws/elastic-beanstalk-roadmap#133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Replace SSD storage type gp2 with gp3 

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
No

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Upgrade to new storage type to improve performances and reduce costs

**Are you currently working around this issue?**
No

**Additional context**
https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/

**Comment by vincentclee** [comment]
I tried to use Option `BlockDeviceMappings` with value `/dev/xvdcz=:8:true:gp3` and got the following error:

> ```Aws::ElasticBeanstalk::Errors::ConfigurationValidationException: Configuration validation exception: Invalid option value: '/dev/xvdcz=:8:true:gp3' (Namespace: 'aws:autoscaling:launchconfiguration', OptionName: 'BlockDeviceMappings'): Value does not satisfy regex: '((/dev/([sh]d[a-z]([1-9]?|1[0-5]?)|xvd[a-z]|xvd[bc][a-z])|xvd[a-z]|xvd[bc][a-z])=(none|ephemeral[0-9]+|(snap-[a-zA-Z0-9]+)?(:([0-9]+)?)?(:(true|false)?)?(:gp2|:standard|:st1|:sc1|:io1:[0-9]+)?))(,\s*(/dev/([sh]d[a-z]([1-9]?|1[0-5]?)|xvd[a-z]|xvd[bc][a-z])|xvd[a-z]|xvd[bc][a-z])=(none|ephemeral[0-9]+|(snap-[a-zA-Z0-9]+)?(:([0-9]+)?)?(:(true|false)?)?(:gp2|:standard|:st1|:sc1|:io1:[0-9]+)?))*' [<DeviceName>=<Volume>, <Volume> is one of 'none', 'ephemeral<NUMBER>', or '[<SnapshotId>]:[<VolumeSize>]:[DeleteOnTermination]:[<VolumeType>][:<IOPS> (only when VolumeType is io1)]'.]```

**Comment by Sekhar-Kutikuppala** [comment]
Hi @eballetbaz Thank you for the feedback. We are looking into this

**Comment by amsinha2** [comment]
Is there an update here, i am trying to do this also

**Comment by uronly14me** [comment]
Hi I am waiting for it too. Does anyone know about it?

**Comment by shatalov-boris** [comment]
I've just noticed the gp3 option in my environment settings. I've switched to it and it's working fine so far.

**Comment by 1tonyca** [comment]
The feature is now available

**Comment by raphamotta** [comment]
Hello. I did not find this option. Could you please tell me where can I find it?

**Comment by 1tonyca** [comment]
Include release note as a reference, https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-06-30-change-history.html

**Comment by hayd** [comment]
is there a reason that the min size is 10Gb rather than 8Gb (as with GP2).
This is a little bizarre, as this isn't a restriction on GP3 itself.
