### ISSUE TITLE
Request to support the Inf1 instance type

### ISSUE THREAD

**Issue by jeremyjpaws** [aws/elastic-beanstalk-roadmap#134]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Request for Elastic Beanstalk to support the Inf1 instance type https://aws.amazon.com/ec2/instance-types/inf1/

**Comment by pprahlad** [comment]
Hi @jeremyjpaws, Thank you for the feedback. We are looking into this

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-09-20-dynamic-instance-type.html
