### ISSUE TITLE
Add Support for Node.js 14x

### ISSUE THREAD

**Issue by camjc** [aws/elastic-beanstalk-roadmap#138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Please add support to the AWS AMI's for NodeJS 14.
Its been out since 2020-04-21
https://nodejs.org/en/about/releases/

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
NodeJS platforms (Likely just targeting the AmazonLinux2 since AL1 is on the way out)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Using modern nodejs version in production.

**Are you currently working around this issue?**
Investigating using docker platform as a workaround, this adds overhead though.

**Comment by eye1** [comment]
Any chance to speed up on this? Node v12 has been in maintenance for a while now and catching up is basically getting urgent at this point.

**Comment by gsogol** [comment]
+1

**Comment by mmejeras** [comment]
+1

**Comment by mmejeras** [comment]
Apologies for the weird question, but what does 'Coming Soon' in this board mean, in terms of timeline? A month from status change? 6 months?

**Comment by hsharif-rh** [comment]
To reiterate the previous comment, it would be handy to know an estimated timeline for this release? Cheers.

**Comment by carlosfaria94** [comment]
Amazon Linux 2 already comes with support for NodeJS 14 ([source](https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/)), since the Lambda support announcement for NodeJS 14.

What's holding back AWS EB from supporting it?

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-02-26-al2.html

**Comment by camjc** [comment]
Glad to see its supported now (thanks!), but would have been great to have a rough timeline, we literally just moved everything to 12 a fortnight ago, and could have saved some time and gone straight to 14. Is it possible to provide rough timelines for future upgrades?
