### ISSUE TITLE
Allow deployment on OS-X ec2 instances

### ISSUE THREAD

**Issue by fhk** [aws/elastic-beanstalk-roadmap#143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

It would be great to have the ability to build OS-X server apps using elastic beanstalk.

For example I want to build a app that uses [Vision](https://developer.apple.com/documentation/vision)

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

Yes [here](https://aws.amazon.com/ec2/instance-types/mac/)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Currently its not possible and there aren't any good solutions to easily deploy my application.

**Are you currently working around this issue?**

Yes, I plan to virtualize OS-X...

**Comment by fhk** [comment]
Just wanted to check in to see if there are any updates?

**Comment by 1tonyca** [comment]
We don't have any use cases support this, for now, closing this. If this is still required, please do share some context on cloud workloads running on OS-X.

**Comment by fhk** [comment]
@1tonyca the main goal here is to have a web server that uses OS-X in combination with a server framework like Flask.

This would enable developers to utilize OS-X via API.
