### ISSUE TITLE
Automatically make .platform scripts executable

### ISSUE THREAD

**Issue by jeremyjpaws** [aws/elastic-beanstalk-roadmap#146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
I'd like scripts deployed under .platform/ to have executable permissions by default

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, it is expected to have to configure executable permissions while locally preparing files. This is fine on a ZIP deployment, but is harder on a JAR deployment as JARs cannot save file permissions. It is also frustrating to have a deployment failure, after just forgetting to do chmod +x on files before deployment. Since it is known these files need to be executable, it would be nice if Elastic Beanstalk did this automatically.

**Workarounds**

For JAR deployments, you can ZIP the JAR with .platform/ and a procfile to keep file permissions as ZIP archives support file permissions but JARs do not.

**Comment by manu-sparheld** [comment]
It would be nice to have it all Environments.  We use PHP and Node environments.

**Comment by manu-sparheld** [comment]
It would be nice to have it all Environments.  We use PHP and Node environments.

**Comment by dgagnon-simpleset** [comment]
Example work around:  https://gist.githubusercontent.com/mjescandell/fc3fab70087a7c6d80636e3e6fce9180/raw/e0b208f2930fdab24be7f165c140f072b308ba2e/02_grant_executable_rights.config

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html

For all Amazon Linux 2 based platforms versions that were released on or after April 29, 2022, Elastic Beanstalk automatically grants execute permissions to all of the platform hook scripts. In this case you don't have to manually grant execute permissions. For a list of these platform versions, refer to the [April 29, 2022 - Linux platform ](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-04-29-linux.html#release-2022-04-29-linux.platforms)release notes in the AWS Elastic Beanstalk Release Notes Guide.
