### ISSUE TITLE
[Customer Feedback Wanted] Decoupling Database from Beanstalk Environment

### ISSUE THREAD

**Issue by jonathanwang415** [aws/elastic-beanstalk-roadmap#147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Hi Elastic Beanstalk team here! We've heard about your grievances about how closely coupled databases are to the lifecycle of your Beanstalk environment. We are excited to announce that we are working towards giving customers a way to **decouple their database from running environments** as well as **retaining their database during environment termination**.

We wanted your feedback on the decoupling from running environments, specifically:
- Would you benefit from a "soft decoupling" where your beanstalk environment would still be able to connect to the database after decoupling? In other words, we could leave the RDS SG ingress rule intact as well as the environment variables after removing your RDS database/security group from the environment CFN stack. This would allow you to retain connection to your DB, but this will lead to more stack termination failures if customers do not clean up their ingress rules before attempting to delete their environment.
- **Note:** We are currently leaning towards **not** providing a soft decoupling option to prevent customers from experiencing more stack termination failures.

Let us know what you think and if you would like to see any changes to our proposed changes below!

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?** If so, which one(s)?
N/A

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

1. RDS database retention from terminated environments
- Add a Retain to [DBDeletionPolicy](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-rdsdbinstance)
- Policy will be applied
 
2. RDS database decoupling from running environments
- Customer should be able to decouple their RDS database from a running environment.
- Upon decoupling, the database will either be retained, snapshotted, or deleted, depending on the option setting for [DBDeletionPolicy](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-rdsdbinstance)
- If Retain is set, customer's RDS database and security group will be retained, but the ingress rule will be deleted, thereby terminating connection from the environment instances to the RDS database. Environment variables and DBPassword option setting will be removed as well for security.

3. Default value for DBDeletionPolicy will be changed from Delete to Snapshot
- This is so we can be in accordance with CFN's default value for RDS instance DeletionPolicy: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html#aws-attribute-deletionpolicy-options
- Safer for customers who might unexpectedly delete their database during environment termination.
- Snapshots should not increase the costs for customers

**Are you currently working around this issue?**
How are you currently solving this problem?
Customers are either accepting the tightly coupled architecture or using their own external RDS database: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/rds-external-defaultvpc.html

**Additional context**
Anything else we should know?

N/A

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by dragonsahead** [comment]
You should also be aware that the coupled RDS that Elastic Beanstalk deploys have magnetic disks instead of the production grade provisioned IOPS SSD's, so if you move ahead and make the decoupling, please take into account something for customers to change the disks or a reminder of this somewhere

**Comment by jonathanwang415** [comment]
We are aware that some customer databases may still be running on magnetic disk storage for backward compatibility, and we will update the documentation to provide a reminder to customers attempting to reuse a Beanstalk managed database. Thank you!

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-10-06-db-decoupling.html
