### ISSUE TITLE
Pipenv is missing on Python 3.8 AL2 version 3.2.0

### ISSUE THREAD

**Issue by spawn-guy** [aws/elastic-beanstalk-roadmap#157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

`Pipenv` is awesome. but it is missing from `Python 3.8 AL2 version 3.2.0` of elastic beanstalk.
even though it is mentioned as _the_ [Package Manager](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-python.html)

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

- `Python 3.8 AL2 version 3.2.0`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

`Python 3.7 AL2 version 3.2.0` has `Pipenv` and it works like a charm. But after trying to upgrade to `python 3.8` deployment started to fail.

**Are you currently working around this issue?**

we are still running on `3.7`. but we would like to see this bug fixed asap.

i don't want to maintain different requirements for `3.7` that are included in core of `3.8` (not to say the current python is `3.9`)

example from our `Pipfile`
```
[packages]
...
importlib-metadata = { version = "*", markers = "python_version < '3.8'" }
zipp = { version = "*", markers = "python_version < '3.8'" }
...
```

**Additional context**

Please bring back `Pipenv`

**Attachments**

from /var/log/eb-engine.log
```
2021/03/18 14:43:19.571493 [INFO] Running command /bin/sh -c python3 -m pipenv install --ignore-pipfile
--
2021/03/18 14:43:19.589862 [INFO] Installing dependencies with Pipfile
2021/03/18 14:43:19.589878 [INFO] Running command /bin/sh -c python3 -m pipenv install --skip-lock
2021/03/18 14:43:19.607578 [ERROR] An error occurred during execution of command [app-deploy] - [InstallDependency]. Stop running the command. Error: fail to install dependencies with Pipfile file with error Command /bin/sh -c python3 -m pipenv install --skip-lock failed with error exit status 1. Stderr:/bin/python3: No module named pipenv
2021/03/18 14:43:19.607590 [INFO] Executing cleanup logic
2021/03/18 14:43:19.607658 [INFO] CommandService Response: {     "status": "FAILURE",     "api_version": "1.0",     "results": [         {             "status": "FAILURE",             "msg": "Engine execution has encountered an error.",             "returncode": 1,             "events": [                 {                     "msg": "Instance deployment failed to install application dependencies. The deployment failed.",                     "timestamp": 1616078599,                     "severity": "ERROR"                 },                 {                     "msg": "Instance deployment failed. For details, see 'eb-engine.log'.",                     "timestamp": 1616078599,                     "severity": "ERROR"                 }             ]         }     ] }

```

from bash console
```
[root@ip-hidden ~]# which pipenv
/usr/bin/which: no pipenv in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
[root@ip-hidden ~]# which python3
/bin/python3
[root@ip-hidden ~]# cd /var/app/staging/
[root@ip-hidden staging]# ls
app  Pipfile  Pipfile.lock  Procfile  README.md
[root@ip-hidden staging]# python3 -m pipenv install --skip-lock
/bin/python3: No module named pipenv
[root@ip-hidden staging]# python3 -m pipenv install --ignore-pipfile
/bin/python3: No module named pipenv
```

**Comment by wngam** [comment]
Hi @spawn-guy , I'm checking the `64bit Amazon Linux 2 v3.2.0 running Python 3.8` platform, but I think `pipenv` is installed by default. Here is my console output when I logged in to the instance:

```
$ which pipenv
/usr/local/bin/pipenv

$ pipenv --version
pipenv, version 2020.8.13

$ which python3
/usr/bin/python3

$ python3 --version
Python 3.8.5
```

**Comment by spawn-guy** [comment]
@wngam valid point. Let's investigate further!

I'm in `eu-west-1` Region. I'll try to find the exact ami id later today (environment is already terminated to save money).

It could be a bad ami in my region.

However, I can confirm my experience repeated 3 times since the availability of 3.8. And I haven't seen any platform version updates.

Just to be sure: @wngam what user were you logged in as to verify your findings? `ec2-user` or `root`? I can not see it from the log you posted. Eb deployer runs commands from `root`

**Comment by davidbrai** [comment]
@spawn-guy for me this happened because I had `python-devel` in my yum packages. Once I removed it, pipenv seems to work fine

**Comment by spawn-guy** [comment]
> @spawn-guy for me this happened because I had `python-devel` in my yum packages. Once I removed it, pipenv seems to work fine

interesting, @davidbrai i do have `python3-devel` in yum packages. it is a way to install an openssl-enabled `pycurl`. i'll have a look at it, thanks

**Comment by davidbrai** [comment]
@spawn-guy please update if you figure it out as I may need to use python-devel in the future

**Comment by spawn-guy** [comment]
@davidbrai i just gave it another try. 

deployed current working `py37` code to `Python 3.8 running on 64bit Amazon Linux 2/3.2.2` along with existing `pycurl` rebuild and `python3-devel` dependency - and **IT WORKED!** 

i'll try to remove this `pycurl-openssl` rebuild tomorrow - let's see how it will behave.

but so far - so good! our app started, dependencies seem to be pulled. i like it 💯 

🥇 to the people who fixed this
