### ISSUE TITLE
How to import a project to eb cli?

### ISSUE THREAD

**Issue by evenstensberg** [aws/elastic-beanstalk-roadmap#158]
How can I import a project created in the UI to elastic beanstalk cli? `i.e eb import` instead of `init`

**Comment by rahulrajaram** [comment]
@evenstensberg

`eb init -i` will prompt you to select a region, application name, environment, etc. You could "import" a previously created application this way.

**Comment by rahulrajaram** [comment]
Closing this ticket since original question has been answered.
