### ISSUE TITLE
Worker tier sqsd strips whitespace multiple spaces

### ISSUE THREAD

**Issue by jdempster** [aws/elastic-beanstalk-roadmap#159]
I'm having an issue with the worker tier PHP Amazon Linux 2 (platform 3.1.6)
For some very strange reason, it's stripping multiple spaces.

I've tried to work out what the issue is, but with no luck. sqsd seems to be the culpret as if I read the data directly from sqs it's all there.

We've so far had to revert the migration in all the regions we're upgrading to the new platform.

The issue results in a fatal for PHP unserialize as it expects the exact number of characters, so striping characters breaks it.

**Comment by jdempster** [comment]
I've tested this in the recently released platform 3.2.0 and the issue still exists. Is anyone else having this issue? It makes using the workers useless for me.

**Comment by jdempster** [comment]
After much digging, I've found the issue. The ruby core SDK has been updated. The XML parser is incorrectly set up to strip whitespace. As a solution, I'm using a prebuild hook to patch the ruby file.

```
#!/bin/bash -eu

if [ -f "/.aws-sdk-core-xml-parser-engines-ox-fix-installed" ]; then
    exit 0
fi

sudo yum install -y patch
patch -u /opt/elasticbeanstalk/lib/ruby/lib/ruby/gems/2.6.0/gems/aws-sdk-core-2.11.546/lib/aws-sdk-core/xml/parser/engines/ox.rb -i .platform/files/aws-sdk-core-xml-parser-engines-ox.patch
touch /.aws-sdk-core-xml-parser-engines-ox-fix-installed
systemctl restart sqsd
```

```
--- ox.rb       2021-04-09 20:20:20.862069509 +0000
+++ ox-new.rb   2021-04-09 20:21:05.181225573 +0000
@@ -14,7 +14,7 @@
           Ox.sax_parse(
             @stack, StringIO.new(xml),
             :convert_special => true,
-            :skip => :skip_white
+            :skip => :skip_none
           )
         end
```

**Comment by is-alnilam** [comment]
We've seen the same issue (AL2 Ruby 2.7 platform). As we use a mix of signed XML and YAML, this breaks the daemon completely.

I ended up working around this by dropping in a completely custom SQS daemon, reading the standard config file and hooking into the startup scripts so that the healthchecks don't realise that 'the wrong' SQS daemon is running -- I already had code to do most of this, so it's not quite as crazy as it sounds. But it's definitely not ideal.

We'd be very keen to see this fixed as well!

**Comment by jdempster** [comment]
It would appear this is has been fixed. I'm currently using platform version 3.3.1 and the ruby library which has been packaged has been updated with a fix to the issue.

Bit disappointed AWS never responded to confirm the issue and inform regarding the fix. 

Either way glad it's resolved :)

**Comment by 1tonyca** [comment]
Thanks for catching the oversight
