### ISSUE TITLE
Ruby: Run 'checkforraketask' scripts also on configuration deployment

### ISSUE THREAD

**Issue by januszm** [aws/elastic-beanstalk-roadmap#176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

This:

```
[INFO] Running command /bin/su webapp -c bundle exec /opt/elasticbeanstalk/config/private/checkforraketask.rb assets:precompile
[INFO] Found assets:precompile task in Rakefile
[INFO] Running command /bin/su webapp -c bundle exec rake assets:precompile
...
[INFO] Running command /bin/su webapp -c bundle exec /opt/elasticbeanstalk/config/private/checkforraketask.rb db:migrate
[INFO] Found db:migrate task in Rakefile
[INFO] Running command /bin/su webapp -c bundle exec rake db:migrate
```

runs only on regular deployment, but it should also run on configuration deployment, basically whenever `/var/app/current` is replaced with the unpacked application bundle.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?
Ruby

**Are you currently working around this issue?**
Use dedicated shell script in `.platform/confighooks/predeploy/assets.sh` to run `rails assets:precompile`.

**Additional context**
Also may apply to Python platform and Django apps where I think a similar "checkfor..." task should be executed.

**Comment by gonzaloaune** [comment]
I'm having a similar issue where the `rake db:migrate` is not running even though I have `RAILS_SKIP_MIRATIONS` as `false`.

Here are the logs:

```
2021/08/10 14:16:50.446290 [INFO] Running command /bin/su webapp -c bundle exec /opt/elasticbeanstalk/config/private/checkforraketask.rb db:migrate
2021/08/10 14:16:51.040758 [INFO] No db:migrate task in Rakefile, skipping db:migrate.
```

If I deploy the same codebase to AmazonLinux 1, I get this:

```
  + su -s /bin/bash -c 'bundle exec /opt/elasticbeanstalk/support/scripts/check-for-rake-task.rb db:migrate' webapp
  Couldn't find the MJML 4. binary.. have you run $ npm install mjml?
  + '[' false = true ']'
  + su -s /bin/bash -c 'leader_only bundle exec rake db:migrate' webapp
```

Hopefully this is helpful in case this is the same bug?

**Comment by januszm** [comment]
It seems that such a feature should also be available for the Python platform, where an important step for Django applications is installing Javascript packages and building a frontend. Something like this should be run during the deployment process and Configuration deployment:

```
yarn install && yarn build
python manage.py collectstatic --noinput
```

Currently, if someone wants to do build css and js in Django, they must do it, e.g. as a `postdeploy` hook. This, in turn, may cause a problem with the correct evaluation of the health check, i.e. before the frontend is finished building, some requests will end with errors (no js files, etc.) and stop the entire deployment.
