### ISSUE TITLE
Ruby 3

### ISSUE THREAD

**Issue by interpegasus** [aws/elastic-beanstalk-roadmap#179]
What do you want us to build?

Hi, Ruby 3.0 brings some performance, concurrency, and typing improvements among other advantages, and I would like to know if there are any plans to support it via AWS Beanstalk?

https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

Additional context

https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.ruby
**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?Tell us about your request

**Comment by 1tonyca** [comment]
@interpegasus , we are currently researching https://github.com/aws/elastic-beanstalk-roadmap/issues/166, if it's the same request, please close this one and track issues 166. Thanks!
