### ISSUE TITLE
Linux2 platform difficult to upgrade NodeJS version

### ISSUE THREAD

**Issue by yueileen** [aws/elastic-beanstalk-roadmap#186]
The problem is that on the new linux2 platform, upgrading NodeJS versions is difficult/manual. In the older linux platform, we can upgrade the node version for the EB in the following way:

1: creating a new beanstalk environment by performing cloning operation OR
2: creating a new beanstalk environment using saved configuration 

On linux2 platform, both methods do not allow you to choose a different (higher) node version. Currently, the only way to perform a NodeJS version upgrade is to create a new environment, manually set the configs (network, vpc, load balancer, deployment etc) and then perform a blue-green deployment. 

This is very inefficient and error-prone to do manually, given that we have many services and applications on beanstalk. 

Can you please address this as soon as possible? Thank you.

**Comment by dgagnon** [comment]
You can already update nodejs version in-place:
aws elasticbeanstalk update-environment --environment-name [env_name] --solution-stack-name "64bit Amazon Linux 2 v[version] running Node.js 14"

**Comment by yueileen** [comment]
Thanks very much. I was looking to do this via the AWS console but didn't find one. I'll use the CLI instead.
