### ISSUE TITLE
Static asset routing mismatch for ruby platforms

### ISSUE THREAD

**Issue by owensj-basis** [aws/elastic-beanstalk-roadmap#187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?
Change the default nginx conf for ruby platforms to route static assets from the domain root. 

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?
Yes, Ruby

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

On an EB instance running a rails app with the default nginx configs, static assets (in the `public/` directory) get served from `my-app.com/public`, but ruby serves them locally from the domain root. It's been a known issue for [six years](https://forums.aws.amazon.com/thread.jspa?threadID=150904&start=25&tstart=0), and the publicly accepted workarounds (using ebextensions) don't seem to be working since the [platform update last april](https://aws.amazon.com/blogs/compute/introducing-a-new-generation-of-aws-elastic-beanstalk-platforms/).

**Are you currently working around this issue?**
How are you currently solving this problem?

When I try to use a override the default conf (`.platform/nginx/nginx.conf`), I get `Stderr:nginx: [emerg] duplicate location "/" in /var/proxy/staging/nginx/conf.d/elasticbeanstalk/webapp.conf:3`. According to [this issue](https://stackoverflow.com/questions/64455581/duplicate-location-nginx-error-backend-and-frontend), this error is due to the default conf not getting overridden, and I haven't been able to figure out how to remedy this. 

When I try to extend the default conf (`.platform/nginx/conf.d/proxy.conf`), I get `Stderr:nginx: [emerg] "server" directive is not allowed here`.

**Comment by januszm** [comment]
I just had to add the following file:

```nginx
# .platform/nginx/conf.d/elasticbeanstalk/packs_and_stuff.conf

location /packs {
  alias /var/app/current/public/packs;
  gzip_static on;
  gzip on;
  expires max;
  add_header Cache-Control public;
}

# other locations config goes here
```

And all assets work fine with default nginx config and Rails application. But I agree that such configurations should be already available in the platform, without workarounds.

**Comment by zzzhu0192** [comment]
Hi,

Thanks for reaching out to us! 

* for override default nginx issue, could you check whether your `nginx.conf` contains this line ` include conf.d/elasticbeanstalk/*.conf;` ? Beanstalk provided conf file are put under this directory. If you do not want any Beanstalk provided conf file, please do not add this line in `nginx.conf`.
* for extend default nginx issue, could you check whether your `proxy.conf` is valid inside [server block](http://nginx.org/en/docs/http/ngx_http_core_module.html#server) ? 
```
http {
    server {
        # Include the Elastic Beanstalk generated locations
        include conf.d/elasticbeanstalk/*.conf;
    }
}
```

Thanks

**Comment by 1tonyca** [comment]
Thanks for your feedback and patience. We have updated our nginx configuration on AL2 Ruby platform and shipped it as part of Oct Release (Ruby AL2 platform version 3.3.7). On platform 3.3.7, static assets (in the public/ directory) are served both from my-app.com/public and the domain root.
