### ISSUE TITLE
AL2 Ruby platform is too picky about Puma version and .ruby-version

### ISSUE THREAD

**Issue by januszm** [aws/elastic-beanstalk-roadmap#188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

The AL2 platform requires the use of a specific version of the Puma server and its dependencies, such as `nio4r`. It will break the system with hard to track error if versions required by the application don't match those on the server. See: https://stackoverflow.com/questions/59861277/puma-stuck-with-message-early-termination-of-worker-on-rails-6-api-only-projec

This means that if we want to use the puma server also for local development (which is completely OK), it is necessary to set the version to the same as the used AL2 platform. This is obviously a problem, because you have to keep track of what version is currently in use in AWS EB Ruby AL2 stack and the problem may be greater if the version changes in the new platform release. Actually, the safest thing to do is remove puma from Gemfile, as well as it is better to remove the .ruby-version file from the repository (see: https://github.com/aws/elastic-beanstalk-roadmap/issues/166#issuecomment-860137386) . This is completely against good web application development practice for the Rails framework.

This should be changed to either work like the old AL1 platform where both .ruby-version and puma version specified by the application code were ignored and whatever was on the server was used. Or, even better,  the platform should allow you to use the same minor Puma version and the minor/patchlevel Ruby version as found in Gemfile and .ruby-version files. So if the server has Ruby 2.7.4 and Puma 5.3.2 and in the application we have .ruby-version 2.7.3 and Puma 5.4.0, it should just work.

**Are you currently working around this issue?**
Remove `puma` from Gemfile or make sure version specified in Gemfile.lock matches the version on the server.  Add `.ruby-version` to .gitignore to make sure it is not deployed. Both workarounds are bad in long term.

**Comment by justin-robinson** [comment]
This and start logging the puma error messages somewhere. Debugging this from scratch was a nightmare.

**Comment by januszm** [comment]
Example, attempt to upgrade from platform version 3.3.1 (Ruby 2.7.3) to 3.3.4 (Ruby 2.7.4)

```
[INFO] Running command /bin/sh -c bundle config set --local deployment true
[ERROR] An error occurred during execution of command [self-startup] - [stage ruby application].
  Stop running the command. Error: install dependencies in Gemfile failed with error
  Command /bin/sh -c bundle config set --local deployment true failed with error exit status 1.
  Stderr:rbenv: version `2.7.3' is not installed (set by /var/app/staging/.ruby-version)
```

The application has Ruby version set to 2.7.3 in the `.ruby-version` file.
An attempt to upgrade the platform using the UI will fail, because currently, the code change to `.ruby-version` and platform upgrade is required in the same procedure.

**Comment by januszm** [comment]
Also Puma dependencies cause a number of problems with deployments, i.e. if we are on platform 3.3.4 and we have Puma 5.3.2, with nio4r 2.5.7 dependency and the application has been updated to nio4r 2.5.8, the deployment will fail. Puma will not start on the server due to the conflict of nio4r (2.5.7 vs 2.5.8). This is another example that the entire setup related to Ruby version and Puma version (including dependencies) should be fixed. At the moment it is practically impossible to upgrade the platform, e.g. from 3.3.4 (Puma 5.3 from nio4r 2.5.7) to 3.3.5 (Puma 5.4, nio4r 2.5.8) without downtime.

**Comment by januszm** [comment]
It looks like the only way to upgrade minor platform version without cloning the whole environment (blue-green) is to turn off health checks and Rolling based on health, if used, and then first change the platform and then deploy the updated Gemfile.lock.
How it really should work - probably either that the Puma version on the server does not conflict with the one in the Gemfile.lock file, or if, Puma and its dependencies are in Gemfile.lock, then this version is used, not some of the server.

**Comment by zzzhu0192** [comment]
Hi,

Thanks for contacting us!

* For puma server version, we will install the latest puma version for AL2 ruby platform. If you want to lock the puma version, please do **not** use the preinstalled puma. Instead, put puma inside Gemfile and provide a Procfile to use whatever puma version you desire. 
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ruby-platform-procfile.html

* For `.ruby-version` file, we do not have any special logic to handle it. If your application has a `.ruby-version` that points to a specific version(2.7.3 in this case), I would assume you want this specific version(2.7.3). Updating to a platform that has 2.7.4 installed would fail. If you do not care about patch version, then you should probably remove `.ruby-version` file before deploying to Beanstalk. If this does not make any sense, can you provide more insights on your local development flow? 

* For puma dependencies, are you using the preinstalled puma ? Can you put Gemfile/Gemfile.lock/Procfile here ? One before deployment with nio4r 2.5.7 and one after deployment with nio4r 2.5.8.

* Can you elaborate on how it is impossible to upgrade platform version from 3.3.4 to 3.3.5 ? Are you using the preinstalled puma ? Can you put your Gemfile, Gemfile.lock and Procfile here ?

**Comment by januszm** [comment]
Hi @zzzhu0192 , I appreciate you taking the time on this. I would like to clarify that the workarounds you described are probably well known to most readers, but are not the true solution to the issue mentioned here.

The `.ruby-version` is used in the very popular Ruby development workflow, where the file is checked into a Git repository and made available to the engineering team. When the team decides to upgrade to a newer version of the app, the change to that file is committed. Then the appropriate change is made in the test and live environments. Previously, this was possible with AL1 because AL1 ignored this file and forced the server version to be used. This was OK because after changing the code, it was possible to send it to the server and only then do the platform upgrade. Currently, it is not possible, the server will return an error about version conflict and abort deployment. This is why you cannot upgrade if you have a `.ruby-version` file in the repository.
Hope this clears up some of the questions above. The only workaround is to remove the `.ruby-version` file from the Git repository, but this is generally a bad thing.

As for the Puma server, the situation is similar, every new Rails application has the 'puma' gem listed in Gemfile. When you change the Puma version on the server, deployment is not possible due to a version conflict. Again - deleting the Puma entry from Gemfile is by no means a good solution, developers need a Puma entry in the Gemfile to work locally. If this is your intention, please write it clearly in the documentation that currently to use the Ruby Elastic Beanstalk platform updates you need to delete the `.ruby-version` file and:
a) either remove Puma from Gemfile
b) or leave Puma in Gemfile but also use a Procfile

All in all, I think you should either restore the behavior from the AL1 platform, that is, the Ruby and Puma versions of Gemfile are ignored and the system versions will be used, no conflicts. Or, introduce support for running ANY recent version of Ruby and Puma on the server via `rbenv` with `ruby-build` plugin, or precompiled versions of Ruby (e.g. last couple of versions) as specified in the project in ruby-version and Gemfile.lock

**Comment by nickgal** [comment]
Using the [.ebignore](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-configuration.html#eb-cli3-ebignore) file might be a potential workaround for the `.ruby-version` file for anyone using the EB cli.

**Comment by januszm** [comment]
Not sure if `.ebignore` would help or cause more problems because:

> If .ebignore is present, the EB CLI doesn't read .gitignore

I'd happily use it if it worked "together" with `.gitignore`

**Comment by zzzhu0192** [comment]
Hi @januszm,

Thanks for the detailed explanation!

For the `.ruby-version` file, after engineer updated this file and deployed the new code to running env, update env would fail due to version conflict. i.e. running env contains ruby 2.7.7 but `.ruby-version` points to 2.7.8. You would like to ignore the `.ruby-version` file as in AL1. If we release a new feature that supports installing any ruby version on instance as long as it has the same minor version as platform branch, would you prefer this way or simply ignore the `.ruby-version` file ?

For the puma version, we will update our documentation to be more clear that if cx has puma in their Gemfile, a Procfile is required so that whatever puma version specified in Gemfile will be used. 

Thanks

**Comment by januszm** [comment]
> You would like to ignore the .ruby-version file as in AL1. If we release a new feature that supports installing any ruby version on instance as long as it has the same minor version as platform branch, would you prefer this way or simply ignore the .ruby-version file ?

This is not a question just for me, but it would be easiest to ignore `.ruby-version` as in AL1, this will solve the platform upgrade problem.

Ultimately, I think it is worth implementing support for different versions via ruby-build plugin to rbenv which you already use in EB AL2. This will solve another problem with the EB platform - delaying the release of support for new versions, be it Ruby or Python. In the Python platform, the situation is similar, it is enough to make `pyenv` available on the server and users will decide which minor version they want to install (via pyenv/pipenv).

**Comment by cbisnett** [comment]
I also got hit with this as I was upgrading Amazon Linux AMI to Amazon Linux 2 which meant that Ruby changed from 2.5 to 2.7. What's worse than this just failing was that because I had set our Elastic Beanstalk Deployment Policy set to "Rolling with additional batch" the deployment fails on the new hosts and then those get removed as "excess instances" and then the environment transitions to "Healthy". Identifying this is what was happening required me to quickly jump into a new instance and tail all the logs in `/var/log/`. This workflow needs some updating to make this less of an issue or more clear when it's happened.

**Comment by 1tonyca** [comment]
Thanks for your feedback and patience. We have updated ruby version configuration on AL2 Ruby platform and shipped it as part of Oct Release (Ruby AL2 platform version 3.3.7). On platform version 3.3.7, the platform ignores the local ruby version (specified in the .ruby-version file) and forces the server version to be used.

**Comment by januszm** [comment]
Great news @1tonyca , thank you!

**Comment by x9sim9** [comment]
Thanks all for your help here, elastic beanstalk in its current state is completely unusable for ruby unless you have read this discussion. Having puma not use the version in your project was causing very, very, very hard to diagnose issues and if I had not found this discussion after 3 days of banging my head against a wall I would still be stuck on this issue.

I do appreciate that AWS has a "special" way of doing things but they must realise that this is broken by default for anyone using elastic beanstalk at the minute and the barrier to solving this issues is so high that its just not feasible for most people.

**Comment by x9sim9** [comment]
Specifically what fixed my issue if it is not clear is making my gems match the exact version of puma that is being used on the server which i found by sshing into the box and doing puma -v and then setting my gem to match along with nio4r

for ruby 2.7 with platform version 3.4.2 updating your gem files to this will solve your issue
gem 'puma', '=5.6.1'
gem 'nio4r', '=2.5.8'

Alternative option is to create your own procfile as mentioned above in the comments

**Comment by gugaiz** [comment]
@1tonyca  I am trying to upgrade from 3.4.5 to 3.4.6 and I am having issues with the .`ruby-version` file that is set to `2.7.5` on my codebase. I thought you were ignoring `.ruby-version` since version 3.3.7, but does not seems to be the case.

**Comment by januszm** [comment]
The problem with `.ruby-version` is back, Ruby 3.0 platform was recently upgraded to 3.0.4 and projects with `3.0.3` in `.ruby-version` won't work.

**Comment by januszm** [comment]
@1tonyca  looks like a regression

Also, why EB still does not support Ruby 3.1 ?  It is stable and widely used in production environments.

**Comment by nickpearson** [comment]
In case anyone needs a workaround until this gets fixed, here's what I use:

`.platform/hooks/prebuild/01_clean.sh`

```bash
#!/bin/bash

# ignore the application's Ruby version
rm -f .ruby-version
```

**Comment by baiyli** [comment]
Hi @januszm @gugaiz ,

Thanks for contacting us.

For the issue related with `.ruby-version`, I tried to update an env of an old ruby platform version(3.4.4) with old ruby version in the `.ruby-version` file to the latest ruby platform(3.4.6) in both 2.7 and 3.0 branches successfully. In order to reproduce this issue, could you provide more information?
For example:
- Error logs
- Ruby platform versions (update from 0.0.0 to 0.0.1 )
- When did you first notice this problem?
- ... Anything else might be helpful

Thanks.

**Comment by januszm** [comment]
@baiyli  it looks like this issue only happens when there's a misimatch between `.ruby-version` (e.g. `3.0.3`) and the version installed on the server (e.g. `3.0.4`). Fortunately, it does not affect deployments and running the server, it is a bit of a problem when you have cron jobs or need to SSH to the server to run the console or scripts (e.g. for debugging purposes).

I think @nickpearson 's workaround seems like a good longer term solution, at least until you decide to make major changes, such as allowing the developer to decide which Ruby version will be used on the server via Gemfile or `.ruby-version` files. In fact, the latter option would also solve significant problems with delay in providing support for new Ruby versions. Example, we've been waiting a long time for Ruby 3.1 to become available (and still waiting). If rvm or rbenv were running on the server with pre-compiled up-to-date Ruby versions (2.7, 3.0, 3.1), developers could easily select a version without having to change the solution stack.

**Comment by baiyli** [comment]
Hi @januszm ,

Thanks for your detailed reply.

Just to confirm, this issue just happens when you run some commands after SSH to the instance instead of app deployment or updating ruby env/platform to a new ruby platform version, right? 

I can reproduce this issue when I try to run the console on the instance. This problem is indeed caused by `.ruby-version`. In addition to the @nickpearson's workaround, I think exporting an environment variable for `RBENV_VERSION` to override the local ruby version can work as well. For example, `RBENV_VERSION=3.0.4 bundle exec rails c`. Meanwhile, we'll have a discussion on how to solve this issue better for customers.

Thanks.

**Comment by nabilfreeman** [comment]
I have had to debug impossible Puma issues 3 times already this year, and if it happens again I will leave Elastic Beanstalk forever.

(and thank you to people providing info in this thread, it has helped a lot today)

**Comment by nabilfreeman** [comment]
@x9sim9 yes this is the fix, but good luck next time EB team decides to upgrade Puma to 5.7 without telling you. Your app will be FUBAR without any warning.

**Comment by x9sim9** [comment]
> @x9sim9 yes this is the fix, but good luck next time EB team decides to upgrade Puma to 5.7 without telling you. Your app will be FUBAR without any warning.

Yeah I was worried about this happening and ended up using a procfile so that the Puma version defined in Gemfile is always used, instead of the system version.

Why amazon does not see this as a huge problem I have no idea, without this thread I would have never figured out the issue and been forced to migrate away from AWS. Not everyone will be so lucky.

**Comment by x9sim9** [comment]
If anyone needs it here is the contents of my procfile to ensure the correct ruby version is used from the Gemfile

`web: bundle exec puma -C /opt/elasticbeanstalk/config/private/pumaconf.rb`

**Comment by baiyli** [comment]
Hey @nabilfreeman @x9sim9 

Thanks for @x9sim9's workaround.

We have documents for tracking ruby or dependencies' versions and handling puma version conflict issues.
- Ruby or dependencies version for all Beanstalk Ruby AL2 platforms: https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-ruby.html
- Fix puma version conflict issue: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ruby-platform-procfile.html

Hope these 2 documents are helpful for your concerns.

Thanks

**Comment by januszm** [comment]
It's happening again 

```
Unable to load application: Gem::LoadError:
  You have already activated puma 5.6.5, but your Gemfile requires puma 5.6.4
```

the most recent platform upgrade totally breaks apps without notice, without any indication on what went wrong

**Comment by baiyli** [comment]
Hey @januszm ,

Do you have a procfile in your source bundle and still get this error?

Thanks.

**Comment by januszm** [comment]
@baiyli  no, I do not use Procfile, I rely on the default platform settings.

**Comment by x9sim9** [comment]
You have to use a Procfile this is the only solution to this problem, but the file is very easy

Just create a file caled
Procfile 
In the main directory no file extension

And copy this inside and you are done, no other work required

`web: bundle exec puma -C /opt/elasticbeanstalk/config/private/pumaconf.rb`

**Comment by baiyli** [comment]
Thanks for the information. Currently, Beanstalk platform install the latest puma version by default so you have to include the procfile in your source bundle if you want to use other puma versions specified in you Gemfile. For more information, you can check this [document](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ruby-platform-procfile.html). Thanks.

**Comment by januszm** [comment]
@x9sim9  thanks I know how Procfile(s) work and how to set it up but since AWS EB documentation does not mention this as "obligatory" I epect it to work without Procfile. Ultimately I'll probably use this as a workaround.

@baiyli  I'd suggest to make it super clear in AWS docs that Procfile is required. Also to improve the developers' experience I'd recommend to build a mechanism that injects a default Procfile when EB detects that the app has `puma` in its Gemfile.

**Comment by januszm** [comment]
Also, this is not the only solution to this issue, another one is to move `puma` to group `development` of the project Gemfile.

```ruby
group :development do
  gem 'puma'
  # ...
end
```

**Comment by baiyli** [comment]
Thanks for your suggestion. Procfile is used across multiple platforms in Beanstalk service to specify custom commands to start and run your application currently so this way is recommended for developers to fix puma version conflict in the official document of ruby platform. We will try to make the document clearer for this issue.

**Comment by nabilfreeman** [comment]
Thanks @baiyli, I hope you do improve the documentation and environment, as this is direct feedback from AWS customers that the Ruby on EB experience is not intuitive and is resulting in production applications going live with guaranteed instability in the future.

We appreciate your hard work and for being here on GitHub to listen!

**Comment by januszm** [comment]
While we have you here @baiyli , how is adding Ruby 3.1 going ? EB uses rbenv which makes Ruby installation very easy, Ruby 3.1 has been around for so long that there is no justification for withholding it. Adding Ruby 3.1 seems like a quick task that could be accomplished in a few days even with a relatively complicated platform. Could you share some more information on what is blocking Ruby 3.1 in Elastic Beanstalk?

**Comment by baiyli** [comment]
Hey @nabilfreeman , thanks for your feedback. We are actively working on updating ruby document to make document clearer now. Will update this thread when we release updated ruby documents.

Hey @januszm , thanks for your feedback. `Support for Ruby 3.1` is on our radar and we will update the roadmap category as soon as we have more updates

Thanks.

**Comment by justin-robinson** [comment]
Knowing the pains of EB, I opted to build a fargate stack in cdk. Took about a week but now my ruby and puma deps are version controlled and in docker.

**Comment by xrnm** [comment]
We're going to be dumping EB over this. They've completed ruined the robustness and quality of about 25 of our deployed sites with this version non-sense. We have no control over what underlying version is being used and code that deployed yesterday won't deploy today because of what they're doing with EB.

Moving about 20 sites to ECS and Docker.

**Comment by xrnm** [comment]
Folks who aren't making the switch from EB might benefit from trying a custom AMI approach. We weighed this option and decided to move to ECS instead.

**Comment by gugaiz** [comment]
You can also use docker with EB if you don't want to switch to ECS

**Comment by januszm** [comment]
Suggestions above (in my humble opinion) defeat the purpose of using the platform. As soon as you switch to Docker or use a custom AMI, you are responsible for managing the system and security updates, and that was not the purpose of the Elastic Beanstalk platform. The idea was for the platform to be managed by AWS so developers could quickly deploy code with simple developer friendly commands, in short it was supposed to be (and for some years it WAS) **Heroku on AWS**.
So, as soon as you decide to use Docker images, custom AMI, you might as well switch to Kubernetes, EKS, ECS, Fargate, whatever, as it will require some extra sysadmin/devops work and extra deployment time.

**Comment by gugaiz** [comment]
I don't think we can compare the level of complexity of deploying an app on EB (using Docker) with deploying an app on ECS/EKS, but I understand your point and I agree that EB has lost its essence.

**Comment by x9sim9** [comment]
> Suggestions above (in my humble opinion) defeat the purpose of using the platform. As soon as you switch to Docker or use a custom AMI, you are responsible for managing the system and security updates, and that was not the purpose of the Elastic Beanstalk platform. The idea was for the platform to be managed by AWS so developers could quickly deploy code with simple developer friendly commands, in short it was supposed to be (and for some years it WAS) **Heroku on AWS**. So, as soon as you decide to use Docker images, custom AMI, you might as well switch to Kubernetes, EKS, ECS, Fargate, whatever, as it will require some extra sysadmin/devops work and extra deployment time.

I definitely agree that Elastic Beanstalk absolutely fails at its main purpose especially with ruby, the lack of documentation the forced update from AL1 to AL2, the issues with ruby versions, and so many many other devops issues I have had with elastic beanstalk. Months of development time dedicated to all the quirks of the elastic beanstalk platform. One of my personal worst experiences in almost 20 years of devops.

**Comment by xrnm** [comment]
This service used to be great and now I'm scrapping it for a service that does something slightly different because, with the introduction of these ruby/gem/version nightmares, the platform is necessarily unstable, fails to be robust, and fails to be easy thus removing any benefit it previously provided. If I have to manage all of my own patching and versioning anyway, might as well use something more portable and stable. I wish we hadn't just invested the time and energy moving to AL2 and had dumped the platform at that point.

I recommend that course of action for anyone currently considering an AL1 to AL2 migration.
