### ISSUE TITLE
Support the M6i Instance Types

### ISSUE THREAD

**Issue by matthewdouglas** [aws/elastic-beanstalk-roadmap#191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Requesting support to use the new [M6i instances](https://aws.amazon.com/ec2/instance-types/m6i/) in Elastic Beanstalk.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
All current supported platforms.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Would like to take advantage of the compute-price performance of M6i over M5.

**Are you currently working around this issue?**
Currently utilizing a mixture of T3, M5, and C5 instances.

**Comment by snnles** [comment]
Elastic Beanstalk now supports dynamic instance type selection, which means you will be able to use all the compatible instance types in a region and availability zone. For more information visit:

- [What's New post](https://aws.amazon.com/about-aws/whats-new/2021/09/aws-elastic-beanstalk-dynamic-instance-type-selection/)
- [Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-09-20-dynamic-instance-type.html)

**Comment by matthewdouglas** [comment]
@snnles Thank you! It would appear that this also resolves #89.
