### ISSUE TITLE
Graviton (Arm-based) instance type support rollout - wave 1

### ISSUE THREAD

**Issue by 1tonyca** [aws/elastic-beanstalk-roadmap#192]
Thank you for your patience and interest in Graviton instance type support in Elastic Beanstalk. We are happy to announce the gradual rollout for this support, beginning in early October. Customers who would like to adopt Graviton early will be able to create/update their environments in six regions via aws cli[1]. Please note that the late September release only includes aws cli support. Console and eb cli workflows will follow in subsequent rollouts. 

For this first wave of rollout, we are targeting in six regions (us-east-1, us-east-2, us-west-2, eu-west-1, eu-central-1, sa-east-1) for the following platform branches:

- Docker running on 64bit Amazon Linux 2
- Node.js 14 running on 64bit Amazon Linux 2
- Node.js 12 running on 64bit Amazon Linux 2
- Python 3.8 running on 64bit Amazon Linux 2
- Python 3.7 running on 64bit Amazon Linux 2
- Tomcat 8.5 with Corretto 11 running on 64bit Amazon Linux 2
- Tomcat 8.5 with Corretto 8 running on 64bit Amazon Linux 2
- PHP 8.0 running on 64bit Amazon Linux 2
- PHP 7.4 running on 64bit Amazon Linux 2
- Ruby 2.7 running on 64bit Amazon Linux 2

We look forward to share more details through upcoming release notes and developer guide to help customers to adopt this wave of rollout. Stay tuned!

[1]https://docs.aws.amazon.com/cli/latest/reference/elasticbeanstalk/index.html

**Comment by candrews** [comment]
When should expect CloudFormation support?

**Comment by jpike88** [comment]
@1tonyca Sad that ap-southeast-2 wasn't in the first wave :( do you have a schedule of how long each wave will be and which regions are included?

But great news!

**Comment by jmgunter** [comment]
Any update on a specific date for the roll out on this? Could you provide an example cli command for updating the elastic beanstalk instance to one of the new Graviton types?

**Comment by 1tonyca** [comment]
Thank you all for your patience. We are heads-down to wrap up wave 1 rollout, and we might be a few days behind. We are as eager as you are to get this release to you, so it won’t be too long before early October. 

For wave 1 rollout, we will provide Arm-based images, and you will need to use a provided image as a custom AMI for your Elastic Beanstalk environment by filling the <arm-based-image-id-provided-by-us> field in the below examples

Example of AWS CLI command to update the existing Elastic Beanstalk environment:

aws elasticbeanstalk update-environment \
--region <region> \
--environment-name <existing-environment-name> \
--solution-stack-name <arm-supported-solution-stack> \
--option-settings \
Namespace=aws:ec2:instances,OptionName=InstanceTypes,Value=<arm-based-instance-type> \
Namespace=aws:autoscaling:launchconfiguration,OptionName=ImageId,Value=<arm-based-image-id-provided-by-us>

Example of AWS CLI command to create a new Arm-based Elastic Beanstalk environment:

aws elasticbeanstalk create-environment \
--region <region> \
--application-name <application-name> \
--environment-name <new-environment-name> \
--solution-stack-name <arm-supported-solution-stack> \
--option-settings \
Namespace=aws:autoscaling:launchconfiguration,OptionName=IamInstanceProfile,Value=<instance-profile> \
Namespace=aws:ec2:instances,OptionName=InstanceTypes,Value=<arm-based-instance-type> \
Namespace=aws:autoscaling:launchconfiguration,OptionName=ImageId,Value=<arm-based-image-id-provided-by-us>

More details to come

**Comment by 1tonyca** [comment]
Thanks again for your patience and interest, and we are happy to announce wave 1 rollout is now completed [1]. Customers who would like to adopt Graviton early with this rollout, please follow the developer guide [2] to proceed.

We will keep this issue opened for two weeks, in case you have any questions or issues regarding this release.

We have already started working on the next gradual rollout - MVP, and it would include:

- Remaining platform branches on AL2 that weren’t included in Wave 1, ex .NET Core on linux and Corretto
- Widen regional support to all Graviton instance type supported regions [3]
- Basic console experience for Graviton instance type selection

We will share more details in a separate post with estimated timeline for MVP

[1] https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-10-13-graviton-wave1.html 
[2] https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.ec2.html#using-features.managing.ec2.instance-types
[3] https://aws.amazon.com/ec2/graviton/

**Comment by jpike88** [comment]
great news, eagerly awaiting availablity in ap-southeast-2, ap-northeast-1, and eu-west-2

Thanks

**Comment by 1tonyca** [comment]
Closing after two weeks
