### ISSUE TITLE
Upgrade NGINX to version 1.20.1 or higher - follow-up

### ISSUE THREAD

**Issue by sf-fernandovargas** [aws/elastic-beanstalk-roadmap#194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
update nginx package

**Is this request specific to an Elastic Beanstalk [platform]
not platform specific. affects all beanstalks

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Beanstalk has an old version of nginx and it is failing vulnerability scans. 

**Are you currently working around this issue?**
No workaround

**Additional context**
Upgrade NGINX to version 1.20.1 or higher <https://github.com/aws/elastic-beanstalk-roadmap/issues/180> closed issue that was not really resolved

**Attachments**
Upgrade NGINX to version 1.20.1 or higher <https://github.com/aws/elastic-beanstalk-roadmap/issues/180> closed issue that was not really resolved

**Comment by 1tonyca** [comment]
Thanks for re-opening this for our attention, as closed issues are not triaged.

Please refer to this link as reference, https://forums.aws.amazon.com/thread.jspa?messageID=990394

**Comment by sf-fernandovargas** [comment]
That reference is very helpful! Thanks for your quick reply!

fjv.

**Comment by DGeoWils** [comment]
Is nginx-1.20.0-2.amzn2.0.3 used across all platforms if we have updated to the latest version?

On the "PHP 7.4 running on 64bit Amazon Linux 2/3.3.5" platform, I get this output.

> nginx -v
   nginx version: nginx/1.20.0


Thank you!

**Comment by goodthang** [comment]
On the latest AMI for Elastic Beanstalk (Node) "Node.js 14 running on 64bit Amazon Linux 2/5.4.6"
> nginx -v
> nginx version: nginx/1.20.0

AMI ID: `ami-03982d1439cb6b7fb`
AMI Name: `aws-elasticbeanstalk-amzn-2.0.20210813.64bit-eb_nodejs14_amazon_linux_2-hvm-2021-10-02T03-44`

The AMI was built 2021-10-08, but `nginx` is still stuck with version 1.20.0.

If the issue is fixed, it's not available for Node.js environment.

**Comment by Lisenish** [comment]
@1tonyca Could you please confirm if this is actually resolved? 

This [documentation page](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.nodejs) also says that it's **1.20.0** still

And I reproduced it on the freshly created Node.JS ELB environment

**Comment by goodthang** [comment]
For those who stumbled on here looking for a work-around solution.  I ended up customizing the EB AMI to download and override the Node version used by the default AMI.  See [documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#linux-packages).

Specifically, add/edit `.ebextensions/option.config` (or a similar extension config file name) with the following:
```
packages:
  rpm:
    nginx: https://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.20.1-1.el7.ngx.x86_64.rpm
```

It's only temporary solution until the default EB AMI is truly fixed.  You lose the convenience of AMI + Node upgrade with this solution, so you should remember to switch back later.

For those looking to pass PCI compliance scan, you can use this solution or perhaps turning off the nginx version return in the header with nginx.conf.  However, that's just hiding the issue and not addressing it.
