### ISSUE TITLE
Allow platform hooks in Amazon Linux 2 - Docker build.

### ISSUE THREAD

**Issue by mathieujobin** [aws/elastic-beanstalk-roadmap#200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Ruby platforms and others allow to add scripts in `.platform/hooks/*` folder, this is very useful.
when we use Docker to deploy our application, we only send a Dockerrun.aws.json

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_v2config.html
https://gist.github.com/deanpeterson/2f323e67245d5f516f42
https://www.johnvincent.io/taskmuncher/docker/create-dockerrun/

Apparently, there isn't a way to add these hooks when using Beanstalk Docker platform.
Please add this ability

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

Docker AL2 version 3.4.7

**Comment by jpike88** [comment]
as a nodejs dev I think priority no 1 should be getting it out there with the interface intact so no black magic needs to be done via the cli. 

Surely this can be easily worked around using .ebextensions in the meantime, right?

**Comment by mathieujobin** [comment]
no @jpike88 .ebextensions can no longer be used. as far as I know, the new format is to place them in `.platform/hooks` but That's for non-docker platform. which is a huge limitation.

**Comment by jpike88** [comment]
Yikes good thing I found out now! Maybe it's time I migrated to the new hooks approach to be future proof.

**Comment by florianlh** [comment]
I don't really understand where you're getting that information that platform hooks don't work on the Docker platform, I don't see anything related to it in the links you provide in your issue.

From my experience platform hooks work for the Docker platforms, like any other Amazon Linux 2 platform, as documented on https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html

I use them in my application which is using  the AL2 multi-container (docker-compose) docker platform.

> when we use Docker to deploy our application, we only send a Dockerrun.aws.json

Well you don't have to send just your `Dockerrun.aws.json`, you can upload a deployment archive containing your container definition and other files like your `.ebextensions/` or `.platform/` configuration directories. The EB CLI for instance can help you do that easily.

**Comment by mathieujobin** [comment]
@florianlh I want to believe you, but I cannot find any documentation that would tell me how to instruct the `EB CLI` to add the .ebextensions in the package.

When I was using the ruby platform yes, it was making a zip of the whole project. so everything was included and files at those locations were automatically picked up.

That might be the case if I let Beanstalk build my Dockerfile, but that makes the deployment super slow.
And the fastest way to deploy on beanstalk is to do something like this.

```
$ cat .elasticbeanstalk/config.yml 
global:
  application_name: freehugs
  default_ec2_keyname: secret
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  workspace_type: Application
deploy:
  artifact: Dockerrun.aws.json
$ cat Dockerrun.aws.json
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/freehugs:202110181507210900",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": "80"
    }
  ]
}
```
Can I instruct it to include the `.platform` and/or the `.ebextensions` folder along? 
I sure want to know how

**Comment by mathieujobin** [comment]
So what I would want here, is be able to do 

```
$ cat Dockerrun.aws.json
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/freehugs:202110181507210900",
    "Update": "true"
  },
  "Hooks": [
       "filename"
   ],
  "Ports": [
    {
      "ContainerPort": "80"
    }
  ]
```

**Comment by gndk** [comment]
@mathieujobin You can already do this. Docker platform supports it fine.

I started with this as a base for my deployment script: https://github.com/imperfectproduce/aws-docker-deploy/blob/master/deploy.sh

Added some more stuff to it, like the `.platform` folder. I use single container environment with a prebuilt image thats hosted in ECR.

My deployment package is a ZIP and the contents looks like this:

```
├── .ebextensions
│   ├── alb-http-to-https-redirection.config
│   ├── htpasswd_webhook.config
│   ├── leader.config
│   └── options.config
├── .platform
│   ├── hooks
│   │   └── postdeploy
│   │       ├── 01_setup.sh
│   │       └── 99_rm_leader_only.sh
│   └── nginx
│       └── conf.d
│           ├── 01_max_body_size.conf
│           └── elasticbeanstalk
│               └── basic_auth_webhook.conf
└── Dockerrun.aws.json
```

Then you use the `AWS CLI` to upload that ZIP to S3, create an application version with it and update the environment with that version, like you see in the linked deploy script.

I don't know if this also works with the `EB CLI` since I don't use it for deploys. My deploy script runs in CI and deploys automatically after each green pipeline. But maybe this helps :)

**Comment by mathieujobin** [comment]
Really cool @gndk 

Thanks

**Comment by mathieujobin** [comment]
For anyone coming across this post, I finally released my builder script for beanstalk-docker.

https://github.com/mathieujobin/beanstalk-docker-deploy/

deploy and autoscaling events happens under a few minutes
