### ISSUE TITLE
Node 16 LTS

### ISSUE THREAD

**Issue by boy51** [aws/elastic-beanstalk-roadmap#201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Is there any heads up when there will be a node 16 platform for EB? Node 14 is going to maintenance soon. We are trying to move from node 14 to 16 for all projects, mainly since npm 7 will be standard and its just so much faster. But also many developers are running around with apple silicon these days which is not supported by node 14. Its quite annoying to be stuck with node 14 in production.

**Comment by camjc** [comment]
This would be very useful for us too.
We raised last year around 14 #138 and didn't get an answer before it was surprise-implemented.

**Comment by jcpage** [comment]
One major reason to support Node 16 & npm 7 is workspaces - we have a monorepo and wasted a bunch of time trying workaround all sorts of things get it to successfully install packages, run, a couple different project workspaces.  Finally had to switch to use docker containers w/ latest node where we could just "npm start -w xxx".  Support for Node 16 would have made this so much easier.

**Comment by jpike88** [comment]
@zzzhu0192 this is really important, node 16.3.0 and more recent versions bring big performance increases to async_hooks which helps with things like instrumentation. Please consider making this more of an urgent requirement

**Comment by camjc** [comment]
Node 12 is about to be deprecated (April), it would be very useful to know if we can jump straight up to 16 so we don't have to go to 14 and then 16 later on.

If we can get an indication on timing it'd really help everyone using EB Node AMIs.

This is the fourth-most thumbs-upped issue in this repo (only behind 2x that have been around 2 years, and one other AMI req, for Java).
I think it warrants a response in this thread, even if its "it won't be until at least after April" or similar, so folks can plan around the EB roadmap.

**Comment by StolenJelly** [comment]
Community needs a plan. EB is awesome but without predictable upgrades we'll all have to move to plain EC2 or alternatives to keep clients and maintainers on side. Just give us a heads up.

**Comment by jpike88** [comment]
@zzzhu0192 care to respond with a clear timeframe on this?

**Comment by sagrawal31** [comment]
> One major reason to support Node 16 & npm 7 is workspaces - we have a monorepo and wasted a bunch of time trying workaround all sorts of things get it to successfully install packages, run, a couple different project workspaces. Finally had to switch to use docker containers w/ latest node where we could just "npm start -w xxx". Support for Node 16 would have made this so much easier.

@jcpage how the support of Node 16 in AWS Elastic beanstalk will help manage workspaces in the local system? Can you please explain? Am I missing something?

My take is that Elastic Beanstalk will only care about compiled JS.

**Comment by jcpage** [comment]
Node 16 comes with npm 7 which is required to support workspaces.  Yes, you can install npm 7+ when building with a node 12 image but it's extra steps, etc.  Simpler and faster just to support node 16 & npm 7 in the docker build images directly.

This isn't really just an EB issue, it's the same with node lambdas.

**Comment by sagrawal31** [comment]
Yes, @jcpage. That's in my knowledge, thank you. My point was to confirm if Elastic Beanstalk/Lambda has something to do with Node 16/npm 7 workspace directly because you mentioned that "_one major reason to support Node 16 & npm 7 is workspace_".

So we can still use workspace locally and deploy the built bundle on Elastic Beanstalk & Lambda.

**Comment by ddkang** [comment]
Is there a timeline for this?

**Comment by ghost** [comment]
Would sure be nice to get this soon we're doing a massive upgrade, so jumping from 12 to 16 now would be rather helpful.

**Comment by camjc** [comment]
And now its released.
<img width="2568" alt="image" src="https://user-images.githubusercontent.com/4197647/156465783-78659004-cc89-4b1e-b9de-8318ec3bdab1.png">

*Can we please get some warning next time?*
We're almost done upgrading to 14 because we didn't get any warning, its a lot of wasted effort.

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-03-02-linux.html

**Comment by camjc** [comment]
@1tonyca is it possible to get notice next time?
Even a range, or a not-before-x would be extremely useful for everyone trying to plan around these upgrades.
