### ISSUE TITLE
.NET 6 on Linux Support 

### ISSUE THREAD

**Issue by waf** [aws/elastic-beanstalk-roadmap#216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
.NET 6 was released on 8 November 2021. Elastic Beanstalk already supports .NET 5 ([see the previous elastic-beanstalk-roadmap tracking issue here](https://github.com/aws/elastic-beanstalk-roadmap/issues/101)), so it'd be great to get access to .NET 6 similarly.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Affects [.NET Core on Linux](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.dotnetlinux)

**Comment by chadmyers** [comment]
.NET 5 is officially EOL on May 08, 2022 (https://github.com/dotnet/core/blob/main/releases.md)  which is 66 days from now. 

Is there any update on this and whether there's a plan to release .NET 6 support in beanstalk before the EOL date of .NET 5?

Thank you!

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-03-31-linux.html
