### ISSUE TITLE
Elastic beanstalk AMIs for NodeJS should use latest kernel 5.10

### ISSUE THREAD

**Issue by dgagnon-simpleset** [aws/elastic-beanstalk-roadmap#228]
AWS announcement from November:  https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-linux-2-ami-kernel-5-10/

We only use NodeJS, so I can not confirm if this is a problem on other environments.

**Comment by matthewdouglas** [comment]
@dgagnon-simpleset You should be able to install `kernel-ng` and upgrade if you need to. I'm doing this step in a pipeline to customize the AMI for the Python 3.8 platform and haven't had any issues with 5.10.

**Comment by dgagnon** [comment]
@matthewdouglas how does the deployment of the EB instance handles the reboot?

**Comment by matthewdouglas** [comment]
@dgagnon I'm not sure; might be worth trying out to see what it does. I would suspect it is something that could be set up through the `packages` part of `.ebextensions`. 

I've been building a custom AMI using EC2 Image Builder with the default Elastic Beanstalk platform AMIs as the source. The built-in components that I apply are `update-linux-kernel-mainline`, `update-linux`, `amazon-inspector-linux`, `stig-build-linux-high`, and `reboot-test-linux`.

**Comment by dgagnon** [comment]
While it would provide the updated kernel, it defeats the purpose.  We really would like not to have to do manual updates to get the latest kernel.

AWS Inspector has been returning 100s of CVE hits on the 4.x branch ( the default kernel ), this is what prompted our adventure in kernel upgrading.

Updating the kernel in a platform hooks (predeploy) and using need-restarting -r in postdeploy kind of works, but it is pretty hackish.

**Comment by matthewdouglas** [comment]
@dgagnon I do agree with that, but also honestly at this point it feels like we may not see much happen until the platforms are rebased on [Amazon Linux 2022](https://aws.amazon.com/linux/amazon-linux-2022/).

The custom AMI route feels slightly less hackish but doesn't work well with managed platform updates. See also #172.

**Comment by praegt** [comment]
AL2 platforms released since March 28, 2024, use kernel 5.10 https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2024-03-28-al2.html

AL2023 platforms use kernel 6.1
https://docs.aws.amazon.com/linux/al2023/ug/performance-optimizations.html
