### ISSUE TITLE
Graviton instance support for Node 16

### ISSUE THREAD

**Issue by jpike88** [aws/elastic-beanstalk-roadmap#234]
`Added a new platform branch, Node.js 16. For documentation of the latest version, see [Node.js v16.x Documentation](https://nodejs.org/dist/latest-v16.x/docs/api/). Graviton instance type support for the Node.js 16 platform branch will be available in the next Node.js platform update.`

This is mentioned in your docs, would be good if this was tracked as an issue here so people can be notified when it's closed. I wish I would be auto notified each time a new platform release drops but this is the next best thing

**Comment by 1tonyca** [comment]
Thanks for creating an issue to track this, and it will be available soon

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-03-31-linux.html
