### ISSUE TITLE
Elastic Beanstalk console major refresh

### ISSUE THREAD

**Issue by jsheld** [aws/elastic-beanstalk-roadmap#24]
The Elastic Beanstalk console is getting a major overhaul to its look and feel.  In late January, we will release a beta version of the revamped console that will allow customers in us-east-1 to continue using the console as they know it today or optionally explore the new console experience we plan to introduce to all regions later this year.  Improvements include streamlined and simplified navigation, a UX that represents a much cleaner and intuitive representation of your Elastic Beanstalk resources, the ability to search and quickly find resources based on a variety of attributes,
quick-links that allow you to seamlessly navigate back to recent environments you touched, and many other new and exicting features!

**Comment by jsheld** [comment]
The new version of the console is now publicly available in us-east-1!  If you find something delightful or want to share critiques or criticisms, we want to know. Use the feedback link in the footer of the console to let us know what you think.

**Comment by pprahlad** [comment]
This is now publicly available in all regions.
