### ISSUE TITLE
Upgrade glibc on the Ruby platform graviton images

### ISSUE THREAD

**Issue by ramonpm** [aws/elastic-beanstalk-roadmap#246]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
We tried to migrate to Graviton instances unsuccessfully because the available AMIs do not have an updated version of the glibc lib.
Nokogiri fails to install with the error saying that it requires a glibc >= 2.29 and the AMIs have installed version 2.26

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Ruby

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It should be a simple change, just to have an updated version installed. We could install it ourselves but then it's bad because of having to download, compile and install the lib every time we replace an instance, it's better to have it on the image directly.

**Are you currently working around this issue?**
No. Sadly, we are just not using Graviton.

**Additional context**
It was the last blocking point, but perhaps there are more after fixing this one. Could you please try running a real-world ruby on rails application on it and seeing if everything installs?

**Comment by erotte** [comment]
👍

**Comment by praegt** [comment]
Amazon Linux 2023 comes with glibc 2.34
https://docs.aws.amazon.com/linux/al2023/ug/core-glibc.html
https://docs.aws.amazon.com/linux/al2023/ug/amzn2-al2023-ami.html

Find supported platforms on AL2023 here: https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html
