### ISSUE TITLE
Amazon Linux 2023 support

### ISSUE THREAD

**Issue by bofkentucky** [aws/elastic-beanstalk-roadmap#249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Amazon Linux 2 is going to be an unsupported platform in a year unless Amazon Linux team extends support beyond their published dates of June 2023.  Even though Amazon Linux 2022 hasn't went GA, it would be helpful to get a timeline on when or if 2022 is going to be supported on beanstalk by the time AL2 falls off support. 

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?
No, affects all Linux platforms

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Issue is largely self-serving, if AL 2022 isn't a supported platform by  Feb 1 2023, I will have a limited window in late Q2 2023 to implement, test, and convert my existing beanstalk apps to AL 2022 due to internal change controls around a large event in our industry.

**Are you currently working around this issue?**
How are you currently solving this problem?
Not an issue yet, but seeking roadmap clarity. 
**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by darin-holloway** [comment]
The AL2 FAQ has been recently updated `Q. When will support for Amazon Linux 2 end?
Amazon Linux 2 end of support date (End of Life, or EOL) has been extended by one year from 2023-06-30 to 2024-06-30 to provide customers with ample time to migrate to [Amazon Linux 2022](https://aws.amazon.com/linux/amazon-linux-2022/). Amazon Linux 2022 Generally Available release is scheduled for later this year, and will be supported for five years.`

**Comment by ScottHull** [comment]
Interesting that EOL is announced before the next version is even in general availability.  For my apps, the migration from Amazon Linux 1 to 2 was a total headache...not looking forward to doing that again.  AWS continues to make Docker almost mandatory for developers who do not want to deal with the continuous short-term heart attacks around OS support.

**Comment by darin-holloway** [comment]
> Interesting that EOL is announced before the next version is even in general availability.  For my apps, the migration from Amazon Linux 1 to 2 was a total headache...not looking forward to doing that again.  AWS continues to make Docker almost mandatory for developers who do not want to deal with the continuous short-term heart attacks around OS support.

This wasn't their fault entirely, the skinny ties running Redhat these days killed CentOS 8 early.

**Comment by kevinh-csalabs** [comment]
@1tonyca any chance this will fix the issue of .ebextensions being ignored? https://github.com/aws/elastic-beanstalk-roadmap/issues/189

**Comment by gloriousjob** [comment]
This ticket is asking for al2023 to be available in EB before al2 dies (which could mean waiting a year, when al2023 is always halfway in its life cycle). I’m requesting for it to be available now since al2023 is in GA.

**Comment by bofkentucky** [comment]
Summary of current state

Amazon Linux 2023 is GA
Amazon Linux 2 end of support date is currently 2025-06-30
AL2023 ECS optimized containers went GA 2023-04-14
EC2 Image builder support is working https://github.com/aws/ec2-image-builder-roadmap/issues/78

**Comment by goetzb** [comment]
The first Elastic Beanstalk platform with Amazon Linux 2023 has now been released - surprisingly (see #174), it's the Python platform: https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-05-04-al2023.html

**Comment by gloriousjob** [comment]
Any roadmap for the .net core platform?

**Comment by andyhethers** [comment]
Any idea when this is going to be available for the PHP platform?

**Comment by Harrythespy** [comment]
Any news for Node.js platform?

**Comment by baiyli** [comment]
Hey @andyhethers @Harrythespy ,

Elastic Beanstalk launches PHP 8.1, PHP 8.2, Node.js 18, Docker and Corretto 17 platforms based on AL2023 today. More Elastic Beanstalk platforms based on AL2023 will come soon. Thanks for your support in Elastic Beanstalk service.

For more information: https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-08-04-al2023.html

**Comment by andyhethers** [comment]
Great news! Thanks for the update.

**Comment by darin-holloway** [comment]
This is technically done, there are al2023 versions of all beanstalk platforms at this point and the al2 platform retirements are happening/scheduled

**Comment by acorncom** [comment]
Should this issue be closed then?

**Comment by darin-holloway** [comment]
@acorncom Yes, I believe this one should be closed
