### ISSUE TITLE
AWSEBCLI on Github

### ISSUE THREAD

**Issue by jsheld** [aws/elastic-beanstalk-roadmap#25]
The AWS Elastic Beanstalk Command Line Interface (CLI) is a tool that helps you deploy and manage
your AWS Elastic Beanstalk applications and environments.  It has always been our intent to pubilsh the CLI on GitHub and with this effort we hope to achieve a number of goals, to include: 

- Encouraging external participation in feature enhancements and bug fixes.
- Fostering an online community of CLI developers (developers helping developers).
- Providing an opportunity to recognize external developers that evangelize the product and contribute toward its improvement.
- Demonstrating more convincingly the idea to current and prospective customers that Beanstalk is builder-friendly.

We look forward to engaging with our avid Elastic Beanstalk developer community!

**Comment by G-Rath** [comment]
Here's where the repo ended up: https://github.com/aws/aws-elastic-beanstalk-cli
