### ISSUE TITLE
Docker Compose V2

### ISSUE THREAD

**Issue by mamurphy** [aws/elastic-beanstalk-roadmap#255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

Elastic Beanstalk currently uses Docker Compose version 1.29.2. Docker compose V1 has been deprecated and Docker Compose V2 has become the standard as of April 2022. I would like to request EB move to use the new Docker Compose V2.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

This is specific to the Docker platform.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Trying to avoid using a deprecated CLI.

**Are you currently working around this issue?**
How are you currently solving this problem?

We have to continue to use the Docker Compose V1 CLI in all of our local and CI testing in order to match reality of how containers are built and deployed on the EC2 instances by EB.

**Additional context**
Anything else we should know?

I have opened a ticket with AWS Support and they have created a feature request on my behalf with the internal team but suggested that I also request here.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

Relevant links:
https://docs.docker.com/compose/reference/
https://www.docker.com/blog/announcing-compose-v2-general-availability/

**Comment by baiyli** [comment]
Hey @mamurphy ,

Docker Compose V2 is available on both `Docker on AL2` and `Docker on AL2023` platforms. Thanks for your support for Elastic Beanstalk service.

Docker Compose V2 support in `Docker on AL2`: https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-07-28-al2.html
Docker Compose V2 support in `Docker on AL2023`: https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-08-04-al2023.html
