### ISSUE TITLE
PHP8.1 support lacking basic requirements

### ISSUE THREAD

**Issue by MortenDHansen** [aws/elastic-beanstalk-roadmap#256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Though amazon-linux-2 is behind on PHP support, an official platform is now released with php8.1. The solution however does not quite solve the needs. There seems to be no supported/documented way to add extensions since the platform is still 8.0 with php8.1 preinstalled on top. If user installs an extension, the php8.0 version is installed. 
  As an example, i am trying to install redis and pcntl which is apparently not possible. Referring to the documentation (eg. https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-pecl7-amazon-linux2/) is not applicable for the php8.1 platform in most cases.

_Note, the mentioned article is an example of a document that is not applicable due to the different nature of the php8.1 platform choice. I realize the article is rather old and It is of course possible to workaround the redis installation issue_

**Is this request specific to an Elastic Beanstalk [platform].**
PHP

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**. 
The concrete example is for trying to run a Laravel installation using php8.1 with elasticache redis and pcntl (for Horizon). Not really anything special, but basic package installation is needed.

**Are you currently working around this issue?**. 
I currently have no solution, but i am experimenting with workarounds. I tried the following
 - Ignore the php8.1 platform choice and instead use the 8.0. On the php8.1 there doesn't seem to be a straightforward way work with the php8.1 installation since the image is actually an 8.0 version as per amazon-linux-2. 
 - Uninstall all php and disable the amazon-linux-extras php8.0. 
 - Install php 8.1 from remi
Now the image has the "correctly installed" php 8.1 where it is possible to add extensions etc. Adding a symlink to php81 binary for /usr/bin/php finishes that setup.

Now, php-fpm can of course be installed, but i am not savvy enough to figure out what to do to make the special elastic-beanstalk setup work with the new php version. Might be trivial, but it seems to be undocumented territory. I am able to get everything running, but elastic-beanstalk entangles with the configuration in a way that i haven't figured out.

(see https://github.com/aws/elastic-beanstalk-roadmap/issues/214 )

**Comment by MortenDHansen** [comment]
Here is switching php out on the php8.0 platform:

```
    sudo yum -y remove $(yum list installed | grep amzn2extra-php8.0 | awk '{ print $1 }')
    sudo yum -y remove php-*
    sudo amazon-linux-extras disable php8.0

    sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    sudo yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    sudo yum -y install yum-utils

    sudo yum-config-manager --disable 'remi-php*'
    sudo yum-config-manager --enable remi-php81
    yum install -y libsodium libsodium-devel
    sudo yum -y install php81
    sudo yum -y install php81-php-{cli,fpm,mysql,devel,pdo,gd,mbstring,bcmath,opcache,redis}

    sudo mv /usr/bin/php /usr/bin/old-php
    sudo ln -s /usr/bin/php81 /usr/bin/php

    # this doesn't work:
    # sudo mv /usr/sbin/php-fpm /usr/sbin/old-php-fpm
    # sudo ln -s /opt/remi/php81/root/usr/sbin/php-fpm /usr/sbin/php-fpm
    # sudo systemctl restart php-fpm
```

**Comment by christian-manrique** [comment]
> Here is switching php out on the php8.0 platform:
> 
> ```
>     sudo yum -y remove $(yum list installed | grep amzn2extra-php8.0 | awk '{ print $1 }')
>     sudo yum -y remove php-*
>     sudo amazon-linux-extras disable php8.0
> 
>     sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
>     sudo yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm
>     sudo yum -y install yum-utils
> 
>     sudo yum-config-manager --disable 'remi-php*'
>     sudo yum-config-manager --enable remi-php81
>     yum install -y libsodium libsodium-devel
>     sudo yum -y install php81
>     sudo yum -y install php81-php-{cli,fpm,mysql,devel,pdo,gd,mbstring,bcmath,opcache,redis}
> 
>     sudo mv /usr/bin/php /usr/bin/old-php
>     sudo ln -s /usr/bin/php81 /usr/bin/php
> 
>     # this doesn't work:
>     # sudo mv /usr/sbin/php-fpm /usr/sbin/old-php-fpm
>     # sudo ln -s /opt/remi/php81/root/usr/sbin/php-fpm /usr/sbin/php-fpm
>     # sudo systemctl restart php-fpm
> ```

Hi @MortenDHansen MortenDHansen, thanks very much for sharing your solution but this workaround is not working on my server, let me attach the error returned for any advice thank you so much

`sudo yum install -y libsodium libsodium-devel`

`http://rpms.remirepo.net/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://fr2.rpmfind.net/linux/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://remi.mirrors.arminco.com/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 12] Timeout on http://remi.mirrors.arminco.com/enterprise/7/php81/aarch64/repodata/repomd.xml: (28, 'Failed to connect to remi.mirrors.arminco.com port 80 after 2702 ms: Connection timed out')
Trying other mirror.
http://remi.schlundtech.de/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://mirror.awanti.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://mirror.cedia.org.ec/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://ftp.arnes.si/mirrors/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://remi.conetix.com.au/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://mirrors.neterra.net/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://mirrors.thzhost.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://mirrors.netix.net/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://remi.mirrors.cu.be/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://mirror.neolabs.kz/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://mirror.veriteknik.net.tr/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.veriteknik.net.tr/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: (28, 'Failed to connect to mirror.veriteknik.net.tr port 80 after 2702 ms: Connection timed out')
Trying other mirror.
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
http://repo1.dal.innoscale.net/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
https://mirror.oxilion.nl/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirrors.uni-ruse.bg/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://remi.mirror.karneval.cz/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirror.netsite.dk/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
http://mirror.reconn.ru/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
https://mirrors.ukfast.co.uk/sites/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirror.netweaver.uk/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
http://mirror.team-cymru.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://ftp.riken.jp/Linux/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
https://mir01.syntis.net/remirepo/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
http://mirrors.bytes.ua/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://remirepo.reloumirrors.net/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
https://mirror.pit.teraswitch.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://remi.mirror.liteserver.nl/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirror.marwan.ma/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://remi.mivzakim.net/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://remi.mirror.digitalpacific.com.au/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://merlin.fit.vutbr.cz/mirrors/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirrors.ptisp.pt/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirrors.upr.edu/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
http://mirror.yer.az/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
https://mirror.dk.team.blue/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirror.docker.ru/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirror.ihost.md/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirror.23m.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
http://mirror.hoster.kz/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
https://repo.extreme-ix.org/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirror.usi.edu/pub/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://mirror.mangohost.net/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.


 One of the configured repositories failed (Remi's PHP 8.1 RPM repository for Enterprise Linux 7 - aarch64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=remi-php81 ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable remi-php81
        or
            subscription-manager repos --disable=remi-php81

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=remi-php81.skip_if_unavailable=true

failure: repodata/repomd.xml from remi-php81: [Errno 256] No more mirrors to try.
http://rpms.remirepo.net/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://fr2.rpmfind.net/linux/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://remi.mirrors.arminco.com/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 12] Timeout on http://remi.mirrors.arminco.com/enterprise/7/php81/aarch64/repodata/repomd.xml: (28, 'Failed to connect to remi.mirrors.arminco.com port 80 after 2702 ms: Connection timed out')
http://remi.schlundtech.de/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirror.awanti.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirror.cedia.org.ec/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://ftp.arnes.si/mirrors/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://remi.conetix.com.au/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirrors.neterra.net/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirrors.thzhost.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirrors.netix.net/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://remi.mirrors.cu.be/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirror.neolabs.kz/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirror.veriteknik.net.tr/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.veriteknik.net.tr/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: (28, 'Failed to connect to mirror.veriteknik.net.tr port 80 after 2702 ms: Connection timed out')
https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
http://repo1.dal.innoscale.net/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
https://mirror.oxilion.nl/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirrors.uni-ruse.bg/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://remi.mirror.karneval.cz/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirror.netsite.dk/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
http://mirror.reconn.ru/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
https://mirrors.ukfast.co.uk/sites/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirror.netweaver.uk/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
http://mirror.team-cymru.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://ftp.riken.jp/Linux/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
https://mir01.syntis.net/remirepo/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
http://mirrors.bytes.ua/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://remirepo.reloumirrors.net/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
https://mirror.pit.teraswitch.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://remi.mirror.liteserver.nl/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirror.marwan.ma/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://remi.mivzakim.net/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://remi.mirror.digitalpacific.com.au/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://merlin.fit.vutbr.cz/mirrors/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirrors.ptisp.pt/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirrors.upr.edu/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
http://mirror.yer.az/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
https://mirror.dk.team.blue/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirror.docker.ru/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirror.ihost.md/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirror.23m.com/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
http://mirror.hoster.kz/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
https://repo.extreme-ix.org/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirror.usi.edu/pub/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
https://mirror.mangohost.net/remi/enterprise/7/php81/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

**Comment by MortenDHansen** [comment]
> Hi @MortenDHansen MortenDHansen, thanks very much for sharing your solution but this workaround is not working on my server, let me attach the error returned for any advice thank you so much

Notice that i wasn't sharing a solution. Just posting an example of attempting to workaround to show the roadblock.

**Comment by 1tonyca** [comment]
Thank you for your patient, as part of https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-08-31-al2.html, freetype, pecl and pcntl are now supported.

**Comment by gourav-rcrm** [comment]
@christian-manrique , were you able to find a solution for the issue you had shared? I am also facing the same issue
