### ISSUE TITLE
Looking for a change log

### ISSUE THREAD

**Issue by mathieujobin** [aws/elastic-beanstalk-roadmap#257]
We are seeing these upgrades to our Beanstalk environments.

```
Platform branch
Docker running on 64bit Amazon Linux 2
Current platform version
3.4.17
New platform version
3.4.18 (Recommended)
```

Where can we find out the differences applied in these?

I deploy rails applications via docker on beanstalk.

Thank you

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Comment by xuechenf-pek** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/relnotes.html
