### ISSUE TITLE
PHP 3.5.0 is broken

### ISSUE THREAD

**Issue by nickdnk** [aws/elastic-beanstalk-roadmap#259]
Hello

I don't know where else to report this, but I cannot update to the latest version of EB (3.5.0) for PHP. Instances fail deployment with this error:

```
2022/10/04 03:17:57.346653 [INFO] Executing instruction: stop php-fpm
2022/10/04 03:17:57.346677 [INFO] Running command /bin/sh -c systemctl show -p PartOf php-fpm.service
2022/10/04 03:17:57.350314 [WARN] stopProcess Warning: process php-fpm is not registered 
2022/10/04 03:17:57.350335 [INFO] Running command /bin/sh -c systemctl stop php-fpm.service
2022/10/04 03:17:57.353508 [INFO] Failed to stop php-fpm.service: Unit php-fpm.service not loaded.

2022/10/04 03:17:57.353532 [ERROR] An error occurred during execution of command [self-startup] - [stop php-fpm]. Stop running the command. Error: stop php-fpm failed with error stopProcess Failure: stopping process php-fpm failed: Command /bin/sh -c systemctl stop php-fpm.service failed with error exit status 5. Stderr:Failed to stop php-fpm.service: Unit php-fpm.service not loaded.
  

2022/10/04 03:17:57.353535 [INFO] Executing cleanup logic
2022/10/04 03:17:57.353730 [INFO] Platform Engine finished execution on command: self-startup
```

Rolling back to 3.4.1 fixes this, where the logs look like this instead:

```
2022/10/04 03:22:28.073957 [INFO] Executing instruction: stop php-fpm
2022/10/04 03:22:28.073984 [INFO] Running command /bin/sh -c systemctl show -p PartOf php-fpm.service
2022/10/04 03:22:28.078931 [WARN] stopProcess Warning: process php-fpm is not registered 
2022/10/04 03:22:28.078977 [INFO] Running command /bin/sh -c systemctl stop php-fpm.service
2022/10/04 03:22:28.084296 [INFO] Executing instruction: FlipApplication
```

Please take a look at this immediately if possible. I had to disable automatic updates for our production environment to avoid running into this. Thankfully I only upgraded our staging environment, because the whole thing came crashing down and it started starting and terminating instances really quickly because I have ELB checks enabled.

Edit: I tried creating a new environment starting at 3.5.0, and that did work, but I cannot get my existing ones upgraded. Same error after multiple attempts; I also did an "environment rebuild" before upgrading; same problem. Still, rolling back to 3.4.1 and everything works fine.

**Comment by aromka** [comment]
We get the same thing - "Failed to stop php-fpm.service: Unit php-fpm.service not loaded." 

Running `sudo systemctl restart php-fpm.service` manually on the server returns `Failed to restart php-fpm.service: Unit not found.`

php-fpm module is not installed and cannot be installed through yum.

**Comment by RachelZhao** [comment]
Hi @nickdnk and @aromka
Could you please confirm that whether your environment is using a custom AMI, or is using ARM architecture?

@aromka, did you also find this failure after environment update?

**Comment by nickdnk** [comment]
> Hi @nickdnk and @aromka Could you please confirm that whether your environment is using a custom AMI, or is using ARM architecture?
> 
> @aromka, did you also find this failure after environment update?

ARM, default AMI provided by EB for PHP 8.1.

**Comment by aromka** [comment]
@RachelZhao - yes, tried all options (for PHP 8.1) - update existing env from 3.4.1 to 3.5.0, create a new env from scratch on 3.5.0, and "clone with latest version" - all options failed the deploys. Manually SSH'ing into the env and trying to find php-fpm also gave no result. Trying to install php-fpm via yum returned errors saying package not found / doesn't exist.

We haven't tried to upgrade PHP 8.0 to 3.5.0 though, and I see that all our servers have scheduled upgrade to 3.5.0, which is concerning.

**Comment by nickdnk** [comment]
I did try creating an entirely new environment, downgrade it to 3.4.1 and back to 3.5.0, which worked fine, but I **think** this was with x86, so that might be a variable to isolate. I just accepted the defaults for creating a new environment, just to test, and that did work.

Edit: I mean the template environment for PHP 8.1; no customization or code deployment.

**Comment by nickdnk** [comment]
I tried creating a template environment with ARM today, which also seems to up- and downgrade correctly between 3.4.1 and 3.5.0. No idea why it breaks my real environments. Any news here @RachelZhao ?

**Comment by GreenBadger** [comment]
Same issue here when upgrading from Amazon Linux 2 PHP 8.1 version 3.4.1 to 3.5.0

**Comment by nickdnk** [comment]
I also get this error **a lot** lately. Almost every deployment (but not all) end up with 1 instance in this state, that I have to manually terminate for it to be replaced.

![Screenshot 2022-10-07 at 16 20 21](https://user-images.githubusercontent.com/8411314/194575844-36e0366c-63d3-4335-8608-56514e61cbc7.png)

**Comment by nickdnk** [comment]
@1tonyca Any updates here?

**Comment by RachelZhao** [comment]
@nickdnk 
This issue is fixed already for all new environments, you could start a new EB environment to solve this issue.

To unblock for all existing environment, please run the following command using "awscli" :

`aws elasticbeanstalk update-environment --environment-name release-api --options-to-remove Namespace=aws:autoscaling:launchconfiguration,OptionName=ImageId`

And upgrade again.

Thanks

**Comment by nickdnk** [comment]
> @nickdnk This issue is fixed already for all new environments, you could start a new EB environment to solve this issue.
> 
> To unblock for all existing environment, please run the following command using "awscli" :
> 
> `aws elasticbeanstalk update-environment --environment-name release-api --options-to-remove Namespace=aws:autoscaling:launchconfiguration,OptionName=ImageId`
> 
> And upgrade again.
> 
> Thanks

Thanks. I will try.

**Comment by Frtrillo** [comment]
> @nickdnk This issue is fixed already for all new environments, you could start a new EB environment to solve this issue.
> 
> To unblock for all existing environment, please run the following command using "awscli" :
> 
> `aws elasticbeanstalk update-environment --environment-name release-api --options-to-remove Namespace=aws:autoscaling:launchconfiguration,OptionName=ImageId`
> 
> And upgrade again.
> 
> Thanks

Hello, I have same issue running on 3.4.1. How Im supposed to upgrade my environment without having to create a new one and re-configure everything?... 
If its with that command, which options I have to change from it

**Comment by Smef** [comment]
I had done the environment update from 3.4.1 which left it in a broken state, but on 3.5.3. Running the suggested command after that allowed to redeploy itself and resolved the issue.

**Comment by alekmlynek** [comment]
I'm getting this in 3.5.4 and 3.5.3. Anyone else? I've been fighting with this not realizing this is an AWS issue.
