### ISSUE TITLE
PrivateLink support

### ISSUE THREAD

**Issue by chadhayton** [aws/elastic-beanstalk-roadmap#26]
We are currently adding support for AWS PrivateLink to Elastic Beanstalk.  PrivateLink allows customers to better secure their Elastic Beanstalk environments by ensuring that traffic doesn't traverse the Internet, reducing the exposure to threat vectors such as brute force and distributed denial-of-service attacks. PrivateLink can also provide private connectivity between VPCs, AWS services, and on-premises applications, securely on the Amazon network.

**Comment by hamza-eljohri** [comment]
Could you please tell us when it will be available ?
