### ISSUE TITLE
Add Retry and Exception Handling Logic to 01iisreset.bat

### ISSUE THREAD

**Issue by twinmind** [aws/elastic-beanstalk-roadmap#261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Beanstalk on Windows is using `C:\Program Files\Amazon\ElasticBeanstalk\hooks\restartappserver\enact\01iisreset.bat` which contains `IISReset` command without any retry logic or exception handling. IISReset command is prone to throwing errors and we observed `restartAppServer` command failure on our production environment due to `IISReset` failure in `estartappserver\enact`.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Windows Server 2019 with IIS 10.0 version 2.10.4

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We need robust and reliable environment restarts and deployments, unhandled IISReset is by itself makes beanstalk command chain janky.

**Are you currently working around this issue?**
How are you currently solving this problem?
We're thinking of replacing `01iisreset.bat` with some custom hook during deploy if this is not fixed

**Comment by praegt** [comment]
Windows Server platform versions 2.10.6 and later, released since November 2022, have retry logic and exception handling for IISReset related to the restart app server command
