### ISSUE TITLE
PHP 8.1 related error: git not availabe during deployment

### ISSUE THREAD

**Issue by tobiaseichert** [aws/elastic-beanstalk-roadmap#262]
Running the default `/bin/sh -c composer.phar install --no-ansi --no-interaction` inside a PHP 8.1 environment (64bit Amazon Linux 2/3.5.0) currently results in an error, e.g.

```
In Git.php line 484:
                                                                               
  Failed to clone https://git.drupalcode.org/project/coder.git, git was not f  
  ound, check that it is installed and in your PATH env.                       
                                                                               
  sh: git: command not found 
```

However, git is installed:
```
[ec2-user@ip-172-31-4-122 ~]$ which git
/usr/bin/git
```
 Is this an environment related bug at deployment time? There's no problem when performing a deployment inside a PHP 7.4 environment.

_Originally posted by @tobiaseichert in https://github.com/aws/elastic-beanstalk-roadmap/issues/214#issuecomment-1293418700_

**Comment by tobiaseichert** [comment]
Any update on this? Right now, deployment using composer.json/composer.lock and git is broken for the php-8.1 platform. Workaround would be to include the vendor folder so composer.json will be ignored, as described [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-configuration-composer.html). Switching to php-8.0 for now.

Please let me know if you need further details/logs.

**Comment by baiyli** [comment]
Hey @tobiaseichert. Please open a support case, you can reach us via https://aws.amazon.com/contact-us/

**Comment by tobiaseichert** [comment]
Hi @baiyli I don't think this is a case of technical support, as I followed along [the documentation mentioned above](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-configuration-composer.html). This works for PHP environments < 8.1, so something has changed in your setup. I already sent feedback to the docs team, but haven't received any feedback so far.

**Comment by acorncom** [comment]
@tobiaseichert is this still an issue for you? I'm seeing PHP 8.1 work without issues

**Comment by tobiaseichert** [comment]
Hi @acorncom Unfortunately, using `composer install` with custom git repositories still won't work with Amazon Linux 2 (PHP 8.1, fresh install, no upgrade):

```
Failed to clone https://git.drupalcode.org/sandbox/<myrepo>.git, git
was not found, check that it is installed and in your PATH env.            
                                                                               
sh: git: command not found
```

I'm at a loss here, as git is available when connecting to the instance using `eb ssh`. Right now, I consider it an Amazon Linux 2 bug as there aren't code changes on our site and deployment works just fine using Amazon Linux 2 (PHP 8.0) with custom git repositories defined in composer.json.

I wonder if the Amazon Linux 2 PHP team ist reading this, as this doesn't seem to be a case of paid technical support.

**Comment by tobiaseichert** [comment]
Additionally, to ensure that git is installed before `composer install` is invoked, I explicitly added git as package dependency and let the process write its location to a file /root/git_location.txt:

00env.config inside .ebextensions
```yaml
packages:
    yum:
        git: []
commands:
    whichgit:
        command: which git >> /root/git_location.txt
```

After connecting to the instance I ran the following command as root:
```sh
cat git_location.txt 
/usr/bin/git
```

So it's definitely there but apparently not in the path of the process that runs composer install during deployment, which is different from the way it worked in Amazon Linux 2 (PHP 8.0).

**Comment by acorncom** [comment]
@tobiaseichert are you able to dig into your logs further? I'm using a number of custom Git repos (vs Packagist packages) without issue on 64bit Amazon Linux 2/3.5.6 on PHP 8.1. But in my case all repos are installed using git urls, NOT http urls (i.e. `git://github.com/<org>/<repo>.git`).

But that's been working smoothly and without incident for the last month as we've setup this environment

**Comment by tobiaseichert** [comment]
@acorncom Interestingly, during `composer install`, `unzip` isn't available too:

/var/log/eb-engine.log
```
Package operations: 201 installs, 0 updates, 0 removals
As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' (21.01+) may remediate them.
```

However, it's installed:
```sh
which unzip
/usr/bin/unzip
```

Does unzip work for you during installation?

**Comment by acorncom** [comment]
@tobiaseichert yes, looks like it's running fine

```
2023/04/25 14:02:14.987198 [INFO] Running command /bin/sh -c /usr/bin/unzip -q -o /opt/elasticbeanstalk/de
ployment/app_source_bundle -d /var/app/staging/
```

**Comment by acorncom** [comment]
@tobiaseichert ah, realized where my app may differ from yours.

In this app, we have two `composer` files (for reasons that aren't interesting here). The composer.json file that matters lives inside of an `app` folder inside the root directory and I haven't yet figured out how to control how to tell EB's composer installation to use my `<project>/app/composer.json` file instead of `<project>/composer.json`. So currently when EB installs composer it uses our `<project>/composer.json` file which has no packages and then I trigger a second install using `.platform/hooks/prebuild/1-init.sh` file:

```
#!/bin/bash
php -d memory_limit=-1 /usr/bin/composer.phar install --no-dev --no-interaction --prefer-dist --optimize-autoloader --prefer-dist -d app
```

That may be how I bypass the snag you're hitting?

**Comment by tobiaseichert** [comment]
@acorncom Progress! If I explicitly set the `PATH` variable inside an ebextensions config file, deployment completes successfully, as git and unzip are now found during `composer install`:

.ebextensions/00env.config
```yaml
    aws:elasticbeanstalk:application:environment:
        PATH: $PATH
```

This leads to the question of why this is necessary for AL2 PHP 8.1 but not AL2 PHP 8.0 with no changes otherwise. 🤔

Your solution seems to bypass the problem (unintentionally?), as you explicitly call composer on your own a second time with a properly set PATH. Usually, running `composer` automatically through Elastic Beanstalk's mechanism should be working just fine.

Thanks for your help narrowing down the problem! As a workaround, setting PATH should be enough. Still, I think this is a bug on their side.

**Comment by acorncom** [comment]
@tobiaseichert glad you got it sorted out and yes, your fix does make it sound like an issue for EB. Might be worth opening a support case so the appropriate internal team can address it now that we've narrowed it down ...

**Comment by RachelZhao** [comment]
@tobiaseichert this should already been fixed in our May release. Let us know if you are still seeing the issue.

**Comment by tobiaseichert** [comment]
Hi @RachelZhao Yes, the issue has been fixed. It's now working as expected. Thanks!
