### ISSUE TITLE
PHP 8.1 not published as Amazon Linux Extra

### ISSUE THREAD

**Issue by PaulBehrendtVentoro** [aws/elastic-beanstalk-roadmap#265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
As of _PHP 8.1_, EB seems not to use _amazon-linux-extras_. So, I am unable to build a Docker image for local dev & CI/CD. 

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
64bit Amazon Linux 2 v3.5.0 running PHP 8.1

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
For local development and CI/CD-purposes, we have, in the past, used a Docker image to imitate what the EB-AMI does (`FROM amazonlinux:2`).
And for some dependencies like Memcached, the Dockerfile also imitated what was defined in our _.ebextensions_ (yum-installs, pecl-stuff etc.).
This is impossible from now on, or am I missing something?
We want our local environment to be as close to production as possible. We need a way where setting up PHP extensions locally can be sourced from production configuration, vice-versa.
But, we are looking for a curated image and want to avoid a migration to Docker for production.
If this is the only possibility, we might as well switch from AWS EB to Laravel Forge + Homestead.

**Are you currently working around this issue?**
By not upgrading from _PHP 8.0_.

**Comment by bits4breakfast** [comment]
As far as I can see PHP 8.1 is now available

```
$ amazon-linux-extras list | grep php
 42  php7.4=latest            enabled      [ =stable ]
  _  php8.0                   available    [ =stable ]
  _  php8.1                   available    [ =stable ]
```

**Comment by jrmaia** [comment]
sudo amazon-linux-extras enable php8.1
Refusing because php8.1 could cause an invalid combination.

**Comment by netadapt** [comment]
> sudo amazon-linux-extras enable php8.1

First disable 8.0 : 

sudo amazon-linux-extras disable php8.0
