### ISSUE TITLE
.NET 7 on Linux Support 

### ISSUE THREAD

**Issue by lister-service** [aws/elastic-beanstalk-roadmap#266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?

.NET Core 7 was officially released on November 8th.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

[.NET Core on Linux](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.dotnetlinux)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Looking to be able to deploy new .NET Core applications to AWS - unable to do so currently.

**Are you currently working around this issue?**
How are you currently solving this problem?

Still running .NET 6 for new applications

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by chrispaynter** [comment]
This is a massive blocker for an upgrade we want to do, I would have hoped to see Beanstalk stay up to date with the latest run times.

**Comment by chrispaynter** [comment]
Hmmm, actually I updated to this - 64bit Amazon Linux 2 v2.4.1 running .NET Core

Looks like it does support .NET 7, however they website doesn't list it in the Frameworks section.

https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-dotnetlinux.html

**Comment by chrispaynter** [comment]
Ignore that I must have read my logs wrong. .NET 7 not supported. This is something I'd consider rather urgent for AWS to resolve.

**Comment by matheuscschenfeld** [comment]
Does anyone have a solution?

Trying to deploy a .net 7 application to Elastic Beanstalk runnion on Amazon Linux 2

**Comment by smbadiwe** [comment]
@matheuscschenfeld @chrispaynter 

If you build your project as Self-Contained, you can run .NET 7 on AWS Elastic Beanstalk.

To do this, check the box: `Build self-contained deployment bundle`.

![image](https://user-images.githubusercontent.com/10943435/212841396-1ec0d437-6f49-4e8c-bb9e-b09fd7c4542d.png)

**Comment by bytecod3r** [comment]
is there any development roadmap to include dotnet 7 on the elasticbeans?

**Comment by AndrewMutation** [comment]
@smbadiwe 

I've got a CI build using the command line  (dotnet restore/build/publish). Do you know what the equivalent runtime ID (or other args I should pass to get the equivalent of the Amazon Publish UI?

I've tried with the folowing, but I'm not sure there is a probleme with my arguments or if its something else that isn't working.

 dotnet publish "my.csproj" -c Release -o publish --runtime linux-x64

**Comment by Persimus** [comment]
@AndrewMutation for build pipelines you need to install the latest .NET build tools:
```
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel ST
```
More info: https://aws.amazon.com/blogs/devops/building-net-7-applications-with-aws-codebuild/

**Comment by AndrewMutation** [comment]
@Persimus 

My build isn't on AWS, but that may help someone else :)

It seems like my problem is probably the glibc version on arm64 that is discussed here: https://github.com/dotnet/runtime/pull/80866

When I installed (Edit: on amazon linux in EB) v7 with dotnet-install.sh, I got the error they describe: `GLIBC_2.27' not found

**Comment by AndrewMutation** [comment]
The issue seems to be resolved for me with the release of 7.0.4
I copied dotnet-install.sh onto the machine and ran it with channel 7.0

dotnet-install.sh --channel 7.0 --runtime aspnetcore -InstallDir /usr/local/dotnet/

**Comment by RedHot17** [comment]
please hurry with this

**Comment by aswanevelder** [comment]
We are nearing the one year anniversary of DotNet 7, any news when NET Core running on 64bit Amazon Linux 2 will be upgraded to .net 7?

**Comment by edvanr** [comment]
Yeah this is really holding us back. There are so many EF core features in dotnet 7 that we need and it is preventing us from upgrading everything. Very close to ditching beanstalk if this doesn't happen soon...

**Comment by utkugenel** [comment]
I solved this problem using ebextensions.

Created .ebextensions folder in the root of the project and dotnet.config file in it and added dotnet install command.
After deployment, this command run first on elastic beanstalk environment.

dotnet.config file
```
commands:
  01_dotnet_install:
    # install .net 7.0
    command: 'curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 7.0 --runtime aspnetcore -InstallDir /usr/local/dotnet/'
```

**Comment by scionwest** [comment]
I thought Amazon was pretty public about only officially supporting LTS versions of .Net on their platforms - which is 6.0. For things we want to run the latest/greatest on, we deploy to either Lambda with custom runtimes/layers or EC2 directly. For things we want to stick with LTS on, we deploy use the services that are managed more by AWS. These are things you need to take into consideration when you're designing your apps and deciding what your deployment platform will be.

**Comment by matheuscschenfeld** [comment]
I resolved this by using a Docker image in ECR and configuring the service in ECS

**Comment by slavik93** [comment]
Based on https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-dotnetlinux.html there are no default elastic beanstalk platforms that support .NET 7.
As a workaround, you can create a default Elastic Beanstalk platform, .NET Core Linux, which supports .NET 6.
Then, connect to the EC2 instance and install .NET 7 SDK by the following commands:
sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
sudo yum install -y dotnet-sdk-7.0

**Comment by aswanevelder** [comment]
According to @scionwest's comment on STS not supported by AWS, then .Net 8, set to be released between November 14-16, will be the Long-Term Support (LTS) version. I guess then as a result, EB will skip .Net 7, which was a Short-Term Support (STS) release. It's uncertain how long AWS will take to implement this upgrade, but there is optimism for the future.

**Comment by slavik93** [comment]
As an additional option, to deploy a project with a greater .NET SDK than 6 is to add a configuration file in the uploaded Zip for Elastic Beanstalk to install the dependencies during deployment.
Directory Location: You create a directory named .ebextensions at the root of your application source code. Inside this directory, you place configuration files(e.g. 01_install_dotnet_7.config) in YAML or JSON format.
This is the file content to install .NET 7 SDK:
commands:
  01_install_dotnet_7:
    command: |
      sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
      sudo yum install -y dotnet-sdk-7.0

**Comment by xaviermarquez-alba** [comment]
> @matheuscschenfeld @chrispaynter
> 
> If you build your project as Self-Contained, you can run .NET 7 on AWS Elastic Beanstalk.
> 
> To do this, check the box: `Build self-contained deployment bundle`.
> 
> ![image](https://user-images.githubusercontent.com/10943435/212841396-1ec0d437-6f49-4e8c-bb9e-b09fd7c4542d.png)

this works for me; using ` dotnet publish project -c Release -o build --self-contained true`

**Comment by praegt** [comment]
Superseded by .NET 8, which is LTS. Track https://github.com/aws/elastic-beanstalk-roadmap/issues/311 for .NET 8 on Linux
