### ISSUE TITLE
New instance type availability

### ISSUE THREAD

**Issue by alexjurkiewicz** [aws/elastic-beanstalk-roadmap#27]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
t3a instance types are supported in some regions, but not all. Please deploy support for these instance types to Tokyo!

**Comment by danielhklein** [comment]
Thanks for the request! We will look into supporting these instance types in Tokyo, I will provide updates as they become available here.

**Comment by DJAlPee** [comment]
+1 also for Frankfurt (eu-central-1)

**Comment by cheng-liven** [comment]
Will you add t3a support to all remaining regions where t3a hardware is available or do we need to create a separate issue for another region? (Our case: Sydney)

**Comment by labisso** [comment]
@cheng-liven no need for separate issues - we're refreshing our instance type support across all regions

**Comment by alexjurkiewicz** [comment]
Can you talk briefly about how releases to EB are rolled out? My
understanding is that new features are rolled out globally over several
"waves". Do these waves comprise the same regions every time? Or are they
per-feature based on customer demand/something else? Is there a fixed delay
between each wave's release?

**Comment by pjastrzabek** [comment]
👍 can we have some estimations when other regions could be included? 2020 Q2? Q3?

**Comment by Sunkyue-Kim** [comment]
For Seoul too.

**Comment by mikeobr** [comment]
Will instance type support for [g4 instaces](https://aws.amazon.com/ec2/instance-types/g4/) be included? My team is very interested in using these, but they are only available in a few select regions for elastic beanstalk.

**Comment by pprahlad** [comment]
Accidentally closed this issue. Reopening

**Comment by chadhayton** [comment]
We are continuing to work on rolling out t3a support in all regions.  Currently Tokyo does not support t3a, but Frankfort and Sydney do. Below is a list of regions that currently support t3a:
- ap-northeast-2
- ap-south-1
- ap-southeast-1
- ap-southeast-2
- ca-central-1
- cn-north-1
- cn-northwest-1
- eu-central-1
- eu-west-1
- eu-west-2
- eu-west-3
- sa-east-1
- us-east-1
- us-east-2
- us-gov-east-1
- us-gov-west-1
- us-west-1
- us-west-2

**Comment by jjadta** [comment]
Reopening.  Inadvertently closed when removing the Proposed tag.

**Comment by jjadta** [comment]
Support for T3A instances has been rolled out to all applicable regions.  Region list below. Closing.

ap-northeast-2
ap-south-1
ap-southeast-1
ap-southeast-2
ca-central-1
cn-north-1
cn-northwest-1
eu-central-1
eu-west-1
eu-west-2
eu-west-3
sa-east-1
us-east-1
us-east-2
us-gov-east-1
us-gov-west-1
us-west-1
us-west-2

**Comment by itoyama** [comment]
@jjadta Are there any more plans to support the t3a instance type in the Tokyo region(ap-northeast-1)?

**Comment by itoyama** [comment]
@pprahlad @chadhayton @danielhklein @labisso Can anyone answer my question?

**Comment by itoyama** [comment]
@1tonyca Cloud you answer my question?

**Comment by pprahlad** [comment]
@itoyama Thank you for this feedback. Given this issue is closed, I suggest we create a new request and prioritize this alongside other requests.
