### ISSUE TITLE
Add Support for Java/Corretto 19

### ISSUE THREAD

**Issue by steven-khimba** [aws/elastic-beanstalk-roadmap#270]
Community Note
Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.
Tell us about your request
It would be great if EB supported Java/Corretto 19 now that it was released 20 September 2022. Java 19 adds some performance gains.

Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?
If so, which one(s)?

Java SE

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

We want to run the latest LTS version.

Are you currently working around this issue?
How are you currently solving this problem?

Running an old version of Java.

Additional context
Anything else we should know?

No

Attachments
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by darin-holloway** [comment]
19 isn't an LTS though, 17 would be the current LTS

**Comment by darin-holloway** [comment]
and JDK21 has been released, I believe this one is good to close
