### ISSUE TITLE
[Feature Request] Amazon Linux 2023 on Elastic Beanstalk Platforms

### ISSUE THREAD

**Issue by jceduar** [aws/elastic-beanstalk-roadmap#279]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?

The Feature Request is being created to track when the newly released AL2023 will be available for Elastic Beanstalk platforms. 

AWS announced the general availability of [Amazon Linux 2023 (AL2023)](https://aws.amazon.com/linux/amazon-linux-2023/) in the following [blog post](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-linux-2023/) on March 15, 2023.

Please feel free to provide any comments / updates surrounding the desired feature request.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

All Platforms.

**Additional context**
[1] AWS Elastic Beanstalk release notes - https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/relnotes.html
[2] Amazon Linux 2023 release notes - https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html

**Comment by neeo** [comment]
Duplicate? https://github.com/aws/elastic-beanstalk-roadmap/issues/249

**Comment by ashkulz** [comment]
I think so, AWS missed their deadline and had to rename it? :joy:

**Comment by AngelicaFWhite** [comment]
This is a very important upgrade to enable application using Beanstalk to benefit from Linux security fixes deployed  to Amazon Linux 23. Is there an estimation when this will be available?

**Comment by ashkulz** [comment]
I reached out to AWS Support and they have no idea if/when it'll happen.

**Comment by acorncom** [comment]
Looks lie this can be closed
