### ISSUE TITLE
Full Django framework support (GIS libraries on Python platform)

### ISSUE THREAD

**Issue by cheng-liven** [aws/elastic-beanstalk-roadmap#28]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

_**Tell us about your request**
What do you want us to build?_

Make compiled [GIS libraries required by Django](https://docs.djangoproject.com/en/3.1/ref/contrib/gis/install/geolibs/) available in system package repositories so we can install them via EB .config files quickly.

_**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?_

Yes for our use case. Python platform. But the GIS libraries are language-agnostic so it can apply to other platforms as well.

_**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem._

We use Django to build our location-aware mobile apps backend. The [builtin geographic features of Django required a few GIS libraries](https://docs.djangoproject.com/en/3.0/ref/contrib/gis/install/geolibs/) and these libraries are not available in AL repositories so we have to compile from source codes before installation. It takes 20+ minutes to finish the compilation so we have to make a custom EC2 image in advance and a new custom image is required every time a new EB Python platform version is released.

_**Are you currently working around this issue?**
How are you currently solving this problem?_

Build a custom EC2 system image: 

1. Launch a new EB Python web app.
1. SSH to the EB instance.
1. Install some build tool packages.
1. Compile and install the GIS libraries from source codes (took 20+ minutes).
1. Export path of installed libraries to system environment variables.
1. Save as a custom EC2 system image.
1. Launch new EB instances with the custom EC2 image.
1. Repeat steps above when there is a new EB platform version.

_**Additional context**
Anything else we should know?_

RDS PostgreSQL already [supports the required PostGIS extension since late 2013](https://aws.amazon.com/blogs/aws/amazon-rds-for-postgresql-now-available/).

Many people would appreciate the feature: [questions asked on stackoverflow again and again](https://www.google.com/search?q=elastic+beanstalk+geodjango+site:stackoverflow.com)

_**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)_

No.

**Comment by labisso** [comment]
Thanks for the suggestion @cheng-liven! I definitely see the value of having these libraries baked into the platform. We'll evaluate adding them, ideally by getting them into the Amazon Linux repositories.

**Comment by ScottHull** [comment]
AWS Support directed me to this issue via my request:

> Elastic Beanstalk doesn't seem to support Django 3.0 because Elastic Beanstalk is pulling an outdated depricated argparse Python library.  This is critically important to fix.  Any insight on this? Relevant forum post: https://forums.aws.amazon.com/thread.jspa?messageID=920667

Leaving this comment here to make sure it is captured.  I am using GeoDjango as well (and installing the required libraries to EB via .config files was an extremely difficult task, so +1 for the original issue), so it could be that the `argparse` library issue is fundamentally tied into GeoDjango.

**Comment by mnmkt** [comment]
Could you make Django 2.2 for EB Python 3.6 platform as well?
Current latest compatible version is Django 2.1 but Python 3.6 itself is compatible with Django 2.2.
https://docs.djangoproject.com/en/2.1/faq/install/#what-python-version-can-i-use-with-django

**Comment by cheng-liven** [comment]
> Could you support Django 2.2 for EB Python 3.6 platform as well?
> Current latest compatible version is Django 2.1 but Python 3.6 itself is compatible with Django 2.2.
> https://docs.djangoproject.com/en/2.1/faq/install/#what-python-version-can-i-use-with-django

There is no issue to run the core Django 2.2 or 3.0  (no GIS features)on the current Python 3.6 environments.

**Comment by jjadta** [comment]
Reopening.  Inadvertently closed when removing the Proposed tag.

**Comment by cheng-liven** [comment]
Recommended versions of libraries that supported by Django 2.2 LTS ~ Django 3.2 LTS (All Django versions currently receive official updates):

[GEOS](https://trac.osgeo.org/geos/): v3.7.x
[PROJ](https://proj.org/): v5.2.x
[GDAL](https://gdal.org/): v2.3.x

**Comment by cheng-liven** [comment]
The same issues raised more than 5 years ago:
https://forums.aws.amazon.com/thread.jspa?messageID=677038

**Comment by ScottHull** [comment]
@cheng-liven @Sekhar-Kutikuppala Confused on why this was closed.  Was hoping for AWS EB to support Django fully...will this not happen?

**Comment by theamanbhargava** [comment]
Are there any updates on Django 3.x support in EB?
