### ISSUE TITLE
Tomcat 8.5/9 with Corretto 17

### ISSUE THREAD

**Issue by lisenet** [aws/elastic-beanstalk-roadmap#285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
We need Corretto with Tomcat and Java 17. Tomcat version can be either 8.5 or 9, we can accommodate both.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)? Tomcat

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Upgrading from an older version of Java to Java 17 for security reasons.

**Are you currently working around this issue?**
No. This is currently blocking our migration path from an older version of Java to Java 17.

**Comment by praegt** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-10-19-al2023.html
