### ISSUE TITLE
Support RDS storage types

### ISSUE THREAD

**Issue by dannosaur** [aws/elastic-beanstalk-roadmap#29]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support the ability to provision RDS instances with storage types other than magnetic, and other properties such as monitoring.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?
No

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It would be nice if there was more support for provisioning RDS instances with more advanced properties than currently available. While not impossible, it just adds a layer of inconvenience to using the platform.

**Are you currently working around this issue?**
Provisioning an RDS instance via an environment, then manually modifying the created RDS instance with the desired properties.

**Additional context**
Also, the link for the RDS instance in the "Configuration" tab doesn't work anymore since RDS's console changed to the new design. It no longer filters the console to the instance listed. It would probably make more sense that it takes you to the instance overview page, rather than the list view anyway.

**Comment by pprahlad** [comment]
Thanks for this feedback. We are evaluating this to see if we can support this.

**Comment by jsheld** [comment]
We will look at the link from the configuration card on the EB console to RDS to ensure that works as expected. Thank you for making us aware of this issue.
