### ISSUE TITLE
Elastic Beanstalk Config & RDS DB Engine Version Validation Error

### ISSUE THREAD

**Issue by escully27** [aws/elastic-beanstalk-roadmap#291]
I'm continually see the following error while trying to edit any of my EB's configuration settings. When I go to edit the DB section of the EB configuration, this error blocks the form from loading properly. It's apparently impossible to alter this value manually.

```
Configuration validation exception: Invalid option value: '12.8' (Namespace: 'aws:rds:dbinstance', OptionName: 'DBEngineVersion'): Engine Version 12.8 not supported for postgres db
```

![Screenshot 2023-06-26 at 2 06 43 PM](https://github.com/aws/elastic-beanstalk-roadmap/assets/11113163/e97ff456-73f9-48a4-a1c5-f9e8c1062375)

I've tried to edit the EB config in via AWS cli but I get the following error.

`ERROR: ServiceError - Configuration validation exception: RDS DB Engine Version option setting is not allowed to changed`

![Screenshot 2023-06-26 at 2 09 37 PM](https://github.com/aws/elastic-beanstalk-roadmap/assets/11113163/4abd07ad-3ccb-47be-93b2-4b29bab3e524)

There's also a fun typo in the error message :)

I'd really prefer to not have to rebuild our entire environment. I also get the first error when I try to clone the EB.

Is this because our DB was restored from a previous snapshot and upgraded engine version to 12.11 - somehow the EB value for this did not update correctly.

**Comment by mamboitaliano21** [comment]
Facing the same issue as well. Any solution to this?

**Comment by escully27** [comment]
Had to rebuild a new environment and gave access to the previous DB through the Environment properties. Had to update a bunch of our packages and such because the only allow elastic beanstalk options are all newer than our existing project. Sorry, it seems the only way forward is biting the bullet and launching a new environment.


![Screenshot 2023-07-06 at 11 04 52 AM](https://github.com/aws/elastic-beanstalk-roadmap/assets/11113163/0f32bb81-1f26-4580-94e8-0811e5da9490)

**Comment by GarrisonD** [comment]
Faced it today... Don't want to rebuild the environment too 😞

**Comment by GarrisonD** [comment]
@escully27 Why did you close the issue? It's still the bug.

**Comment by GarrisonD** [comment]
I tried to decouple an RDS instance like:

```yml
aws:rds:dbinstance:
    HasCoupledDatabase: 'false'
```

 and here is the error I got:

```
ERROR: ServiceError - Configuration validation exception: Invalid option value: '******' (Namespace: 'aws:rds:dbinstance', OptionName: 'DBPassword'): DB password length for MySQL DB should not be more than 41 characters
```

and made no sense at all. At least because I am using PostgreSQL 😄

I could make it work with a dummy value for `DBPassword`:

```yml
aws:rds:dbinstance:
    DBPassword: 'test12345678'
    HasCoupledDatabase: 'false'
```

No password was changed on the RDS instance 👌
