### ISSUE TITLE
Support Corretto 21 on Java SE platform

### ISSUE THREAD

**Issue by marceloverdijk** [aws/elastic-beanstalk-roadmap#301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Support Corretto 21 on Java SE platform.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Yes, this is specific to the Java SE platform.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Upgrade to Corretto 21 to use latest Java 21 features.

**Are you currently working around this issue?**
Using older Corretto 17 version instead.

**Additional context**
N/A

**Attachments**
N/A

**Comment by ahoehma** [comment]
Any news here?

**Comment by ahoehma** [comment]
Is there any chance to get java 21 support in beanstalk?

**Comment by cabilash0** [comment]
EB added Java21 support on 25th Jan 2024

**Comment by c-a-m** [comment]
Is there anything we as a community can help to move this along.  There shouldn't be a suprise here.  No one is saying "Whoa, they released another LTS java! Didn't see that coming!"  It took 11 months to support java 17 in beanstalk after it's release.  So by that metric, 21 should be released in August, but it doesn't even look like its on the roadmap according to this: https://github.com/aws/elastic-beanstalk-roadmap/projects/1#card-71296827

**Comment by praegt** [comment]
Corretto 21 on AL2023 is supported on Elastic Beanstalk as of 2024-01-25: https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2024-01-25-al2023.html
