### ISSUE TITLE
AWS AL2 - Elastic beanstalk - how can I proper install Postgres 15?

### ISSUE THREAD

**Issue by emish89** [aws/elastic-beanstalk-roadmap#302]
I have an Elastic Beanstalk enviroment with AL2 system (latest available) and until today, I used `amazon-linux-extras` to install PG 14 with this command:

`sudo amazon-linux-extras install postgresql14
`
Now I want to update to postgresql15 but seems that `amazon-linux-extras` is not providing it for AL2 (seems providing it for AL2023, for AL2 only PG 11, 12, 13, 14) . Or, I can't find the way to enable it.

So I'm here to ask if someone knows a way to properly install postgresql15 on AL2 enviroment.

Thanks a lot for all the info and the help

**Comment by timsinakiran** [comment]
I switched to AL2023. It's easier to use AL2023 due to dnf. The AL2023.2 is pretty solid.

**Comment by emish89** [comment]
> I switched to AL2023. It's easier to use AL2023 due to dnf. The AL2023.2 is pretty solid.

@timsinakiran sadly is not available in beanstalk for ruby. Last available version is AL2

**Comment by emish89** [comment]
I don't know if this thread helped but now is available AL2023 for ruby on beanstalk :) 
@timsinakiran
