### ISSUE TITLE
Deploying multiple Java applications in a single Elastic Beanstalk Instance in Asia Pacific (Mumbai) region   ap-south-1 

### ISSUE THREAD

**Issue by vaquarkhan** [aws/elastic-beanstalk-roadmap#31]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

Yes , Deploying multiple Java applications in a single Elastic Beanstalk Instance in Asia Pacific (Mumbai) region ap-south-1 , its not available in ap-south-1  

**Are you currently working around this issue?**
No

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by richardhboyd** [comment]
@vaquarkhan can you fill in the answers to the questions, it looks like you left the template responses in the feature request.

**Comment by jsheld** [comment]
Not enough information in this post to investigate any potential issue. Also, this is a good candidate for a support-related request.
