### ISSUE TITLE
.Net 8 on Linux Support

### ISSUE THREAD

**Issue by AndrewMutation** [aws/elastic-beanstalk-roadmap#311]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Support .Net 8 on Linux in Elastic Beanstalk

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

[.NET Core on Linux](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.dotnetlinux)

**Comment by aswanevelder** [comment]
The issue regarding .Net 7 since release a year ago had no response, doubt this is being maintained anymore. I was very hopeful given that .Net 8 is LTS, but I honestly have given up on this ever being updated.

https://github.com/aws/elastic-beanstalk-roadmap/issues/266

**Comment by AndrewMutation** [comment]
I was following the  266 for a while, ended up using the .Net install script to get 7 running.

"doubt this is being maintained anymore."
This roadmap or .Net on Elastic Beanstalk.

I needed v7 for something in-house, but if they aren't serious about direct support for .Net, its quite disappointing.

**Comment by aswanevelder** [comment]
Today I finally managed to do this with Docker, which seems to be the only way going forward. I am too very disappointed, I absolutely love AWS but it would probably have been a lot easier on Azure. I'll post a video in the next few days if anyone is interested how to run Dotnet 8 with Docker on EB.

**Comment by AndrewMutation** [comment]
I had started the in-house project using docker on EB, but was having issues so we switched to running it directly on EB and it was a lot simpler.

**Comment by kumail-talverse** [comment]
Make it done ASAP!!

**Comment by kumail-raza** [comment]
@aswanevelder  waiting for one, I was planning to do the same with Docker & ECS/Fargate to achieve this, but that is an extra work.

**Comment by kumail-raza** [comment]
It should be done by now, ASAP

**Comment by thackerdynasty** [comment]
docker is so finicky this needs to be done

**Comment by MrDark** [comment]
.NET on Windows Server already support .NET 8 since December 5th 2023.

**Comment by rajancstack** [comment]
when will this be supported?

**Comment by sunilshahi** [comment]
Any updates or plans on this?

**Comment by ardahal7** [comment]
Any updates on this?

**Comment by gurunath-kalburgi** [comment]
Any updates on this?

**Comment by gabaoalb** [comment]
.NET Core 6 goes EOL in November of this year, we have more 5 months of support for Microsoft, i would like to start the migration to .NET Core 8

**Comment by sunilshahi** [comment]
The end of support for .NET 7 is on May 14, 2024. Its was STS release. I think there is no point in adding support for .NET 7 after official support has ended. 

Since .NET 8 is LTS and majority of people waiting for #266 would equally benefit from this, can we skip adding support for .NET 7 and prioritize this instead? #266 has around 71 upvotes at the time of writing this comment.  Please consider "merging" upvotes for these two tickets and plan accordingly.

**Comment by AndrewMutation** [comment]
At this point, I don't think anything is going to happen with this.

I haven't seen any responses to this or to #266 that seem to be from Amazon, so its either docker or install the runtime yourself

**Comment by MrDark** [comment]
We have switched to publishing our apps with self-contained enabled. It makes the artefact larger but alleviates the dependency of having a pre-installed runtime.

**Comment by aswanevelder** [comment]
I believe this is a lost cause, Docker seems to be the only plausible way forward, self-contained makes the deployment too bulky.

**Comment by edvanr** [comment]
> We have switched to publishing our apps with self-contained enabled. It makes the artefact larger but alleviates the dependency of having a pre-installed runtime.

Does this actually work? Could you post some more details?

I remember trying this over 12 months ago but didn't have any luck getting it working

**Comment by MrDark** [comment]
> > We have switched to publishing our apps with self-contained enabled. It makes the artefact larger but alleviates the dependency of having a pre-installed runtime.
> 
> Does this actually work? Could you post some more details?
> 
> I remember trying this over 12 months ago but didn't have any luck getting it working

Within our (Azure) pipeline, we run the `dotnet publish` command with arguments `--runtime linux-x64 --self-contained true`. The output artefact is then directly used in the CDK when deploying to AWS.

**Comment by tecnocrata** [comment]
Is this what you are looking for? https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-12-05-windows.html

**Comment by edvanr** [comment]
> > > We have switched to publishing our apps with self-contained enabled. It makes the artefact larger but alleviates the dependency of having a pre-installed runtime.
> > 
> > 
> > Does this actually work? Could you post some more details?
> > I remember trying this over 12 months ago but didn't have any luck getting it working
> 
> Within our (Azure) pipeline, we run the `dotnet publish` command with arguments `--runtime linux-x64 --self-contained true`. The output artefact is then directly used in the CDK when deploying to AWS.

This is great thanks for sharing. In case anyone else has problems with this, we could not get the binary to run on the `64bit Amazon Linux 2 v2.6.4 running .NET Core` Beanstalk instance. After a bit of digging and testing, we worked out that we needed to build it for `linux-arm64` not `linux-x64`

**Comment by praegt** [comment]
Elastic Beanstalk now supports .NET 8 on Amazon Linux 2023
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2024-05-17-al2023NET8.html

**Comment by praegt** [comment]
.NET 8 is now available on the .NET Core on Amazon Linux 2 platform
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2024-07-18-al2.html
