### ISSUE TITLE
Support updating tags via CloudFormation without a replacement

### ISSUE THREAD

**Issue by benbridts** [aws/elastic-beanstalk-roadmap#32]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
ElasticBeanstalk replaces the environment when updating the Tags via CloudFormation. It would be nice if it behaved like the console/api and could do this without a full replacement.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
no

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When managing environments infrastructure as code is a must, the current implementation makes it very cumbersome to change tags of you do that.

**Additional context**
see also https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/155

**Comment by jjadta** [comment]
This change is under review by CloudFormation for implementation.

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/155

We will close this issue once CloudFormation closes out the above issue.

**Comment by jsheld** [comment]
Closing this issue as it is being tracked by CFN per the previous comment. Please refer to CFN roadmap for progress on resolving this issue.

**Comment by benbridts** [comment]
@jjadta @jsheld Can you find out why this isn't moving forward on the CloudFormation roadmap?
