### ISSUE TITLE
Tomcat 10.1 with Corretto 21

### ISSUE THREAD

**Issue by JulB310** [aws/elastic-beanstalk-roadmap#329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
We need to have platform "Tomcat 10 + Corretto 21 on AL2023".
Today, only "Corretto 21" or "Tomcat 10 + Corretto 17 on AL2023" are available.
Corretto 21 is out on Sep 21, 2023

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Platform Tomcat 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Want a new stack with the last versions of Java 21 (Corretto).

**Are you currently working around this issue?**
No

**Comment by praegt** [comment]
Elastic Beanstalk now supports Corretto 21 with Tomcat 10.1 on Amazon Linux 2023
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2024-07-03-al2023.html
