### ISSUE TITLE
Ruby apps should set APP_ENV

### ISSUE THREAD

**Issue by stefansundin** [aws/elastic-beanstalk-roadmap#34]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
The Ruby community has decided that `RACK_ENV` and `RAILS_ENV` are complicated to use (and used incorrectly a lot). So they decided to add `APP_ENV`, the one variable to rule them all.

Elastic Beanstalk is setting `RACK_ENV=production` as a default for new Ruby apps. It should start setting `APP_ENV=production` as well.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Ruby

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
It's not hard to set new variables, but better defaults would make things easier for newbies.

**Are you currently working around this issue?**
I set `APP_ENV=production` manually after creating an app.

**Additional context**
- https://github.com/rack/rack/blob/d0218ed43eb4f47bfba614b4671577142dbdbad0/lib/rack/server.rb#L182-L187
- https://github.com/sinatra/sinatra/blob/a4dd24add24f2dd0e7299b9e68e12038138294d3/README.md#environments
- https://github.com/sinatra/sinatra/pull/984

In addition, `RACK_ENV=production` is not an intended value (as seen in the rack code linked above). It has always been intended to be set to either `development`, `deployment`, or `none`. Unfortunately, Heroku and other websites have been telling Ruby developers to set `RACK_ENV` and `RAILS_ENV` to the same value, so this mistake is very common. For `APP_ENV`, they allow `production` and other values.

I think the default `RACK_ENV` value should be changed to `deployment`. This may have some backwards compatibility concerns, but it is the proper value. One way to deal with this is to also start setting `RAILS_ENV=production` which should fix this concern for Rails developers.

I also think it would be nice if there was a better way to set default environment variables through `.ebextensions` somehow. Something like Heroku lets you do via an `app.json` file ([example](https://github.com/stefansundin/rssbox/blob/84d1dfaa2d1c69a875cfd81fc4d7247b36529c6c/app.json#L17-L51)).

Thanks!

**Comment by labisso** [comment]
Thanks for the suggestion @stefansundin! I think we can do this with fewer backwards-compatibility concerns in our upcoming AL2-based Ruby platform. Changing it in our existing platform needs some more research though.

**Comment by jjadta** [comment]
Reopening.  Inadvertently closed when removing the Proposed tag.

**Comment by 1tonyca** [comment]
Closing older issue that we are no longer considering, please do re-open if this is still relevant.
