### ISSUE TITLE
[Bug] - Building wheels for collected packages fails with "cannot open linker script file"

### ISSUE THREAD

**Issue by DanielCBezerra** [aws/elastic-beanstalk-roadmap#341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

Moving this issue from [amazon-linux-2023](https://github.com/amazonlinux/amazon-linux-2023/issues/814), as they said this is likely a problem with Elastic Beanstalk build, and not with AL2023.

**Describe the bug**
Deploying a Python project on Elastic Beanstalk, running the new version "Python 3.12 running on 64bit Amazon Linux 2023/4.2.0", with the following packages in the requirements.txt:
```
libsass >= 0.23.0, < 1.0.0
psycopg2 >= 2.9.9, < 3.0.0
```

Results with the following errors:
```
/usr/bin/ld: cannot open linker script file /root/rpmbuild/BUILD/Python-3.12.7/.package_note-python3.12-3.12.7-1.amzn2023.aarch64.ld: No such file or directory
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/g++' failed with exit code 1
```

**To Reproduce**
Easy to reproduce just opening the instance console and doing a:
`pip install psycopg2`

**Expected behavior**
Should install as always did on old versions.

**Comment by NaimShaqqou** [comment]
Thank you for bringing this to our attention. We were able to replicate this error and are working on a fix.

**Comment by kxsph** [comment]
Hi NaimShaqqou - please let me know if you have any update on this issue. I have the same error message when running "pip3 install rpy2". I am able to install it with python 3.11 but not python 3.12.

**Comment by NaimShaqqou** [comment]
Hi, we have a fix for this issue that will be included in the upcoming AL2023 platform release.

**Comment by kxsph** [comment]
Excellent, thank you. For now I have built python 3.12 RPM on the Amazon Linux 2023 instance in order to create the linker file: /root/rpmbuild/BUILD/Python-3.12.7/.package_note-python3.12-3.12.7-1.amzn2023.x86_64.ld. I then copy it onto the instance as part of my .ebextensions scripts. That seems to be a workaround for now.

**Comment by NaimShaqqou** [comment]
This issue was fixed in our latest AL2023 Platform release: https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2024-11-08-al2023.html
