### ISSUE TITLE
Elastic Beanstalk support for IMDSv2

### ISSUE THREAD

**Issue by adrienpessu** [aws/elastic-beanstalk-roadmap#39]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

I want to be able to activate IMDSv2 on Elastic Beanstalk EC2 instances with `.ebextensions` 

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

IMDSv2 is available for Ec2 instances but not for Elastic Beanstalk

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

I want Elastic Beanstalk instances to be safe from SSRF using Metadata HTTP API.

**Are you currently working around this issue?**
How are you currently solving this problem?

I solve this in my code.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by Sekhar-Kutikuppala** [comment]
AWS Elastic Beanstalk now supports IMDSv2
[Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-06-10-imdsv2.html)
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-elastic-beanstalk-adds-support-for-imdsv2-and-service-linked-role-for-managed-updates/)
