### ISSUE TITLE
Managed Platform Updates are failing

### ISSUE THREAD

**Issue by aws-sidhartha** [aws/elastic-beanstalk-roadmap#41]
Community Note

    Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request.
    Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

Description:
When users attempt to run managed updates in ElasticBeanstalk environment they are seeing the following error:

=============
Service:AmazonCloudFormation, Message:Template error: instance of Fn::GetAtt references undefined resource AWSEBSecurityGroup.
=============

Cause: 
When users run the managed platform update, by default ElasticBeanstalk uses "Immutable updates" with spot instances/custom VPC settings enabled. 

Workarounds: 
> If the environment is created using launch template, the workaround for this problem is to use "On-demand" instances and relaunching the environment with the same application version.

> If the environment is created using launch configuration, the workaround would be to use "on-demand" no need of relaunching the environment.

**Comment by jjadta** [comment]
Fixed as of June 7th.  Closing
