### ISSUE TITLE
Elastic Beanstalk Health daemon ignores 4xx errors from Application Load Balancer

### ISSUE THREAD

**Issue by pprahlad** [aws/elastic-beanstalk-roadmap#46]
Customers can instruct Elastic Beanstalk to ignore 4xx errors that may be thrown by the ALB if you had WAF enabled, for example. This will reduce the false positives from Elastic Beanstalk health checks.

**Comment by pprahlad** [comment]
This is now released. https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-04-20-health-rules.html

**Comment by jjadta** [comment]
Additional documentation on this feature can be found here:

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced-rules.html
