### ISSUE TITLE
Java/Docker Platform Environment Update Issue

### ISSUE THREAD

**Issue by s-stefanov** [aws/elastic-beanstalk-roadmap#48]
### I think it's really high priority and it's blocking us from maintaining our environment 
[https://forums.aws.amazon.com/thread.jspa?threadID=315451](https://forums.aws.amazon.com/thread.jspa?threadID=315451)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
For Java and Docker platforms, there is an issue with updating or creating environment variables after the first creation of the environment

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Yes, `eu-central-1`

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want to add/update a variable in Java/Docker platforms. This is currently not possible and gives us an error.

**Are you currently working around this issue?**
Using the AWS Console and and EBS CLI `eb setenv`

**Additional context**
You can check this forum thread for additional information [https://forums.aws.amazon.com/thread.jspa?threadID=315451](https://forums.aws.amazon.com/thread.jspa?threadID=315451)

**Attachments**
Above ^^ If you need anything else, I'm open for including them from our environment

**Comment by jjadta** [comment]
Thank you for submitting this issue.  We are reviewing it.

**Comment by Sekhar-Kutikuppala** [comment]
This issue is addressed in the latest Corretto platforms v3.1.1
