### ISSUE TITLE
PHP 7.4 on Amazon Linux 2 platform (BETA)

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#5]
PHP 7.4 is now included with Amazon Linux 2 (big thanks to the AL team!). We're planning to include support for it in our upcoming PHP Amazon Linux 2 beta platform.

**Comment by Erveon** [comment]
This would be great to have

**Comment by kusiu** [comment]
When can we get action this?

**Comment by crocLeMonde** [comment]
@labisso do you have any idea about when this should be released ?

**Comment by labisso** [comment]
@crocLeMonde we're working hard on this platform right now and expect it to be available (in beta) in a few weeks

**Comment by brysem** [comment]
> @crocLeMonde we're working hard on this platform right now and expect it to be available (in beta) in a few weeks

That's great news! Can't wait.

**Comment by tattali** [comment]
Hi @labisso, if we create an environment with BETA php 7.4 AMI 2.
When the final version is released, will the migration be automated?

Thanks

**Comment by Sekhar-Kutikuppala** [comment]
Hi @tattali - The Beta platforms are not recommended for production use and the GA PHP 7.4 on AL2 platforms will have a major version. Hence Managed updates won't perform the migration from Beta platform to GA platform. However, if you are already testing the Beta platform then you can perform an in place update (from Beta platform to GA platform) by calling Elastic Beanstalk 
[update environment call](https://docs.aws.amazon.com/cli/latest/reference/elasticbeanstalk/update-environment.html)

**Comment by Sekhar-Kutikuppala** [comment]
PHP on AL2 platform is now generally available
[Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-04-30-al2.html)
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/04/aws-elastic-beanstalk-announces-general-availability-of-amazon-linux-2-based-node-js-php-go-and-ruby-platforms/)
