### ISSUE TITLE
Add support for Spot Instance "interruption notice"

### ISSUE THREAD

**Issue by uldall** [aws/elastic-beanstalk-roadmap#50]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Add support for Spot Instance "interruption notice" by automatically launching a new instance (on-demand or spot) when the notice is received instead of waiting until the instance has already been shut down.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
No.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
This would make it possible to have an Elastic Beanstalk environment with all Spot instances and not worry about them all being shut down at the same time. 

**Are you currently working around this issue?**
Currently we have to set a minimum of 1 on-demand instance to make sure that we don't end up with no instances in an environment.

**Additional context**
Nothing.

**Attachments**
No attachments.

**Comment by candrews** [comment]
I believe that you're looking for Capacity Rebalancing - see https://github.com/aws/elastic-beanstalk-roadmap/issues/123

**Comment by uldall** [comment]
Yes, that is exactly it :)

**Comment by snnles** [comment]
Similar to issue #123 

What's New post for launch: https://aws.amazon.com/about-aws/whats-new/2021/08/aws-elastic-beanstalk-capacity-rebalancing-amazon-ec2-spot-instances/
