### ISSUE TITLE
Apache support on AL2 platforms

### ISSUE THREAD

**Issue by vikashsp** [aws/elastic-beanstalk-roadmap#53]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build? 
Current application is running on apache and using the old version of elastic beanstalk. It doesn't support ngnix. So not working properly for the latest platform.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?
PHP Laravel
**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

**Are you currently working around this issue?**
How are you currently solving this problem?
We need to make our code compatible to ngnix if apache will never work on the latest elastic beanstalk platform

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by rennokki** [comment]
Hey @vikashsp, I do work with Laravel applications and actively deploy them on production using Elastic Beanstalk. I can tell from my experience that Laravel works well with NGINX.

I might wonder what your custom needs would you require that makes your Laravel apps incompatible with Apache? 🤔

**Comment by Sekhar-Kutikuppala** [comment]
We are working on adding Apache to following AL2 based platforms
Java with Tomcat
PHP
Node.js
Python

**Comment by jjadta** [comment]
Closed by mistake.  Reopening.

**Comment by Sekhar-Kutikuppala** [comment]
Elastic Beanstalk now supports Apache in AL2 based PHP, Node.js, Java with Tomcat, and Python platforms. For more details, see [Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-08-04-al2.html)

**Comment by dave-irvine** [comment]
@Sekhar-Kutikuppala I think there are some issues with the implementation for PHP. If you deploy the test application, the PHP files are not interpreted and just print PHP source to the browser.
