### ISSUE TITLE
Bug in Elastic Beanstalk Managed Platform Update when used spot-based instances

### ISSUE THREAD

**Issue by mogilp** [aws/elastic-beanstalk-roadmap#54]
Elastic Beanstalk Managed Platform Update creates an extra autoscaling group and leave it running with extra instances in an environment when used spot-based instances (on-demand instances works without any issue)

Please look into this..

**Comment by dnorth98** [comment]
I ran into exactly the same issue a few weeks ago and opened a support case for this.  After several support engineers, I was told it's a "known issue" so believe it's being worked on.

**Comment by dgagnon** [comment]
The left over instances are cause by your immutable deployement policy, it is the expected behavior as per the doc.

The support guys were telling me that the issue with spot instance is only for immutable deployement, but I never used it.  I can now use spot instance fine.

**Comment by dnorth98** [comment]
> The left over instances are cause by your immutable deployement policy, it is the expected behavior as per the doc.
> 
> The support guys were telling me that the issue with spot instance is only for immutable deployement, but I never used it. I can now use spot instance fine.

That wasn't the case for us - we weren't using immutable deploys.  It was confirmed as an issue by support and actually fixed in July.

**Comment by Sekhar-Kutikuppala** [comment]
We released this fix to all AWS regions where Elastic Beanstalk is available
