### ISSUE TITLE
Traffic Splitting Deployments

### ISSUE THREAD

**Issue by Sekhar-Kutikuppala** [aws/elastic-beanstalk-roadmap#55]
You can now use  the Traffic splitting deployment policy to update an application running in an Elastic Beanstalk web server environment that uses an Application Load Balancer. This deployment policy will enable you to test your new application version under controlled production traffic and also lets you perform Blue/Green type deployments. For more information visit: 
[What's New](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-05-18-ts-deploy.html)
[Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-05-18-ts-deploy.html)

**Comment by manu-sparheld** [comment]
@Sekhar-Kutikuppala Just trying to find out what is maximum time in duration Traffic splitting can be done. Looking in the docs can't find anywhere. Thanks

**Comment by Sekhar-Kutikuppala** [comment]
@manu-sparheld Thank you for the feedback. You can specify Traffic splitting evaluation time between 3 minutes and 600 minutes.

**Comment by manu-sparheld** [comment]
Is it going to be added to AWS beanstalk docs ?

**Comment by Sekhar-Kutikuppala** [comment]
@manu-sparheld It is there in the Elastic Beanstalk developer guide[ Configuring Environments (advanced)](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalktrafficsplitting) section

**Comment by digicase** [comment]
Hello, I have set the evaluation time to 4 minutes, but so far it has taken over 10 minutes since I received this event.

2020-05-29 10:27:39 UTC+0200 | INFO | Traffic-splitting deployment: starting to shift 10% of client traffic to the new application version.
-- | -- | --

Now I'm wondering if something has gone wrong? I'll let it run for another 10 minutes or so but after that I'll have to abort.

**Comment by bruun** [comment]
We have experienced the same issue with the deployment being stuck after "starting to shift 10% of client traffic". The environment we experienced this on was not receiving any traffic on the ALB at the time, I'm not sure if that is something which could cause a problem?

**Comment by bruun** [comment]
> The environment we experienced this on was not receiving any traffic on the ALB at the time, I'm not sure if that is something which could cause a problem when Beanstalk is evaluation the health?

We're testing the same deployment policy in an environment receiving live traffic now, and the process has been stuck at "starting to shift 10% of client traffic to the new application version." for over 20 minutes (the evaluation time is 5 minutes).

The new instances are healthy, and responds to incoming health checks and live traffic. We see no reason why the deployment process isn't proceeding.

**Comment by digicase** [comment]
I switched back to immutable deploys after the first failed attempt. It was a bad situation as after the first abort attempt you are stuck for at least half an hour with no recourse except contacting support. That comes after however long you waited for the traffic test to complete.

**Comment by Sekhar-Kutikuppala** [comment]
> I switched back to immutable deploys after the first failed attempt. It was a bad situation as after the first abort attempt you are stuck for at least half an hour with no recourse except contacting support. That comes after however long you waited for the traffic test to complete.

Hi @digicase  I'm sorry you are facing this issue. I'm from Elastic Beanstalk team and we can help investigate the issue and share our findings. Can you share more details about this issue through email to kutikc@amazon.com

**Comment by Sekhar-Kutikuppala** [comment]
> > The environment we experienced this on was not receiving any traffic on the ALB at the time, I'm not sure if that is something which could cause a problem when Beanstalk is evaluation the health?
> 
> We're testing the same deployment policy in an environment receiving live traffic now, and the process has been stuck at "starting to shift 10% of client traffic to the new application version." for over 20 minutes (the evaluation time is 5 minutes).
> 
> The new instances are healthy, and responds to incoming health checks and live traffic. We see no reason why the deployment process isn't proceeding.

Hi @bruun  I'm sorry you are facing this issue. I'm from Elastic Beanstalk team and we can help investigate the issue and share our findings. Can you share more details about this issue through email to kutikc@amazon.com

**Comment by tahacanatak** [comment]
> We have experienced the same issue with the deployment being stuck after "starting to shift 10% of client traffic". The environment we experienced this on was not receiving any traffic on the ALB at the time, I'm not sure if that is something which could cause a problem when Beanstalk is evaluation the health?
> 
> When aborting the deploy, we get the same problem again:
> 
> ![image](https://user-images.githubusercontent.com/422180/84328847-6a420b00-ab83-11ea-999f-6e6677d42365.png)
> 
> The abort operation will seem stuck for at least 30 minutes, before eventually ending up with the original instances having the error "Incorrect application version".
> 
> Edit:
> 
> After timing out the environment actually still has both the new and old instances:
> 
> ![image](https://user-images.githubusercontent.com/422180/84358426-6cc65400-abc7-11ea-813d-6ad719be6302.png)
> 
> I've tried to do a configuration change on the environment now, and the process is again stuck after the event "Environment update is starting."

i encountered the same problem. Did you solve the cause of the problem ?

**Comment by bruun** [comment]
> i encountered the same problem. Did you solve the cause of the problem ?

Yes, the issue in our case was that we had modified the load balancer in order to redirect HTTP to HTTPS using the following approach: https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/resource-configuration/alb-http-to-https-redirection.config

The resolution for us was to avoid attaching a redirect listener to the ALB.
