### ISSUE TITLE
Support for Pip and Pipenv on Python AL2 platform

### ISSUE THREAD

**Issue by dennishylau** [aws/elastic-beanstalk-roadmap#56]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

Pipenv is problematic, please bring back pip.

While Pipenv provides some nice features, it has serious performance issues. It spawns multiple pip processes every time during `eb deploy`, and chokes up the CPU. This together with slow installation time (relative to good old pip) in turn cause multiple problems.

- Application cannot be deployed onto instance types with less memory such as t3.micro, as Pipenv eats up all its memory during package installation
- Even with enough memory, instances can still become non-responsive and get killed due to extremely high CPU usage
- CPU credits are lost
- CPU-based auto-scaling rules are triggered

Please see the screenshot below. Instances get choked up 50% of the time.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Python

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Please see the above

**Are you currently working around this issue?**
I have no idea how to work around this

**Additional context**
N/A

**Attachments**
<img width="861" alt="Screenshot 2020-05-21 03 26 47" src="https://user-images.githubusercontent.com/30386036/82489909-ffb62600-9b14-11ea-8438-ee4af1f0ecc4.png">

![Screenshot 2020-05-24 00 15 44](https://user-images.githubusercontent.com/30386036/82735381-ef3fbe80-9d53-11ea-9362-f8ab38169777.png)

**Comment by matteing** [comment]
I agree 100%. My deployments have been slowed considerably and I'm looking into moving out of EB.

**Comment by dennishylau** [comment]
Hi @pprahlad @Sekhar-Kutikuppala, do you guys have any work around for this? Appreciate your help, thank you.

**Comment by matteing** [comment]
This has been a huge issue when deploying. For me, some instances just don't deploy without more than 1GB of RAM. I had to change to using pipenv, which is dead slow on local and on server. 

Some just get stuck deploying and never stop.

**Comment by jjadta** [comment]
We are actively looking into this issue ATM.  Thank you for the request.

**Comment by lestersocialcore** [comment]
Please don't remove pipenv. It's a lot better than pip at managing dependencies and I would hate to have to change my deploy steps to put it back in. Shouldn't older dependency managers like pip be only supported on older managed images of Amazon Linux?

**Comment by Sekhar-Kutikuppala** [comment]
Hi @lestersocialcore  We are working to add both pip and pipenv in Elastic Beanstalk Python on AL2 platforms

**Comment by Sekhar-Kutikuppala** [comment]
Python on AL2 platform now supports both pipenv and pip. See more details [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/python-configuration-requirements.html)

**Comment by spawn-guy** [comment]
@Sekhar-Kutikuppala please, have a look at https://github.com/aws/elastic-beanstalk-roadmap/issues/157 😉
