### ISSUE TITLE
Support for a platform retirement status API by environments

### ISSUE THREAD

**Issue by yafroguin** [aws/elastic-beanstalk-roadmap#58]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Support for a Platform retirement status API by environments

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
non specific.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We're running applications by Elastic Beanstalk about 700 or more applications and 1000 or more environments within several AWS accounts. Every environments are operated by our development team. I want to notice to owner developers to change platform version that is already expire with by environment but now I have only one option: Application lists of Elastic Beanstalk Console. How can I get environments that platform had expired with automation options like APIs or CLI?

**Are you currently working around this issue?**
I'm currently working about this issue by email notice, console message, ..etc.

**Additional context**
I received email with inform about platform retirement but not enough to operate this.

**Comment by jsheld** [comment]
I know the ask here is for an API to simply return LifeCycleState based on a single input parameter, but this can be achieved by scripting a solution as follows:

1. Describe your environments using `aws elasticbeanstalk describe-environments`.

In the response that is returned, inspect the PlatformArn.  For example:

arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running on 64bit Amazon Linux/2.7.1

2. Parse this value to extract the branch name, which in this case is  'Python 3.6 running on 64bit Amazon Linux'

3. Run the following command: `aws elasticbeanstalk list-platform-branches --filters 'Attribute=BranchName,Operator=contains,Values=[Python 3.6 running on 64bit Amazon Linux]'`

In this case, the response is as follows:

```{
    "PlatformBranchSummaryList": [
        {
            "PlatformName": "Python",
            "BranchName": "Python 3.6 running on 64bit Amazon Linux",
            "LifecycleState": "Supported",
            "BranchOrder": 10000,
            "SupportedTierList": [
                "WebServer/Standard",
                "Worker/SQS/HTTP"
            ]
        }
    ]
}```

You can extract the lifecycle state in this manner for each of your environments.

If you want to know the lifecycle state for all Python platforms, use the following:

`aws elasticbeanstalk list-platform-branches --filters 'Attribute=PlatformName,Operator=contains,Values=[Python]'`
