### ISSUE TITLE
.NET Core on Amazon Linux 2 platform

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#6]
We are considering building an Elastic Beanstalk platform which allows native support for running .NET Core applications on Amazon Linux 2. Please let us know your interest in this potential platform by reacting with a 👍 on the issue if you want it to be implemented. Additional feedback and comments are also appreciated!

**Comment by yfayerman** [comment]
Will this enable support for worker environments?

**Comment by labisso** [comment]
@yfayerman Most likely - would that be useful for you? Would you prefer that we supported Worker environments on our current Windows platforms, or is there something specific about the combination of Linux, .NET Core, and Worker that you are interested in?

**Comment by yfayerman** [comment]
@labisso yes, it would be useful, and not specifically because of Linux but for any platform where .NET is supported. So if worker environments were supported on the current Windows platform, it would be great.

**Comment by areac0des** [comment]
this would be pretty good..  +1

**Comment by leandroltavares** [comment]
Is there a target date for this? This would be useful, not having to publish a docker container as a work arround.

**Comment by labisso** [comment]
Hi @leandroltavares we're still researching this but expect to start building it very soon. Because security and operational stability are always our highest priority, we can't provide specific target dates for features.

**Comment by pprahlad** [comment]
We are currently designing how to implement this

**Comment by Sekhar-Kutikuppala** [comment]
.NET Core on Linux platform is now available 
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-elastic-beanstalk-announces-net-core-on-linux-platform/)
[Blog post](https://aws.amazon.com/blogs/developer/aws-elastic-beanstalk-adds-net-core-on-linux-platform/)
[Documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-dotnet-core-linux.html)

**Comment by waf** [comment]
I've been following this issue for a while, and am very eager to try this out! From our initial testing, we've unfortunately run into the same bug as these people: https://forums.aws.amazon.com/thread.jspa?threadID=324610 -- not sure if it's on the radar yet. Let me know if there's a more appropriate place to report this issue. Thanks!
