### ISSUE TITLE
Support multi-stage Docker builds in Amazon Linux 2 platform

### ISSUE THREAD

**Issue by bruun** [aws/elastic-beanstalk-roadmap#60]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
The new AL2 platform (version 3.0.1) does not support multi-staged builds with named stages in the Single Docker Platform.
See [Docker documentation for more information](https://docs.docker.com/develop/develop-images/multistage-build/)

The following error occurs today

```
[INFO] Running command /bin/sh -c docker pull <image-id> as <image-name>
[ERROR] "docker pull" requires exactly 1 argument.
```

**Is this request specific to an Elastic Beanstalk [platform]**
Single Container Docker running on Amazon Linux 2

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are currently running on Amazon Linux platform version 2.15.0 using multi-stage builds, and we want to eventually migrate to Amazon Linux 2.

**Are you currently working around this issue?**
We are sticking to Amazon Linux, although at least one workaround has been provided here: https://stackoverflow.com/a/62031810

**Comment by prattcmp** [comment]
+1

**Comment by 1tonyca** [comment]
This is now available, as part of https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-02-03-linux.html
