### ISSUE TITLE
Document log task customization for AL2 platforms

### ISSUE THREAD

**Issue by lbruun** [aws/elastic-beanstalk-roadmap#66]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Log task customization is documented [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.logging.html#health-logs-extend) for AL1 but there's no equivalent documentation for AL2, yet it has clearly changed.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**

No, I think it applies to all AL2 platforms

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Log task customization, for example which log files are included in a Bundle-Logs operation.

**Are you currently working around this issue?**

Not really. It is possible to kinda reverse engineer the AL2 platform and by doing so you'll figure out the functionality has moved.  But we don't want to move to AL2 before this has been documented by Amazon. Relying on one's own reverse engineer analysis doesn't feel comfortable.

**Comment by wlabatey** [comment]
Currently having to do this right now and couldn't agree more. 

There is no mention of if/how the log file customization has changed on EB for platforms based on Amazon Linux 2.

**Comment by pprahlad** [comment]
Thank you for the input. We are looking into this.

**Comment by vgfeit** [comment]
As we have already migrated to the AL2 platform, this has become a real issue for us. 

Does anyone succeeded to make it work even in an undocumented way?

Basically, what we need is to include some files and a folder from /var/log into the zip file, which, I assume, is a pretty common case.

**Comment by wlabatey** [comment]
@vgfeit We've got custom log files in our EB log bundles working by using the following ebextensions config on Amazon Linux 2:

```
files:
  "/opt/elasticbeanstalk/config/private/logtasks/publish/example-logs.conf" :
    mode: "000755"
    owner: root
    group: root
    content: |
      /var/log/*.log
  "/opt/elasticbeanstalk/config/private/logtasks/tail/example-logs.conf" :
    mode: "000755"
    owner: root
    group: root
    content: |
      /var/log/ee/*.log
  "/opt/elasticbeanstalk/config/private/logtasks/bundle/example-logs.conf" :
    mode: "000755"
    owner: root
    group: root
    content: |
      /var/log/*.log
```

**Comment by wlabatey** [comment]
Just a follow up to say the above config was working for us initially but it looks like it no longer does unfortunately.

**Comment by dankhen** [comment]
As @pprahlad pointed out above, the Elastic Beanstalk team is looking into all AL2 incompatibilities. When we have the information, we'll definitely update the documentation. Thanks for your patience!

**Comment by standady** [comment]
Just as a heads up - I spent hours pulling out hairs from my already bald head trying to figure this out. It is painful when I do my due diligence reading the doc only to find out through some obscure googling that the documentation was not updated.
 
I appreciate all the effort that went into the new platform though!

**Comment by Sekhar-Kutikuppala** [comment]
We addressed this issue in the latest AL2 platforms. For latest AL2 platform versions, see [Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-08-04-al2.html)
