### ISSUE TITLE
Support version 1.18 of NGINX

### ISSUE THREAD

**Issue by rupertbrowning** [aws/elastic-beanstalk-roadmap#67]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?

Support NGINX 1.18: https://www.nginx.com/blog/nginx-1-18-1-19-released/
Using version 1.16.1 is causing our penetration tests to fail with High Priority issues.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?

Node.js

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Using version 1.16.1 is causing our penetration tests to fail with High Priority issues.

**Are you currently working around this issue?**
How are you currently solving this problem?

N/A

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by pprahlad** [comment]
Thank you for the feedback. We are evaluating this request.

**Comment by Sekhar-Kutikuppala** [comment]
Elastic Beanstalk now supports nginx 1.18. For more details, see [Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-08-04-al2.html)
