### ISSUE TITLE
Elastic Beanstalk web server metrics percentile is not a statistical standard definition.

### ISSUE THREAD

**Issue by Houx2001** [aws/elastic-beanstalk-roadmap#69]
- About cloudwatch, a percentile indicates the relative standing of a value in a dataset. For example, the 95th percentile means that 95 percent of the data is lower than this value and 5 percent of the data is higher than this value. Percentiles help you get a better understanding of the distribution of your metric data. Cloudwatch percentile definition is a standard statistical term.

- But about Elastic Beanstalk, a percentile indicates average latency for the slowest x percent of requests over the last 10 seconds. Elastic Beanstalk percentile definition is not a standard statistical term, because the value is average latency not actual latency.

**Comment by jjadta** [comment]
Thank you for your feedback.
