### ISSUE TITLE
Tomcat on Amazon Linux 2 platform

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#7]
We're working on building out this and other platforms on top of Amazon Linux 2 (AL2). With our AL2 platforms, we are refreshing and rethinking each platform based on feedback we’ve gotten from customers. If you have any questions or suggestions for this platform, please add a comment in the issue.

**Comment by mtoftum** [comment]
I'm very interested to see where this is going as I'm about to go through the upgrade of a bunch of Tomcat 8 to 8.5 after the EOL notice we got. If this isn't too far down the road, it might prove a better target than the current 8.5 on AL1. 
Apart from it being AL2, can you say which tomcat versions will be available?

**Comment by labisso** [comment]
@mtoftum yes we plan to support both Tomcat 7 and Tomcat 8.5 in our AL2 platforms

**Comment by mtoftum** [comment]
@labisso 8.5 is what I need, so that's perfect.

**Comment by johnthuss** [comment]
Please change the "JVM options" text field into a larger (resizable) textarea element so that it can actually be edited on the page without having to copy it to another editor to modify.

**Comment by Sekhar-Kutikuppala** [comment]
Corretto with Tomcat on Amazon Linux 2 platforms are now available
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-elastic-beanstalk-announces-general-availability-of-amazon-linux-2-based-tomcat-platforms/)
[Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-06-03-al2.html)

**Comment by matsuhs** [comment]
Any plan to release open Java with Tomcat on AL2 (e.g. Java 8 with Tomcat 8.5 AL2 ver. 4.0.0)  or only support Corretto as a runtime?
