### ISSUE TITLE
Basic environment tier without ELB or SQS

### ISSUE THREAD

**Issue by ggregoire** [aws/elastic-beanstalk-roadmap#70]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

There are currently 2 environment tiers: **web server environment tier** with ELB and **worker environment tier** with SQS. None of them are a good fit for a program that doesn't need a web server or a queue.

It would be great to have a new **basic environment tier** that just provides all the features of Elastic Beanstalk (pre configured platforms, applications versioning, applications multi environments (dev, test, staging, prod…), cloning, auto scaling, logs, health, monitoring, alarms, etc) without ELB or SQS.

**How are you currently solving this problem?**

I'm using EC2.

**Comment by Yuki-Inoue** [comment]
It would be good fit if we are trying to deploy e.g. Rails sidekiq workers (a framework which has its own queue-ish structure)

**Comment by jjadta** [comment]
Creating a single-instance environment (web-tier) should meet your criteria.

**Comment by jjadta** [comment]
Closing.  Please feel free to re-open if this does not address your issue.
