### ISSUE TITLE
Tracking Issue: Support for /opt/elasticbeanstalk/bin/get-config on AL2 platforms

### ISSUE THREAD

**Issue by shalen-n** [aws/elastic-beanstalk-roadmap#76]
The `get-config` command is currently not yet supported for Amazon Linux 2 platforms.

From [111](https://github.com/awsdocs/elastic-beanstalk-samples/issues/111) it appears that the Beanstalk Team is aware of the issue and is tracking it internally. Additionally, it seems that they are currently working on an implementation and are intent on releasing it in an upcoming AL2 platform update however there is no specific timeline/ETA.

This issue has been created for improved visibility/tracking purposes on the issue and for when the implementation of the `get-config` command is rolled out.

**Comment by Sekhar-Kutikuppala** [comment]
@shalen-n Thank you for creating visibility on this issue. We are working on this

**Comment by Sekhar-Kutikuppala** [comment]
'get-config' script is now supported on AL2 platforms. For more details, see [Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-08-04-al2.html)
