### ISSUE TITLE
EC2 key pair cannot be empty

### ISSUE THREAD

**Issue by cheng-liven** [aws/elastic-beanstalk-roadmap#78]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

On the new EB web console, EC2 key pair (Configuration - Security) cannot be empty once select an option from the dropdown list, therefore you can't remove the keypair after set.

Tested platform: Python 3.6 running on 64bit Amazon Linux/2.9.12

**Comment by jsheld** [comment]
Thank you for bringing this to our attention.  My understanding is that the first time you go into the security card, you are presented with a top-level option that says --Choose a key pair--.  Once you select a key pair, you no longer have the --Choose a key pair-- to deselect it.  This is by design.  The workaround is to cancel your change and then go back into the security card.

**Comment by cheng-liven** [comment]
The key pair cannot be removed if the key pair already deployed, and you can do this on the old EB console.

**Comment by dennis-hh** [comment]
Unfortunately, once you have added a key pair and applied the changes, you can not remove the key pair again. This goes so far that when you manually delete the key pair from ec2 settings, the beanstalk stack can not be updated again. I had to completely rebuild the beanstalk stack, which can't be intended behavior.

**Comment by GreenRaccoon23** [comment]
The EC2 Key Pair cannot be removed with an [ebextension](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html) either. I created an ebextension with the following content, deployed it, and was still able to SSH into the server.
```yaml
option_settings:
    aws:autoscaling:launchconfiguration:
        EC2KeyName: null
```

The EC2 Key Pair **can** be removed by running `eb config` on the command line though. While running `eb config`, a YAML file opens. Find the `EC2KeyName` property and set it to `null`. Example:
```yaml
settings:
    aws:autoscaling:launchconfiguration:
        EC2KeyName: null
```

**Comment by tincho4t** [comment]
You can remove it running `aws elasticbeanstalk update-environment --environment-name $ENV --options-to-remove 'Namespace=aws:autoscaling:launchconfiguration,OptionName=EC2KeyName'` replacing $ENV with your environment name.

**Comment by davidebonavita** [comment]
Just to confirm that to this day it's still not possible to remove a keypair from the new EB web console
