### ISSUE TITLE
Support running multiple containers using Docker Compose in Docker on AL2 platform

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#8]
We're working on building out this and other platforms on top of Amazon Linux 2 (AL2). With our AL2 platforms, we are refreshing and rethinking each platform based on feedback we’ve gotten from customers. If you have any questions or suggestions for this platform, please add a comment in the issue.

**Comment by Sekhar-Kutikuppala** [comment]
We are working on building the Docker Compose feature in existing Docker on AL2 platform that will support running multiple containers. Following the launch of this feature, you can migrate your application running on Multi-Container Docker platform on AL to the Docker on AL2 platform.

**Comment by rubenpurple** [comment]
When do you think it will be ready?
Reggards.

**Comment by Sekhar-Kutikuppala** [comment]
Elastic Beanstalk added support for running multi-container applications in AL2 based Docker platform. Customers running multi-container apps on AL AMI based platform can now migrate their apps to run on AL2 based Docker platform. See more -
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/10/aws-elastic-beanstalk-support-running-multi-container-applications-al2-based-docker-platform/)
[Documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker-multicontainer-migration.html)

**Comment by marin-h** [comment]
Hi y'all, I started working on a project using docker-compose in AL2, and was wondering if there is a way to avoid updating specific docker images, as it was possible in single docker container deploys with the directive Image.Update: false in Dockerrun file.
I have added the question in the forums too, as I am not sure which is the better place to ask this kind of things. 
https://forums.aws.amazon.com/thread.jspa?threadID=332543
