### ISSUE TITLE
PHP v7.4 Missing Extensions

### ISSUE THREAD

**Issue by leobewater** [aws/elastic-beanstalk-roadmap#82]
With the new AWS Linus2 for PHP v7.4 and it's missing the following extensions by default. It would be nice to have them by default.

wddx
apcu
igbinary
imagick
memcache
OAuth
ssh2
memcached

**Comment by Sekhar-Kutikuppala** [comment]
Thank you for the feedback. We are reviewing this issue

**Comment by ghost** [comment]
Hi , Thanks for working on this. Is there any tentative timeline when this could be launched ?

**Comment by 1tonyca** [comment]
@neerajklite , the release is progress, would likely be done by end of next week or sooner. Please note imagick and wddx would not be part of the release

**Comment by ghost** [comment]
Thank you @1tonyca . I am specifically in need of the imagick extention. Could it be included in the php8 support which is due release also according to issue [php8 support](https://github.com/aws/elastic-beanstalk-roadmap/issues/131)

**Comment by dejagersh** [comment]
> Hi , Thanks for working on this. Is there any tentative timeline when this could be launched ?

 You can use a file in `.ebextensions` to install PECL extensions manually:

```
---
commands:
  01_install_redis_php_extension:
    command: "yum -y install php-pecl-redis"
```

**Comment by 1tonyca** [comment]
@neerajklite , unfortunately imagick did not pass its unit tests, hence not meeting the bar to be included for php8

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-03-31-al2.html

**Comment by atomita** [comment]
The reason imagick doesn't pass unit tests may be because it uses the older packages.

See below for details.
https://forums.aws.amazon.com/thread.jspa?threadID=318062

**Comment by ghost** [comment]
@1tonyca . There are new releases for Imagick. Can we have an update to this issue . Thanks!
