### ISSUE TITLE
Bug: Apache+PHP completely broken on AL2

### ISSUE THREAD

**Issue by nathankurtyka** [aws/elastic-beanstalk-roadmap#83]
The Apache+PHP AL2 configuration doesn't run PHP (it just outputs the PHP file contents).  For example, even the PHP sample application _appears_ to load successfully, but if you view the HTML you can see the PHP source.

Steps to reproduce:

1. Create a new managed platform: PHP 7.4 running on 64bit Amazon Linux 2/3.1.0
2. Choose to deploy the sample application
3. Choose "Configure More Options"
4. Under "Software", change the Proxy to Apache
5. Launch the environment

Then just view the page source of the sample application. I've attached a screenshot of the output.

![image](https://user-images.githubusercontent.com/4063958/90902994-4f69ef00-e39b-11ea-93fa-b7ce254f35a6.png)

**Comment by neerajklite** [comment]
How did this go pass any tests? if there were any

**Comment by neerajklite** [comment]
Whats the status and expected timeframe for this bug to get fixed ? Thanks !!

**Comment by ghost** [comment]
Any updates @Sekhar-Kutikuppala ? Thanks

**Comment by nickweavers** [comment]
I just created a Amazon Linux 2 beanstalk with Apache selected as the web server and the sample app deployed and the web page html showed no raw php code. Also, phpinfo() looked fine and showed 

```
Apache 2.0 Handler | Ian Holsman, Justin Erenkrantz (based on Apache 2.0 Filter code)
-- | --
CGI / FastCGI | Rasmus Lerdorf, Stig Bakken, Shane Caraveo, Dmitry Stogov
CLI | Edin Kadribasic, Marcus Boerger, Johannes Schlueter, Moriyoshi Koizumi, Xinchen Hui
Embed | Edin Kadribasic
FastCGI Process Manager | Andrei Nigmatulin, dreamcat4, Antony Dovgal, Jerome Loyet
litespeed | George Wang
phpdbg | Felipe Pena, Joe Watkins, Bob Weinand
```

Can anyone confirm this is fixed now?

**Comment by ghost** [comment]
I agree with @nickweavers . We need some confirmation as well in order to go live with this setup.

**Comment by Sekhar-Kutikuppala** [comment]
This issue is fixed in the latest [AL2 platform updates](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-09-03-al2.html).
