### ISSUE TITLE
.ebextensions commands won't execute when configurations are changed from AWS console.

### ISSUE THREAD

**Issue by akbarnasr** [aws/elastic-beanstalk-roadmap#84]
I have some environments with AL2 platform When I change some configuration from the AWS console, my commands in config files won't be executed. I tried to put "sudo" before all command to make sure about permission issue but it didn't work. All things work perfectly when I deploy my application from EB CLI.

I checked "cfn-init.log", When I changed configurations, It doesn't log anything.

I've used platforms with this spec: PHP 7.4 running on 64bit Amazon Linux 2/3.1.0

**Comment by gmsantos** [comment]
You should use the new confighooks to execute your commands when you change environment configurations in AL2. See: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html

**Comment by akbarnasr** [comment]
Thanks, I'll change my configuration files.

**Comment by akbarnasr** [comment]
@gmsantos I couldn't find anything to execute some commands only in leader instance with platform hooks and confighooks. Is there anything that is not mentioned in documents?

**Comment by gmsantos** [comment]
Idk @akbarnasr

**Comment by akbarnasr** [comment]
Thank you so much for your help
