### ISSUE TITLE
Bug: version deployments on AL2 - Apache + PHP 7.4 fail

### ISSUE THREAD

**Issue by dave-irvine** [aws/elastic-beanstalk-roadmap#85]
Output of `eb-engine.log` is:

```
2020/08/24 10:17:31.209953 [ERROR] update processes [cfn-hup php-fpm healthd httpd] pid symlinks failed with error Read pid source file /run/httpd.pid failed with error:open /run/httpd.pid: no such file or directory      
2020/08/24 10:17:31.209966 [ERROR] An error occurred during execution of command [app-deploy] - [Track pids in healthd]. Stop running the command. Error: update processes [cfn-hup php-fpm healthd httpd] pid symlinks failed with error Read pid source file /run/httpd.pid failed with error:open /run/httpd.pid: no such file or directory
```

However the file does exist.

Full details: https://forums.aws.amazon.com/thread.jspa?threadID=325990&tstart=0

**Comment by rwhagw** [comment]
This is also causing successive deployments to fail due to an incorrect application version running.

**Comment by Sekhar-Kutikuppala** [comment]
This issue is addressed in latest platform version (64bit Amazon Linux 2 v3.1.1 running PHP 7.4)

**Comment by adamjpeterson** [comment]
FYI this exact issue is happening for me on an instance I launched today. 64bit Amazon Linux 2 v3.1.1 running PHP 7.4
