### ISSUE TITLE
No way to execute platform hooks only on leader instance on AL2

### ISSUE THREAD

**Issue by akbarnasr** [aws/elastic-beanstalk-roadmap#86]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

I tried to upgrade my environments to Amazon Linux 2, I used .ebextension configs for some commands but they didn't work on configuration updates. I tried to change my commands by new recommendations on AWS documentation by platform hooks and confighooks but I couldn't find any way to specify leader_only in any place. I checked all configs in the instance and I couldn't see anything that represents is this a leader instance or not.

Because hooks run in shell it will be good we have access to the Variable that represents is this instance leader or not.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**

Amazon Linux 2 in platform hooks and confighooks parts.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I saw a solution in #15 but it is not complete and reliable and also a general way for all users.
Also, I could find a shell script in EB Samples repository for [cron-leaderonly-linux.config](https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/instance-configuration/cron-leaderonly-linux.config) that contains a code to detect leader instance but it's not so simple to use and also not a general way for all users.

**Are you currently working around this issue?**
I've used .ebextensions config files for this kind of commands but they don't work on configuration changes.

**Comment by vonmaster** [comment]
Dear AWS staff, could please provide an update regarding this topic? It seems that there is a growing demand from the community; clarification is needed.

**Comment by akbarnasr** [comment]
Finally, I can find a way to detect leader instance. There is an environment variable with the name `EB_IS_COMMAND_LEADER`. I don't know when they add it.

You can use it in your scripts like this

```
if [[ "$EB_IS_COMMAND_LEADER" == "true" ]]; then
  COMMANDS
fi
```

**Comment by vonmaster** [comment]
Thank you so much, @akbarnasr

**Comment by markotitel** [comment]
Or don't use Platfrom Hooks for LEADER tasks

**Comment by rgaino** [comment]
> Or don't use Platfrom Hooks for LEADER tasks

`.config` files when using the Docker engine are executed before the new container is running, which means new migration files are not present yet. I described the problem here: https://forums.aws.amazon.com/thread.jspa?messageID=986065.

@akbarnasr 's solution is the only one that worked for us.

**Comment by dhrumil4u360** [comment]
@akbarnasr I don't think this ENV variable is available anymore. I have check it with `PHP 7.4 running on 64bit Amazon Linux 2`. Is there any other way around it?

**Comment by rgaino** [comment]
> @akbarnasr I don't think this ENV variable is available anymore. 

@dhrumil4u360 I have just used it very recently with success, I can confirm it's there. But the variable only exists at the hook execution time, if you ssh into the instance you won't find it.

**Comment by dhrumil4u360** [comment]
@rgaino  I see.. Yes, I just SSHed to server and checked it. I haven't checked it while running hook. Let me verify it during hook. Thanks for the suggestion.

**Comment by tiptopcoder** [comment]
> Finally, I can find a way to detect leader instance. There is an environment variable with the name `EB_IS_COMMAND_LEADER`. I don't know when they add it.
> 
> You can use it in your scripts like this
> 
> ```
> if [[ "$EB_IS_COMMAND_LEADER" == "true" ]]; then
>   COMMANDS
> fi
> ```

Do you know where can I get the list of EB built-in environment variables? I couldn't find anywhere in AWS docs.

**Comment by rgaino** [comment]
> Do you know where can I get the list of EB built-in environment variables? I couldn't find anywhere in AWS docs.

Not even `EB_IS_COMMAND_LEADER` is documented. It's very frustrating.
I suggest you create a hook that runs the `printenv` command and writes to a file, then you can read from that file and see what variables are present. But if my memory serves me right, `EB_IS_COMMAND_LEADER` was the only one.

**Comment by mathieujobin** [comment]
On Amazon Linux 2 - Docker platform, it appears the `.platform/hooks/*/scripts` are entirely ignored ;(
