### ISSUE TITLE
Config deployment replaces app code but does not run platform hooks, breaking app

### ISSUE THREAD

**Issue by revroad-dev** [aws/elastic-beanstalk-roadmap#88]
When I change environment variables via the AWS Elastic Beanstalk web interface it runs some sort of config deployment, replacing `/var/app/current`, but it does not seem to execute the scripts in `.platform/hooks` like it does with a normal deployment. This breaks my app.

Specifically, I am using Python + Django and I have a platform hook that runs `collectstatic`, putting the static files into the /var/app/current/static directory:

```
#!/bin/bash

source /var/app/venv/*/bin/activate
export PYTHONPATH=/var/app/staging
export DJANGO_SETTINGS_MODULE=my_project.settings

if [[ "$EB_IS_COMMAND_LEADER" == "true" ]]; then
  python manage.py migrate
fi

django-admin collectstatic --noinput --clear
```

After changing an environment variable, the static folder is gone and does not get recreated because the platform hook is not run.

Am I doing something wrong or is this a bug? 

I see from the documentation there are separate `confighooks` but I can't imagine I should have to do the `collectstatic` in both an app platform hook and a config platform hook?

**Comment by axlon** [comment]
I am having this issue too on Beanstalk 3.1.0 using the PHP platform.

**Comment by gmsantos** [comment]
I would assume that you need to copy the script to confighooks too.

Just curious, the `if [[ "$EB_IS_COMMAND_LEADER" == "true" ]]; then` works properly? I could update some scripts from .ebextensions with that :)

**Comment by linjian8** [comment]
To provide hooks that run during a configuration deployment, place them under the .platform/confighooks directory in your source bundle. The same three subdirectories as for application deployment hooks apply.

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html

**Comment by revroad-dev** [comment]
@linjian8 

I already mentioned `confighooks` in my question. That does not answer my question.

**Comment by saranshsingh1** [comment]
@revroad-dev 

From what I've seen for the `config-deploy` logs in `/var/log/eb-engine.log` file, the complete `/var/app/current` directory is replaced during the process of `config-deploy` just the same way as the `app-deploy` process.

Since you're collecting the static assets in the `/var/app/current` directory, you'd have to run the `collectstatic` command again.

##### NOTE: I've noticed that the files in the `.ebextensions` folder were not getting executed for me. So you'd want to look our for those cases as well.

**Comment by januszm** [comment]
If `/var/app/current` is replaced with the unpacked application bundle, but the usual hooks do not work (e.g.`rails asset:precompile` or the Django equivalent), then this is a bug that should be resolved at the platform level. People use some workarounds for this by adding precompile or collectstatic calls and similar to confighooks, but these are just patches. If the `app/current` directory changes, we have to call the typical deploy hooks, if it doesn't change, we could leave it to the developers, but it's still a precarious solution.

UPDATE: I meant this (happens during regular deployment)

```
[INFO] Running command /bin/su webapp -c bundle exec /opt/elasticbeanstalk/config/private/checkforraketask.rb assets:precompile
[INFO] Found assets:precompile task in Rakefile
```
It looks like `/opt/elasticbeanstalk/config/private/checkforraketask.rb` should also be executed for config deploys IF the application bundle is unpacked.

**Comment by r0bchain** [comment]
@revroad-dev  Did you add the script inside /confighooks/**postdeploy**? In my case, the script in there is running after updating the environment variables in EB.
