### ISSUE TITLE
Support Zen2 EPYC based C5a instances

### ISSUE THREAD

**Issue by janost** [aws/elastic-beanstalk-roadmap#89]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
What do you want us to build?
I'd like to run my Beanstalk-hosted application on [C5a instances](https://aws.amazon.com/about-aws/whats-new/2020/06/now-available-amazon-ec2-c5a-instances-featuring-2nd-generation-amd-epyc-processors/). It would be great if Beanstalk supported them.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
If so, which one(s)?
We're currently running a PHP-based application, however I believe this would be beneficial for all platforms.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
C5a instances provide similar or slightly better performance in most workloads as C5 instances and they also cost less.

**Are you currently working around this issue?**
How are you currently solving this problem?
We're currently using C5 instances.

**Additional context**
Anything else we should know?
C5a instances are already available outside of Beanstalk. Please see [this blogpost](https://aws.amazon.com/about-aws/whats-new/2020/06/now-available-amazon-ec2-c5a-instances-featuring-2nd-generation-amd-epyc-processors/).

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-09-20-dynamic-instance-type.html
