### ISSUE TITLE
Glassfish on Amazon Linux 2 platform

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#9]
We're working on building out this and other platforms on top of Amazon Linux 2 (AL2). With our AL2 platforms, we are refreshing and rethinking each platform based on feedback we’ve gotten from customers. If you have any questions or suggestions for this platform, please add a comment in the issue.

**Comment by Sekhar-Kutikuppala** [comment]
To update your environments running on a Preconfigured Docker Glassfish platform version based on Amazon Linux AMI, we recommend you to use the latest Docker on Amazon Linux 2 platform version. To update your environments to the latest Docker AL2 platform version, see "[Deploying a Glassfish application to the Docker platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker-glassfish-tutorial.html)" tutorial in the AWS Elastic Beanstalk Developer Guide.
