### ISSUE TITLE
Set a bunch of environment variables

### ISSUE THREAD

**Issue by ggregoire** [aws/elastic-beanstalk-roadmap#90]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**

Let's say my app has 10 environments variables. With the current UI (1 input for the key, 1 input for the value), it takes me 20 copy/paste to set all these variables.

I thought the UI could allow us to upload an `.env` file or to copy/paste an `.env` file into a textarea.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**

No.

**Comment by chadhayton** [comment]
Thanks for your feedback.  You should be able to use .ebextensions to resolve this issue.  For additional details, please see this link:
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-softwaresettings.html#environments-cfg-softwaresettings-configfiles
